.github/workflows/CI.yml
- This fixes the pipeline for pull requests opened
from forks.
=> chore: fix pipeline for pull requests from forks

.github/workflows/CI.yml
- This fixes the pipeline for pull requests opened
from forks.
=> chore: fix pipeline forks pull requests next

packages/react/src/checkout/hooks/useCheckout.ts
Update useEffect on useCheckout hook to run also after it is mounted
None.
=> fix(react): creating checkout just runs on mount

packages/core/src/bags/hooks/useBagItem.js, packages/core/src/bags/redux/__tests__/selectors.test.js, packages/core/src/bags/redux/selectors.js, packages/core/src/bags/redux/utils/__tests__/buildBagItem.test.js, packages/core/src/bags/redux/utils/__tests__/createBagItemHash.test.js, packages/core/src/bags/redux/utils/buildBagItem.js, packages/core/src/bags/redux/utils/createBagItemHash.js, packages/core/src/contents/__tests__/utils.test.js, packages/core/src/contents/redux/__tests__/reducer.test.js, packages/core/src/contents/redux/actionTypes.js, packages/core/src/contents/redux/actions/__tests__/__snapshots__/doGetCommercePages.test.js.snap, packages/core/src/contents/redux/actions/__tests__/doGetCommercePages.test.js, packages/core/src/contents/redux/actions/doGetCommercePages.js, packages/core/src/contents/redux/actions/index.js, packages/core/src/contents/redux/reducer.js, packages/core/src/contents/utils.js, packages/core/src/products/__tests__/withProductActions.test.js, packages/core/src/products/details/redux/__tests__/__snapshots__/serverInitialState.test.js.snap, packages/core/src/products/details/redux/serverInitialState.js, packages/core/src/products/withProductActions.js, packages/react/src/bags/hooks/__tests__/useBagItem.test.js, packages/react/src/bags/hooks/useBagItem.js, tests/__fixtures__/bags/bag.fixtures.js, tests/__fixtures__/bags/bagItem.fixtures.js, tests/__fixtures__/contents/commercePages.fixtures.js, tests/__fixtures__/contents/index.js
Scheduled release for 07-12-21.
=> Release 07-12-21

package.json, scripts/yalc.sh
- Add script to publish all packages
- Add script to publish core or react
=> chore: add yalc to scripts

package.json, scripts/yalc.sh
- Add script to publish all packages
- Add script to publish core or react
=> chore: add yalc to scripts next

packages/core/src/bags/redux/selectors.js, packages/core/src/products/listing/redux/selectors.js, packages/core/src/products/listing/utils/buildListingHash.js
This updates the documentation about product types to be according
to the API.
Also, this fixes some documentation typos.
=> chore(core): update documentation about product types

packages/redux/src/bags/selectors.ts
This updates the documentation about product types to be according
to the API.
=> chore(redux): update documentation about product types

package.json, scripts/yalc-publish.sh, scripts/yalc-push.sh
Add just two scripts to publish and push, instead of having multiple scripts for each package.
None.
=> chore: refactor yalc scripts next

packages/react/src/analytics/integrations/GA4/validation/eventSchemas.js, packages/react/src/analytics/integrations/shared/validation/eventSchemas.js
=> fix: fix ga4 promocode_applied event schema

packages/core/src/contents/client/getSearchContents.js, packages/core/src/contents/redux/actions/doGetContent.js
More query parameters listed on search contents endpoint documentation:
- target
- metadataCustom
- metadataSearchTagsValues
=> docs: add new query parameter contents

packages/client/src/contents/getSearchContents.ts, packages/client/src/contents/types/contents.types.ts, packages/redux/src/contents/actions/factories/fetchContentFactory.ts, packages/redux/src/contents/actions/fetchContent.ts
More query parameters listed on search contents endpoint documentation
- target
- metadataCustom
- metadataSearchTagsValues
None.
=> docs: add new query parameters contents next

packages/core/src/contents/redux/actions/doGetCommercePages.js, packages/react/src/content/hooks/__tests__/__fixtures__/CommercePage.fixtures.js, packages/react/src/content/hooks/__tests__/__snapshots__/useCommercePage.test.js.snap, packages/react/src/content/hooks/__tests__/useCommercePage.test.js, packages/react/src/content/hooks/index.js, packages/react/src/content/hooks/useCommercePage.js, tests/__fixtures__/contents/commercePages.fixtures.js
Create a new hook to commerce page
Fix redux doGetCommercePage to ranking work correctly
=> feat(react): create hook commerce pages

packages/core/src/contents/redux/actions/doGetCommercePages.js, packages/react/src/content/hooks/__tests__/__fixtures__/CommercePage.fixtures.js, packages/react/src/content/hooks/__tests__/__snapshots__/useCommercePage.test.js.snap, packages/react/src/content/hooks/__tests__/useCommercePage.test.js, packages/react/src/content/hooks/index.js, packages/react/src/content/hooks/useCommercePage.js, tests/__fixtures__/contents/commercePages.fixtures.js
=> Release 04-01-22

packages/react/src/bags/hooks/__tests__/useBag.test.tsx, packages/react/src/bags/hooks/index.ts, packages/react/src/bags/hooks/types/index.ts, packages/react/src/bags/hooks/types/useBag.ts, packages/react/src/bags/hooks/useBag.ts, packages/react/src/categories/hooks/useCategories.ts, tests/__fixtures__/bags/bag.fixtures.ts
This adds a `useBag` hooks that includes all logic associated with a bag.
None
=> feat(react): add useBag hook

packages/react/src/wishlists/hooks/__tests__/useWishlist.test.tsx, packages/react/src/wishlists/hooks/index.ts, packages/react/src/wishlists/hooks/types/index.ts, packages/react/src/wishlists/hooks/types/useWishlist.ts, packages/react/src/wishlists/hooks/useWishlist.ts, tests/__fixtures__/wishlists/wishlists.fixtures.ts
This adds a `useWishlist` hook that includes all logic associated with the wishlist.
=> feat(react): add `useWishlist` hook

packages/react/src/wishlists/index.ts
This adds an `index.ts` file to the wishlist chunk, to export everything.
=> feat(react): add index file to export everything from the wishlist chunk

packages/core/src/returns/client/__tests__/getPickupCapabilities.test.js, packages/core/src/returns/client/getPickupCapabilities.js
- Fix returns account migration service tests
=> fix(core): fix returns account migration service tests

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, packages/core/src/returns/client/__fixtures__/getPickupCapabilities.fixtures.js, packages/core/src/returns/client/__fixtures__/getReferences.fixtures.js, packages/core/src/returns/client/__fixtures__/getReturn.fixtures.js, packages/core/src/returns/client/__fixtures__/patchReturn.fixtures.js, packages/core/src/returns/client/__fixtures__/postReturn.fixtures.js, packages/core/src/returns/client/__tests__/__snapshots__/getPickupCapabilities.test.js.snap, packages/core/src/returns/client/__tests__/getPickupCapabilities.test.js, packages/core/src/returns/client/__tests__/getReferences.test.js, packages/core/src/returns/client/__tests__/getReturn.test.js, packages/core/src/returns/client/__tests__/patchReturn.test.js, packages/core/src/returns/client/__tests__/postReturn.test.js, packages/core/src/returns/client/getPickupCapabilities.js, packages/core/src/returns/client/getReferences.js, packages/core/src/returns/client/getReturn.js, packages/core/src/returns/client/patchReturn.js, packages/core/src/returns/client/postReturn.js, packages/core/src/returns/redux/actions/__tests__/doGetPickupCapabilities.test.js, packages/core/src/returns/redux/actions/doGetPickupCapabilities.js
=> Release 11-01-22

packages/react/src/products/hooks/__tests__/useProductDetails.test.tsx, packages/react/src/products/hooks/index.ts, packages/react/src/products/hooks/types/index.ts, packages/react/src/products/hooks/types/useProductDetails.ts, packages/react/src/products/hooks/useProductDetails.ts, packages/react/src/products/index.ts, packages/redux/src/entities/selectors/products.ts, packages/redux/src/products/selectors/details.ts, tests/__fixtures__/products/state.fixtures.ts
This adds a useProductDetails hook that includes all logic associated with the product.
=> feat(react): add useProductDetails hook

.github/workflows/CI.yml, packages/core/src/products/listing/redux/__tests__/__snapshots__/serverInitialState.test.js.snap, packages/core/src/products/listing/redux/__tests__/serverInitialState.test.js, packages/core/src/products/listing/redux/serverInitialState.js, tests/__fixtures__/products/listing.fixtures.js
=> Release 18-01-22

package.json, packages/client/src/contents/__fixtures__/commercepages.fixtures.js, packages/client/src/contents/__fixtures__/contentTypes.fixtures.js, packages/client/src/contents/__fixtures__/contents.fixtures.js, packages/client/src/contents/__fixtures__/seo.fixtures.js, packages/client/src/contents/__tests__/__snapshots__/getCommercePages.test.js.snap, packages/client/src/contents/__tests__/__snapshots__/getContentTypes.test.js.snap, packages/client/src/contents/__tests__/__snapshots__/getSEO.test.js.snap, packages/client/src/contents/__tests__/__snapshots__/getSearchContents.test.js.snap, packages/client/src/contents/__tests__/getCommercePages.test.js, packages/client/src/contents/__tests__/getContentTypes.test.js, packages/client/src/contents/__tests__/getSEO.test.js, packages/client/src/contents/__tests__/getSearchContents.test.js, packages/client/tests/index.js, packages/client/tests/mswServer.js, yarn.lock
- Remove moxios inside contents
- add msw to fixtures
Refs #18 
None.
=> feat(client): add mock service worker contents

packages/redux/src/wishlists/selectors/__tests__/wishlistsSets.test.ts, packages/redux/src/wishlists/selectors/wishlistsSets.ts
This adds a new isWishlistFetched selector
=> feat(redux): add isWishlistSetFetched selector

packages/core/src/language/client/__mocks__/getTranslations.fixtures.js, packages/core/src/language/client/__tests__/__snapshots__/getTranslations.test.js.snap, packages/core/src/language/client/__tests__/getTranslations.test.js, packages/core/src/language/client/getTranslations.js, packages/core/src/language/client/index.js
- new client added search translations
None.
=> feat(core): create client search translations

packages/client/src/bags/__fixtures__/deleteBagItem.fixtures.ts, packages/client/src/bags/__fixtures__/getBag.fixtures.ts, packages/client/src/bags/__fixtures__/patchBagItem.fixtures.ts, packages/client/src/bags/__fixtures__/postBagItem.fixtures.ts, packages/client/src/bags/__tests__/__snapshots__/deleteBagItem.test.ts.snap, packages/client/src/bags/__tests__/__snapshots__/getBag.test.ts.snap, packages/client/src/bags/__tests__/__snapshots__/patchBagItem.test.ts.snap, packages/client/src/bags/__tests__/__snapshots__/postBagItem.test.ts.snap, packages/client/src/bags/__tests__/deleteBagItem.test.ts, packages/client/src/bags/__tests__/getBag.test.ts, packages/client/src/bags/__tests__/patchBagItem.test.ts, packages/client/src/bags/__tests__/postBagItem.test.ts
This replaces the moxios library with msw on bags client tests.
Refs #18 
None.
=> chore(client): replace moxios with msw bags

packages/client/src/merchantsLocations/__fixtures__/getMerchantsLocations.fixtures.ts, packages/client/src/merchantsLocations/__tests__/__snapshots__/getMerchantsLocations.test.ts.snap, packages/client/src/merchantsLocations/__tests__/getMerchantsLocations.test.ts
This replaces the usage of the `moxios` library with `msw` in the unit tests of the `merchantsLocations`
chunk.
Refs #18 
=> chore(client): replace moxios with msw in merchantsLocations

packages/core/src/subscriptions/client/__mocks__/deleteSubscription.fixtures.js, packages/core/src/subscriptions/client/__tests__/__snapshots__/deleteSubscription.test.js.snap, packages/core/src/subscriptions/client/__tests__/deleteSubscription.test.js, packages/core/src/subscriptions/client/deleteSubscription.js, packages/core/src/subscriptions/client/deleteSubscriptions.js, packages/core/src/subscriptions/client/index.js, packages/core/src/subscriptions/redux/actionTypes.js, packages/core/src/subscriptions/redux/actions/__tests__/doUnsubscribeFromSubscription.test.js, packages/core/src/subscriptions/redux/actions/doUnsubscribeAllSubscriptions.js, packages/core/src/subscriptions/redux/actions/doUnsubscribeFromSubscription.js, packages/core/src/subscriptions/redux/actions/index.js, yarn.lock
=> Release 01-02-22 

packages/react/src/analytics/integrations/GA4/GA4.js, packages/react/src/analytics/integrations/__tests__/GA4.test.js
- add set user on ga4 initialization.
=> fix(react): add set user on ga4 initialization

packages/core/src/checkout/client/__fixtures__/getOperation.fixtures.js, packages/core/src/checkout/client/__fixtures__/getOperations.fixtures.js, packages/core/src/checkout/client/__tests__/__snapshots__/getOperation.test.js.snap, packages/core/src/checkout/client/__tests__/__snapshots__/getOperations.test.js.snap, packages/core/src/checkout/client/__tests__/getOperation.test.js, packages/core/src/checkout/client/__tests__/getOperations.test.js, packages/core/src/checkout/client/getOperation.js, packages/core/src/checkout/client/getOperations.js, packages/core/src/checkout/client/index.js
This PR add new operations endpoints
=> feat(core): add operations endpoints

packages/core/src/checkout/redux/__fixtures__/checkoutSelector.fixtures.js, packages/core/src/checkout/redux/__tests__/reducer.test.js, packages/core/src/checkout/redux/__tests__/selectors.test.js, packages/core/src/checkout/redux/actionTypes.js, packages/core/src/checkout/redux/actions/__tests__/__snapshots__/doGetOperation.test.js.snap, packages/core/src/checkout/redux/actions/__tests__/__snapshots__/doGetOperations.test.js.snap, packages/core/src/checkout/redux/actions/__tests__/doGetOperation.test.js, packages/core/src/checkout/redux/actions/__tests__/doGetOperations.test.js, packages/core/src/checkout/redux/actions/doGetOperation.js, packages/core/src/checkout/redux/actions/doGetOperations.js, packages/core/src/checkout/redux/actions/index.js, packages/core/src/checkout/redux/reducer.js, packages/core/src/checkout/redux/selectors.js
This PR adds new get operations and get operation actions
=> feat(redux): get operations actions

packages/core/src/analytics/integrations/Omnitracking/Omnitracking.js, packages/core/src/analytics/integrations/Omnitracking/__tests__/omnitracking-helper.test.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/core/src/checkout/redux/__fixtures__/checkoutSelector.fixtures.js, packages/core/src/checkout/redux/__tests__/reducer.test.js, packages/core/src/checkout/redux/__tests__/selectors.test.js, packages/core/src/checkout/redux/actionTypes.js, packages/core/src/checkout/redux/actions/__tests__/__snapshots__/doGetOperation.test.js.snap, packages/core/src/checkout/redux/actions/__tests__/__snapshots__/doGetOperations.test.js.snap, packages/core/src/checkout/redux/actions/__tests__/doGetOperation.test.js, packages/core/src/checkout/redux/actions/__tests__/doGetOperations.test.js, packages/core/src/checkout/redux/actions/doGetOperation.js, packages/core/src/checkout/redux/actions/doGetOperations.js, packages/core/src/checkout/redux/actions/index.js, packages/core/src/checkout/redux/reducer.js, packages/core/src/checkout/redux/selectors.js, packages/react/src/analytics/integrations/GA4/GA4.js, packages/react/src/analytics/integrations/GA4/commands.js, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/__tests__/GA4.test.js
=> Release 22 02 22

packages/core/src/entities/schemas/facet.js
=> Release 08-03-2022

packages/core/src/checkout/client/__fixtures__/deleteOrderItem.fixtures.js, packages/core/src/checkout/client/__fixtures__/patchOrderItem.fixtures.js, packages/core/src/checkout/client/__tests__/__snapshots__/deleteOrderItem.test.js.snap, packages/core/src/checkout/client/__tests__/__snapshots__/patchOrderItem.test.js.snap, packages/core/src/checkout/client/__tests__/deleteOrderItem.test.js, packages/core/src/checkout/client/__tests__/patchOrderItem.test.js, packages/core/src/checkout/client/deleteOrderItem.js, packages/core/src/checkout/client/index.js, packages/core/src/checkout/client/patchOrderItem.js, packages/core/src/checkout/redux/__fixtures__/checkoutSelector.fixtures.js, packages/core/src/checkout/redux/__tests__/reducer.test.js, packages/core/src/checkout/redux/__tests__/selectors.test.js, packages/core/src/checkout/redux/actionTypes.js, packages/core/src/checkout/redux/actions/__tests__/__snapshots__/doDeleteOrderItem.test.js.snap, packages/core/src/checkout/redux/actions/__tests__/__snapshots__/doUpdateOrderItem.test.js.snap, packages/core/src/checkout/redux/actions/__tests__/doDeleteOrderItem.test.js, packages/core/src/checkout/redux/actions/__tests__/doUpdateOrderItem.test.js, packages/core/src/checkout/redux/actions/doDeleteOrderItem.js, packages/core/src/checkout/redux/actions/doUpdateOrderItem.js, packages/core/src/checkout/redux/actions/index.js, packages/core/src/checkout/redux/reducer.js, packages/core/src/checkout/redux/selectors.js
=> Release 15-03-2022

packages/core/src/contents/__tests__/utils.test.js, packages/core/src/contents/utils.js, packages/react/src/content/hooks/useCommercePage.js
=> Release 22-03-2022

packages/react/src/content/helpers/renderContent.js
. Add lodash map to renderContent for better deal with undefined states.
None.
=> fix(react): add lodash map to render content

packages/react/src/content/hooks/useContentType.js
Include new params in hook useContentType such as preview, to preview content
Include new params in hook useContentType such as preview, to be able to preview content
None.
=> feat(react): include new params hook useContentType

packages/client/src/users/__tests__/getTitles.test.ts, packages/react/src/contents/helpers/__tests__/renderContent.test.tsx, packages/react/src/contents/helpers/renderContent.tsx, packages/react/src/contents/structured-data/__tests__/product.test.tsx, packages/react/src/contents/structured-data/__tests__/videoObject.test.tsx, packages/redux/src/addresses/types/action.types.ts
. Add lodash map to render content to better deal with the undefined state.
None.
=> fix(react): add lodash map render content

packages/core/src/subscriptions/client/__tests__/putSubscriptions.test.js, packages/core/src/subscriptions/client/putSubscriptions.js, packages/core/src/subscriptions/redux/__fixtures__/storeSubscriptionsState.fixtures.js, packages/core/src/subscriptions/redux/__tests__/selectors.test.js, packages/core/src/subscriptions/redux/actions/__tests__/doUpdateUserSubscriptions.test.js, packages/core/src/subscriptions/redux/actions/doUpdateUserSubscriptions.js, packages/core/src/subscriptions/redux/reducer/__tests__/user.test.js, packages/core/src/subscriptions/redux/reducer/user.js, packages/core/src/subscriptions/redux/selectors.js, packages/react/src/content/helpers/renderContent.js, packages/react/src/content/hooks/useContentType.js
=> Release 29-03-22

packages/analytics/src/Analytics.ts, packages/analytics/src/User.ts, packages/redux/src/analytics/middlewares/__tests__/setUser.test.ts, packages/redux/src/analytics/middlewares/setUser.ts, packages/redux/src/analytics/middlewares/types/index.ts, packages/redux/src/analytics/middlewares/types/setUser.types.ts
- This adds a conversion of the analytics user middleware to typescript.
"None".
=> feat(blackout-analytics|blackout-redux): convert analytic's user middleware

packages/core/src/analytics/redux/middlewares/wishlist.js, packages/core/src/helpers/client/interceptors/authentication/AxiosAuthenticationTokenManager.js, packages/react/src/analytics/integrations/GA/GA.js, packages/react/src/analytics/integrations/GA4/GA4.js, packages/react/src/analytics/integrations/__tests__/GA.test.js, packages/react/src/analytics/integrations/__tests__/GA4.test.js, packages/react/src/authentication/hooks/__tests__/useAuthentication.test.js
=> Release 05-04-22 

packages/react/src/analytics/integrations/Castle/Castle.js, packages/react/src/analytics/integrations/Castle/CastleV2.js, packages/react/src/analytics/integrations/__tests__/Castle.test.js, packages/react/src/analytics/integrations/__tests__/CastleV2.test.js
This PR adds changes that were made on the next version that make sense to apply to the main version. 
With this, we avoid having a breaking change for those that start to use the Castle V2 with the current stable version of the react package and have to migrate later to the next major version (box v2), since the contract for this integration will now be the same.
=> fix(react): update integration options contract

packages/react/src/content/components/Component.js, packages/react/src/content/components/base/__tests__/CallToAction.test.js, packages/react/src/content/components/base/__tests__/ComponentsList.test.js, packages/react/src/content/components/base/__tests__/Html.test.js, packages/react/src/content/components/base/__tests__/__snapshots__/CallToAction.test.js.snap, packages/react/src/content/components/base/__tests__/__snapshots__/ComponentsList.test.js.snap, packages/react/src/content/components/base/__tests__/__snapshots__/Html.test.js.snap, packages/react/src/content/components/base/__tests__/__snapshots__/text.test.js.snap, packages/react/src/content/components/base/__tests__/text.test.js, packages/react/src/content/components/base/callToAction/CallToAction.js, packages/react/src/content/components/base/componentsList/ComponentsList.js, packages/react/src/content/components/base/html/Html.js, packages/react/src/content/components/base/index.js, packages/react/src/content/components/base/text/Text.js
Create base components to render content with a legacy structure
None
=> feat(react): add base components to render components

packages/react/src/analytics/integrations/Vitorino/Vitorino.js, packages/react/src/analytics/integrations/Vitorino/__tests__/Vitorino.test.js
=> Release 26-04-22

packages/core/src/profile/client/__fixtures__/postPhoneNumberValidations.fixtures.js, packages/core/src/profile/client/__fixtures__/postPhoneTokenValidations.fixtures.js, packages/core/src/profile/client/__fixtures__/postPhoneTokens.fixtures.js, packages/core/src/profile/client/__tests__/postPhoneNumberValidations.test.js, packages/core/src/profile/client/__tests__/postPhoneTokenValidations.test.js, packages/core/src/profile/client/__tests__/postPhoneTokens.test.js, packages/core/src/profile/client/postPhoneNumberValidations.js, packages/core/src/profile/client/postPhoneTokenValidations.js, packages/core/src/profile/client/postPhoneTokens.js
Fix paths on phone tokens requests
None
=> fix(core): fix phone tokens endpoints requests

packages/client/src/users/__fixtures__/postPhoneNumberValidations.fixtures.ts, packages/client/src/users/__fixtures__/postPhoneTokenValidations.fixtures.ts, packages/client/src/users/__fixtures__/postPhoneTokens.fixtures.ts, packages/client/src/users/__tests__/postPhoneNumberValidations.test.ts, packages/client/src/users/__tests__/postPhoneTokenValidations.test.ts, packages/client/src/users/__tests__/postPhoneTokens.test.ts, packages/client/src/users/postPhoneNumberValidations.ts, packages/client/src/users/postPhoneTokenValidations.ts, packages/client/src/users/postPhoneTokens.ts
Fix paths on phone tokens requests
None
=> fix(client): fix phone tokens endpoints requests

packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.js, packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.js.snap, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/GA4/validation/eventSchemas.js
- add support for multiple gender on ga4 signup newsletter track.
None.
=> feat(blackout-react): add support multigender ga4's signup newsletter

packages/core/src/contents/redux/serverInitialState.js, packages/core/src/contents/utils.js, tests/__fixtures__/contents/contents.fixtures.js
Include metadata inside serverInitialState from first render
None
=> fix(core): contents server initial state

packages/react/src/content/helpers/index.js, packages/react/src/content/utils/__tests__/sortContentType.test.js, packages/react/src/content/utils/sortContentType.js
. re-export renderContent and renderComponent
. export default sortContentType
None.
=> feat(react): add exports contents

packages/core/src/entities/schemas/searchResult.js
Fix gender filter segment without description.
This also adds a special case for when the filter segment is an attribute.
=> fix: fix gender filter segment without description

packages/react/src/analytics/integrations/Zaraz/__tests__/Zaraz.test.ts, packages/react/src/analytics/integrations/Zaraz/__tests__/__snapshots__/Zaraz.test.ts.snap, packages/react/src/analytics/integrations/Zaraz/constants.ts, packages/react/src/analytics/integrations/Zaraz/eventsMapper.ts
- This adds mappings for the 'Sign-Up Form Completed' events in Zaraz.
=> feat(blackout-react): implement signup form completed mappings in zaraz (next)

packages/core/src/authentication/client/__fixtures__/postPasswordRecover.fixtures.js, packages/core/src/authentication/client/__tests__/__snapshots__/postPasswordRecover.test.js.snap, packages/core/src/authentication/client/__tests__/postPasswordRecover.test.js, packages/core/src/authentication/client/postPasswordRecover.js, packages/core/src/authentication/redux/actions/__tests__/doPasswordRecover.test.js, packages/core/src/authentication/redux/actions/doPasswordRecover.js
- New recover password endpoint.
None.
=> feat(core): new recover password endpoint

packages/redux/src/users/actionTypes.ts, packages/redux/src/users/actions/__tests__/resetUser.test.ts, packages/redux/src/users/actions/__tests__/resetUserState.test.ts, packages/redux/src/users/actions/index.ts, packages/redux/src/users/actions/resetUser.ts, packages/redux/src/users/actions/resetUserState.ts, packages/redux/src/users/types/action.types.ts
=> feat(redux): add reset action for users

packages/client/src/forms/index.ts, packages/client/src/index.ts, packages/client/tsconfig.build.json, packages/client/tsconfig.json, packages/redux/src/forms/__tests__/reducer.test.ts, packages/redux/src/forms/actionTypes.ts, packages/redux/src/forms/actions/__tests__/fetchFormSchema.test.ts, packages/redux/src/forms/actions/__tests__/resetFormSchema.test.ts, packages/redux/src/forms/actions/__tests__/submitFormData.test.ts, packages/redux/src/forms/actions/factories/fetchFormSchemaFactory.ts, packages/redux/src/forms/actions/factories/index.ts, packages/redux/src/forms/actions/factories/submitFormDataFactory.ts, packages/redux/src/forms/actions/factories/types/FetchFormSchemaFactory.types.ts, packages/redux/src/forms/actions/factories/types/SubmitFormSchemaFactory.types.ts, packages/redux/src/forms/actions/fetchFormSchema.ts, packages/redux/src/forms/actions/index.ts, packages/redux/src/forms/actions/resetFormSchema.ts, packages/redux/src/forms/actions/submitFormData.ts, packages/redux/src/forms/index.ts, packages/redux/src/forms/reducer.ts, packages/redux/src/forms/selectors.ts, packages/redux/src/forms/types/action.types.ts, packages/redux/src/forms/types/state.types.ts, packages/redux/src/index.ts, packages/redux/src/types/storeState.types.ts, packages/redux/tsconfig.build.json, packages/redux/tsconfig.json
- Adds exports instructions for forms modules in the
root index file of each package.
- Adds provisory tsconfig.json files for both client and
redux packages.
- Imports of form modules now must be done from the root
for both @farfetch/blackout-client and @farfetch/blackout-redux
packages.
```js
// Previously
import {
getFormSchema,
postFormData,
} from '@farfetch/blackout-core/forms/client';
import {
fetchFormSchema,
getFormSchemaByCode,
getFormSchemaError,
getSubmitFormDataError,
isFormSchemaLoading,
isSubmitFormDataLoading,
resetFormSchema,
submitFormData,
} from '@farfetch/blackout-core/forms/redux';
// Now
import {
getFormSchema,
postFormData,
} from '@farfetch/blackout-client';
import {
fetchFormSchema,
getFormSchemaByCode,
getFormSchemaError,
getSubmitFormDataError, …
```
=> feat(blackout-client|blackout-redux): export forms modules in root index file

packages/core/src/contents/client/__fixtures__/contentPages.fixtures.js, packages/core/src/contents/client/__tests__/__snapshots__/getContentPages.test.js.snap, packages/core/src/contents/client/__tests__/getContentPages.test.js, packages/core/src/contents/client/getCommercePages.js, packages/core/src/contents/client/getContentPages.js, packages/core/src/contents/client/index.js, packages/core/src/contents/redux/__tests__/reducer.test.js, packages/core/src/contents/redux/actionTypes.js, packages/core/src/contents/redux/actions/__tests__/__snapshots__/doGetContentPages.test.js.snap, packages/core/src/contents/redux/actions/__tests__/doGetCommercePages.test.js, packages/core/src/contents/redux/actions/__tests__/doGetContentPages.test.js, packages/core/src/contents/redux/actions/doGetCommercePages.js, packages/core/src/contents/redux/actions/doGetContentPages.js, packages/core/src/contents/redux/actions/index.js, packages/core/src/contents/redux/reducer.js, packages/react/src/content/hooks/__tests__/__fixtures__/ContentPage.fixtures.js, packages/react/src/content/hooks/__tests__/__snapshots__/useContentPage.test.js.snap, packages/react/src/content/hooks/__tests__/useContentPage.test.js, packages/react/src/content/hooks/index.js, packages/react/src/content/hooks/useContentPage.js, tests/__fixtures__/contents/contentPages.fixtures.js, tests/__fixtures__/contents/index.js
Create a new client and redux to new endpoint contentPages.
None.
=> feat(core): add new client contentPages

packages/client/src/wishlists/types/postWishlistItem.types.ts
=> fix(client): update size prop to optional

packages/react/src/addresses/hooks/__tests__/__fixtures__/Addresses.fixtures.tsx, packages/react/src/addresses/hooks/__tests__/useAddresses.test.tsx, packages/react/src/addresses/hooks/useAddresses.ts
- Added export types to all exports.
- Removed one useEffect as it was redundant.
- Fixed a few functions using useSelector that were returning undefined.
None.
=> fix(react): fix useAddresses functions and export types

packages/redux/src/entities/__tests__/__snapshots__/reducer.test.js.snap, packages/redux/src/users/actionTypes.ts, packages/redux/src/users/reducer.ts, packages/redux/src/users/types/action.types.ts
Add users reset actions to reducer
=> fix(redux): add users reset actions to reducer

packages/core/src/locale/redux/__tests__/selectors.test.js, packages/core/src/locale/redux/__tests__/serverInitialState.test.js, packages/core/src/locale/redux/actions/__tests__/__snapshots__/doGetCountries.test.js.snap, packages/core/src/locale/redux/actions/__tests__/__snapshots__/doGetCountry.test.js.snap, packages/core/src/locale/redux/selectors.js, packages/core/src/locale/redux/serverInitialState.js, tests/__fixtures__/locale/locale.fixtures.js
Mapped requestSourceCountryCode key to locale reducer and create getCountryCultures method
=> feat(redux): map requestSourceCountryCode key to locale reducer and create getCountryCultures method

packages/core/src/payments/client/__fixtures__/postApplePaySession.fixtures.js, packages/core/src/payments/client/__tests__/__snapshots__/postApplePaySession.test.js.snap, packages/core/src/payments/client/__tests__/postApplePaySession.test.js, packages/core/src/payments/client/index.js, packages/core/src/payments/client/postApplePaySession.js, packages/core/src/payments/redux/__fixtures__/applePaySession.fixtures.js, packages/core/src/payments/redux/__tests__/reducer.test.js, packages/core/src/payments/redux/__tests__/selectors.test.js, packages/core/src/payments/redux/actionTypes.js, packages/core/src/payments/redux/actions/__tests__/__snapshots__/doPostApplePaySession.test.js.snap, packages/core/src/payments/redux/actions/__tests__/doPostApplePaySession.test.js, packages/core/src/payments/redux/actions/doPostApplePaySession.js, packages/core/src/payments/redux/actions/index.js, packages/core/src/payments/redux/reducer.js, packages/core/src/payments/redux/selectors.js
Create new client and redux for applepaysession
Adding client and redux for applepaysession.
None.
=> feat(client|redux): add applepaysession related packages

packages/core/src/orders/client/__fixtures__/getOrderShippingAddressChangeRequests.fixtures.js, packages/core/src/orders/client/__fixtures__/postOrderShippingAddressChangeRequests.fixtures.js, packages/core/src/orders/client/__tests__/__snapshots__/getOrderShippingAddressChangeRequests.test.js.snap, packages/core/src/orders/client/__tests__/__snapshots__/postOrderShippingAddressChangeRequests.test.js.snap, packages/core/src/orders/client/__tests__/getOrderShippingAddressChangeRequests.test.js, packages/core/src/orders/client/__tests__/postOrderShippingAddressChangeRequests.test.js, packages/core/src/orders/client/getOrderShippingAddressChangeRequests.js, packages/core/src/orders/client/index.js, packages/core/src/orders/client/postOrderShippingAddressChangeRequests.js, packages/core/src/orders/redux/actionTypes.js, packages/core/src/orders/redux/actions/__tests__/__snapshots__/doGetOrderShippingAddressChangeRequests.test.js.snap, packages/core/src/orders/redux/actions/__tests__/__snapshots__/doPostOrderShippingAddressChangeRequests.test.js.snap, packages/core/src/orders/redux/actions/__tests__/doGetOrderShippingAddressChangeRequests.test.js, packages/core/src/orders/redux/actions/__tests__/doPostOrderShippingAddressChangeRequests.test.js, packages/core/src/orders/redux/actions/doGetOrderShippingAddressChangeRequests.js, packages/core/src/orders/redux/actions/doPostOrderShippingAddressChangeRequests.js, packages/core/src/orders/redux/actions/index.js, packages/core/src/orders/redux/reducer.js
Add order change address endpoints
=> feat(core|redux): add order change address endpoints

package.json, packages/client/package.json, packages/client/src/users/authentication/types/postGuestToken.types.ts, packages/react/package.json, packages/redux/package.json, yarn.lock
Due to issues with type checking on other projects, the following changes concerning types were made:
- Add @types/proper-url-join and @types/crypto-js
- Remove unnecessary dependencies
- Update PostGuestTokens Data type, as the inner data properties are optional
None.
By sending us your contributions, you agree that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)
=> fix(client): Fix multiple issues related to types

packages/core/src/analytics/integrations/Omnitracking/Omnitracking.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/react/src/analytics/__tests__/context.test.js, packages/react/src/analytics/context.js
=> dev-main-02-08-22 

scripts/release.sh
- This adds main branch to the release script to enable
releases when the next branch is merged into main.
=> chore: add main branch to release script

packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added wishlist event to omnitracking mapppers.
None.
=> feat(core): add omnitracking's wishlist page tracking mappings

.github/workflows/CI.yml
- This adds `v1` branch to pipeline in order to be able to generate
releases for the previous version after the next version is merged.
=> chore: add v1 branch to pipeline

packages/core/src/contents/client/__fixtures__/commercepages.fixtures.js, packages/core/src/contents/client/__tests__/getCommercePages.test.js, packages/core/src/contents/client/getCommercePages.js, packages/core/src/contents/redux/actions/__tests__/__snapshots__/doGetCommercePages.test.js.snap, packages/core/src/contents/redux/actions/__tests__/doGetCommercePages.test.js, packages/core/src/contents/redux/actions/doGetCommercePages.js, tests/__fixtures__/contents/commercePages.fixtures.js
implement pagination on commercepages v2 endpoint
=> feat(redux): add request pagination on commercepage v2 endpoint

packages/core/src/analytics/__fixtures__/trackData.fixtures.js, packages/core/src/analytics/integrations/Omnitracking/__tests__/omnitracking-helper.test.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/core/src/analytics/integrations/index.js, packages/core/src/analytics/integrations/shared/dataMappings/signupNewsletterGenderMappings.js, packages/react/src/analytics/integrations/shared/dataMappings/index.js
- Added signup_newsletter event mapping.
- Refactor of SignupNewsletterGendarMappings.
#477
=> Feat add omnitracking signup newsletter event

packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added homepage event mapping.
None.
=> feat(core): add omnitracking's homepage mappings

packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added generic page event mapping.
None.
=> feat(core): add omnitracking's generic page mappings

packages/core/src/analytics/__fixtures__/trackData.fixtures.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/core/src/analytics/redux/middlewares/__tests__/bag.test.js, packages/core/src/analytics/redux/middlewares/bag.js
- Added add to bag event mapping;
- Added remove from bag event mapping.
None.
=> feat(core): add omnitracking's bag events mappings

packages/react/src/analytics/integrations/GA4/GA4.js, packages/react/src/analytics/integrations/__tests__/GA4.test.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
=> Weekly Release - 27-09-22

packages/client/src/locale/__fixtures__/getCountryStateCities.fixtures.ts, packages/client/src/locale/__fixtures__/getCountryStates.fixtures.ts
This fixes some types of locale files related to the cities and states responses.
=> fix(client): fix locale types

packages/core/src/orders/client/helpers/adaptOrderDetails.js, packages/core/src/orders/client/postOrderItemActivities.js, packages/core/src/orders/redux/actions/__tests__/__snapshots__/doGetOrderDetails.test.js.snap, packages/core/src/orders/redux/actions/doGetOrderDetails.js, packages/core/src/orders/redux/actions/doPostOrderItemActivities.js
=> Weekly Release - 18-10-22

packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts, packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap, packages/analytics/src/integrations/Omnitracking/definitions.ts, packages/redux/src/analytics/middlewares/__tests__/bag.test.ts, packages/redux/src/analytics/middlewares/bag.ts
- Added add to bag event mapping;
- Added remove from bag event mapping.
none
=> feat(analytics|redux): add omnitracking's bag events mappings next

packages/core/src/returns/client/getReturn.js, packages/core/src/returns/client/getReturnsFromOrder.js, packages/core/src/returns/client/postReturn.js
- Added comments about new return data
None.
=> feat(core): review return endpoints

packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap, packages/analytics/src/integrations/Omnitracking/definitions.ts
- Added filters cleared and filters applied event mapping to omnitracking
None
=> feat(analytics): add omnitracking's filters events next

packages/core/CHANGELOG.md, packages/core/package.json, packages/react/package.json, yarn.lock
This PR updates the castle.io dependency. This new version fixes some bugs on their end.
None.
=> chore(react): update castle dependency version

packages/react/package.json, yarn.lock
This PR updates the castle.io dependency. This new version fixes some bugs on their end.
None.
=> chore(react): update castle.io dependency - next

packages/core/src/analytics/integrations/Omnitracking/__tests__/omnitracking-helper.test.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/core/src/returns/client/getReturn.js, packages/core/src/returns/client/getReturnsFromOrder.js, packages/core/src/returns/client/postReturn.js, packages/react/package.json, packages/react/src/analytics/integrations/GA4/eventMapping.js, yarn.lock
=> Weekly Release - 25-10-22

packages/core/src/returns/redux/__tests__/reducer.test.js, packages/core/src/returns/redux/__tests__/selectors.test.js, packages/core/src/returns/redux/reducer.js, packages/core/src/returns/redux/selectors.js
- Add pickup reschedule to reducer
None.
=> fix(core): pickup reschedule reducer

packages/core/src/analytics/redux/middlewares/__tests__/setUser.test.js, packages/core/src/analytics/redux/middlewares/setUser.js
=> Weekly Release - 15-11-22

packages/core/src/contents/client/__fixtures__/seo.fixtures.js, packages/core/src/contents/client/__tests__/getSEO.test.js, packages/core/src/contents/client/getSEO.js
Update endpoint path to seo metadata
=> feat(core): update seo metadata endpoint

packages/core/src/profile/client/__fixtures__/getGuestUserBenefits.fixtures.js, packages/core/src/profile/client/__fixtures__/getUserBenefits.fixtures.js, packages/core/src/profile/client/__tests__/__snapshots__/getGuestUserBenefits.test.js.snap, packages/core/src/profile/client/__tests__/__snapshots__/getUserBenefits.test.js.snap, packages/core/src/profile/client/__tests__/getGuestUserBenefits.test.js, packages/core/src/profile/client/__tests__/getUserBenefits.test.js, packages/core/src/profile/client/getGuestUserBenefits.js, packages/core/src/profile/client/getUserBenefits.js, packages/core/src/profile/client/index.js, packages/core/src/profile/redux/__fixtures__/userBenefits.fixtures.js, packages/core/src/profile/redux/actionTypes.js, packages/core/src/profile/redux/actions/__tests__/__snapshots__/doGetGuestUserBenefits.test.js.snap, packages/core/src/profile/redux/actions/__tests__/__snapshots__/doGetUserBenefits.test.js.snap, packages/core/src/profile/redux/actions/__tests__/doGetGuestUserBenefits.test.js, packages/core/src/profile/redux/actions/__tests__/doGetUserBenefits.test.js, packages/core/src/profile/redux/actions/doGetGuestUserBenefits.js, packages/core/src/profile/redux/actions/doGetUserBenefits.js, packages/core/src/profile/redux/actions/index.js
This adds user and guest user benefits endpoints
=> feat(core): add user and guestUser benefits endpoints

packages/core/src/contents/redux/actions/doGetSEO.js, packages/react/src/content/hooks/useSEO.js
Add baseurl param on seo docs.
=> chore: add baseurl param on seo docs

packages/react/src/wishlists/hooks/useWishlist.ts, packages/redux/src/wishlists/reducer/wishlists.ts, packages/redux/src/wishlists/types/state.types.ts
Refactored wishlist's reducer initial state to be consistent with bag's one.
=> chore(redux|react): Refactor whishlist initial state

packages/core/src/contents/redux/actions/doGetSEO.js, packages/react/src/content/hooks/useSEO.js
=> Weekly Release - 29-11-22

packages/core/src/analytics/Analytics.js, packages/core/src/analytics/User.js, packages/core/src/analytics/__tests__/analytics.test.js, packages/react/src/content/hooks/useContentType.js, tests/flushPromises.js
=> Weekly Release - 06-12-22

packages/core/src/payments/redux/__fixtures__/getPaymentMethods.fixtures.js, packages/core/src/payments/redux/actions/doPostInstruments.js
This MR add just some JSDoc and mocks updates regarding the new changes to support new way to use the iDeal payment method
None.
=> chore(redux): Adyen HPP deprecation iDeal

packages/client/src/payments/types/paymentInstrumentData.types.ts, packages/client/src/payments/types/paymentMethods.types.ts, packages/client/src/payments/types/postPaymentIntentInstrument.types.ts, packages/redux/src/checkout/actions/__tests__/__snapshots__/fetchCheckoutOrderPaymentMethods.test.ts.snap, packages/redux/src/payments/actions/__tests__/__snapshots__/fetchPaymentMethodsByCountryAndCurrency.test.ts.snap, packages/redux/src/payments/actions/__tests__/__snapshots__/fetchPaymentMethodsByIntent.test.ts.snap, tests/__fixtures__/payments/payments.fixtures.ts
- This MR updates types and mocks to include changes related to Adyen HPP deprecation for iDeal payment method
None.
=> Chore(client|redux): Adyen HPP deprecation iDeal

packages/core/src/profile/client/__fixtures__/getUserReturns.fixtures.js, packages/core/src/profile/client/__tests__/__snapshots__/getUserReturns.test.js.snap, packages/core/src/profile/client/__tests__/getUserReturns.test.js, packages/core/src/profile/client/getUserReturns.js, packages/core/src/profile/client/index.js, packages/core/src/profile/redux/__fixtures__/userReturns.fixtures.js, packages/core/src/profile/redux/actionTypes.js, packages/core/src/profile/redux/actions/__tests__/__snapshots__/doGetUserReturns.test.js.snap, packages/core/src/profile/redux/actions/__tests__/doGetUserReturns.test.js, packages/core/src/profile/redux/actions/doGetUserReturns.js, packages/core/src/profile/redux/actions/index.js
=> Weekly Release: dev-main-03-01-23

packages/core/src/products/details/client/__fixtures__/getProductOutfits.fixtures.js, packages/core/src/products/details/client/__tests__/__snapshots__/getProductOutfits.test.js.snap, packages/core/src/products/details/client/__tests__/getProductOutfits.test.js, packages/core/src/products/details/client/getProductOutfits.js, packages/core/src/products/details/client/index.js, packages/core/src/products/details/redux/__tests__/__snapshots__/serverInitialState.test.js.snap, packages/core/src/products/details/redux/__tests__/reducer.test.js, packages/core/src/products/details/redux/actionTypes.js, packages/core/src/products/details/redux/actions/__tests__/__snapshots__/doGetProductOutfits.test.js.snap, packages/core/src/products/details/redux/actions/__tests__/doGetProductOutfits.test.js, packages/core/src/products/details/redux/actions/doGetProductOutfits.js, packages/core/src/products/details/redux/actions/index.js, packages/core/src/products/details/redux/reducer.js, packages/core/src/products/details/redux/selectors/__tests__/outfits.test.js, packages/core/src/products/details/redux/selectors/index.js, packages/core/src/products/details/redux/selectors/outfits.js, tests/__fixtures__/products/details.fixtures.js, tests/__fixtures__/products/products.fixtures.js
This adds the outfits endpoint that is used to fetch the outfits for a specific product.
None
=> feat(core): added product outfits endpoint

packages/react/src/utils/__tests__/validatePassword.test.js, packages/react/src/utils/index.js, packages/react/src/utils/validatePassword.js
Added a new function that validates the password and provides the relevant errors to display the necessary feedback to the user.
None.
=> feat(react): add password strength helper

packages/react/src/analytics/integrations/Forter/Forter.js, packages/react/src/analytics/integrations/Forter/constants.js, packages/react/src/analytics/integrations/Forter/forterHelper.js, packages/react/src/analytics/integrations/Forter/loadForterScriptForSiteId.js, packages/react/src/analytics/integrations/Nethone/Nethone.js, packages/react/src/analytics/integrations/Nethone/__tests__/nethone-helper.test.js, packages/react/src/analytics/integrations/Riskified.js, packages/react/src/analytics/integrations/Vitorino/Vitorino.js, packages/react/src/analytics/integrations/Vitorino/__tests__/Vitorino.test.js, packages/react/src/analytics/integrations/Vitorino/constants.js, packages/react/src/analytics/integrations/Vitorino/vitorino-helper.js, packages/react/src/analytics/integrations/__tests__/Forter.test.js, packages/react/src/analytics/integrations/__tests__/Nethone.test.js, packages/react/src/analytics/integrations/index.js, packages/react/src/analytics/integrations/shared/constants.js
- Deprecate nethone integration;
- Update Forter and Riskified integrations;
- Refactor of vitorino integrations to remove external script;
- Refactor of current tests and add new ones.
None.
=> feat(react): remove vitorino from external script

packages/core/src/authentication/client/__tests__/postRegister.test.js, packages/core/src/authentication/client/postRegister.js, packages/core/src/authentication/redux/actions/__tests__/doRegister.test.js, packages/core/src/authentication/redux/actions/doRegister.js
This adds metadata information on register client and redux action. Also updates the tests.
=> chore(core): add metadata params on user register flow

packages/client/src/contents/__tests__/getSEOMetadata.test.ts, packages/client/src/contents/types/seoMetadata.types.ts
- Add base URL to getSeoMetadata as a parameter.
=> Feat: add base url to seo metadada

.eslintrc.js, CONTRIBUTING.md
- This improves the current Contributing guide by adding the necessary steps to get the project running and contains additional information regarding the checks that a pull request should have.
=> chore: improve Contributing guide

packages/client/src/bags/types/bagItem.types.ts, packages/client/src/bags/types/patchBagItem.types.ts, packages/client/src/bags/types/postBagItem.types.ts, packages/client/src/types/common/index.ts, packages/client/src/types/common/jsonValue.types.ts, packages/client/src/types/common/metadata.types.ts
This adds the property `metadata` to bag item and respective requests types.
=> feat(client): add metadata to bag item and requests types

packages/client/src/checkout/__tests__/postCheckoutOrder.test.ts, packages/client/src/checkout/types/postCheckoutOrder.types.ts, packages/react/src/checkout/hooks/__tests__/useCheckout.test.tsx, packages/redux/src/checkout/actions/__tests__/createCheckoutOrder.test.ts
This adds the property metadata in POST checkout order request and types.
=> feat(client): add metadata in POST checkout order request and types

packages/core/src/analytics/__fixtures__/trackData.fixtures.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/__fixtures__/gaData.fixtures.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
- Added parameters to checkout_started event, regarding the analytics package improvements.
None.
=> feat(core|react): add parameters checkout started event

packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap, packages/analytics/src/integrations/Omnitracking/definitions.ts, packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap, packages/react/src/analytics/integrations/GA4/eventMapping.ts, tests/__fixtures__/analytics/track/checkoutStartedTrackData.fixtures.ts
- Added parameters to checkout_started event, regarding the analytics package improvements.
None.
=> feat(analytics|react): add parameters checkout started event next

.eslintrc.js, gitpkg.config.js, package.json, packages/analytics/package.json, packages/client/package.json, packages/react/package.json, packages/redux/package.json, scripts/release-git.sh, yarn.lock
This adds a `release:git` script which which will allow developers to install a version of the packages containing the changes they are developing without releasing them to npm. This script aims to facilitate QA process by using gitpkg underneath to publish a built version of the packages to a git repo of their choosing. The repo will receive a commit and a tag which can be used to add the dependency in an application so it can be sent for QA validation.
=> chore: add `release:git` script

packages/core/src/analytics/__fixtures__/trackData.fixtures.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/core/src/analytics/types/__tests__/__snapshots__/eventTypes.test.js.snap, packages/core/src/analytics/types/eventTypes.js, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/__fixtures__/gaData.fixtures.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
- Setup add_delivery_method event with the respective parameters asked in analytics package improvements.
None.
=> feat(core|react): add delivery method added event

packages/analytics/src/__tests__/__snapshots__/index.test.ts.snap, packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap, packages/analytics/src/integrations/Omnitracking/definitions.ts, packages/analytics/src/types/EventTypes.ts, packages/analytics/src/types/__tests__/__snapshots__/EventTypes.test.ts.snap, packages/react/src/__tests__/__snapshots__/index.test.ts.snap, packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap, packages/react/src/analytics/integrations/GA4/eventMapping.ts, tests/__fixtures__/analytics/track/deliveryMethodAddedTrackData.fixtures.mts, tests/__fixtures__/analytics/track/index.mts
Setup add_delivery_method event with the respective parameters asked in analytics package improvements.
None.
=> feat(analytics|react): add delivery method added event next

packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
- Fixed events switched tracker ids.
- Changed Clear filters name to clear_all_filters.
None.
=> fix(core|react): fix filters events

packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap, packages/analytics/src/integrations/Omnitracking/definitions.ts, packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap, packages/react/src/analytics/integrations/GA4/eventMapping.ts
Fixed events switched tracker ids.
Changed Clear filters name to clear_all_filters.
None.
=> fix(analytics|react): fix filters events next

packages/core/src/analytics/__fixtures__/trackData.fixtures.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/__fixtures__/gaData.fixtures.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
Changes regarding Analytics Package Improvements.
- Added checkout order id to edit_checkout_step event.
- Modified change_size event name to select_size.
None.
=> feat(core|react): add parameters edit checkout step event

packages/client/src/__tests__/__snapshots__/index.test.ts.snap, packages/client/src/products/types/productVariant.types.ts, tests/__fixtures__/products/productVariantsMerchantsLocations.fixtures.mts
This add the `publicationFeature` type to the `productVariant` type. It also updates the fixtures for `productVariant`.
=> chore: update Product Variant types with publication features

packages/core/src/analytics/__fixtures__/trackData.fixtures.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/__fixtures__/gaData.fixtures.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
Changes made on add_shipping_info regarding analytics package improvements.
- Removed address_finder parameter.
- Added checkout step and checkout order id.
None.
=> feat: add parameters add shipping info event

packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap, packages/analytics/src/integrations/Omnitracking/definitions.ts, packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap, packages/react/src/analytics/integrations/GA4/eventMapping.ts, tests/__fixtures__/analytics/track/addressInfoAddedTrackData.fixtures.mts
- Added checkout order id to add_address_info event.
None.
=> feat: add parameters add address info event next

packages/core/src/analytics/__fixtures__/trackData.fixtures.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/__fixtures__/gaData.fixtures.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
- Added index parameter to some events (index to GA4 and listIndex to omni).
_Note: listIndex isn't on omni contract but I've added it already to prepare the events for whenever the contract is updated with this new parameter._
None.
=> feat: add index parameter to events

packages/core/src/analytics/redux/middlewares/__tests__/bag.test.js, packages/core/src/analytics/redux/middlewares/__tests__/wishlist.test.js, packages/core/src/analytics/redux/middlewares/bag.js, packages/core/src/analytics/redux/middlewares/wishlist.js
- Adjust middlewares:
- Changing size on cart or wishlist pages will trigger only change size
- Changing quantity always add/remove products events and change quantity event
- When add product that was already on bag, should not trigger change quantity event.
- Add tests
None.
=> feat(core): exclude update product event

packages/redux/src/analytics/middlewares/__tests__/bag.test.ts, packages/redux/src/analytics/middlewares/__tests__/wishlist.test.ts, packages/redux/src/analytics/middlewares/bag.ts, packages/redux/src/analytics/middlewares/wishlist.ts
- Adjust middlewares:
- Changing size on cart or wishlist pages will trigger only change size
- Changing quantity always add/remove products
events and change quantity event
- When add product that was already on bag, should not trigger
change quantity event.
- Add tests
None.
=> feat(redux): exclude update product event for next

packages/core/src/analytics/__fixtures__/trackData.fixtures.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/core/src/analytics/redux/middlewares/__tests__/bag.test.js, packages/core/src/analytics/redux/middlewares/__tests__/wishlist.test.js, packages/core/src/analytics/redux/middlewares/bag.js, packages/core/src/analytics/redux/middlewares/wishlist.js, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/__fixtures__/gaData.fixtures.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
=> Release dev-main-18-04-23

packages/react/src/analytics/__tests__/analytics.test.ts, packages/react/src/analytics/analytics.ts, packages/react/src/analytics/integrations/GA4/GA4.ts, packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.ts, packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- Add parameter to each integration to fill package versions on omni and ga4 requests.
- Omnitracking, are missing update contract that would allow to send this new parameter on final request.
None.
=> feat(analytics|react): add package version to analytics next

packages/core/src/analytics/Analytics.js, packages/core/src/analytics/utils/constants.js, packages/react/src/analytics/__tests__/analytics.test.js, packages/react/src/analytics/analytics.js, packages/react/src/analytics/integrations/GA4/GA4.js, packages/react/src/analytics/integrations/__tests__/GA4.test.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
- Add parameter to each integration to fill package versions on omni and ga4 requests.
- Omnitracking, are missing update contract that would allow to send
this new parameter on final request.
None.
=> feat(core|react): add package version analytics ga4 omni

packages/client/src/orders/types/orderItem.types.ts
- Added optional property metadata to order item types.
None.
=> chore(client): add metadata to order item types

packages/analytics/src/__tests__/__snapshots__/index.test.ts.snap, packages/analytics/src/utils/getters.ts, packages/react/src/__tests__/__snapshots__/index.test.ts.snap, packages/react/src/analytics/integrations/AnalyticsApi/AnalyticsApi.ts, packages/react/src/analytics/integrations/AnalyticsApi/__tests__/AnalyticsApi.test.ts, packages/react/src/analytics/integrations/AnalyticsApi/index.ts, packages/react/src/analytics/integrations/AnalyticsApi/types/index.ts, packages/react/src/analytics/integrations/AnalyticsApi/types/types.ts, packages/react/src/analytics/integrations/index.ts
Setup of analytics api integration on next
None.
=> feat: setup analytics api integration next

packages/core/src/analytics/utils/getters.js, packages/react/src/analytics/integrations/AnalyticsApi/AnalyticsApi.js, packages/react/src/analytics/integrations/AnalyticsApi/index.js, packages/react/src/analytics/integrations/__tests__/AnalyticsApi.test.js, packages/react/src/analytics/integrations/index.js
Setup of analytics api integration on next
None.
=> feat: setup analytics api integration

packages/react/src/analytics/integrations/GTM/__tests__/__snapshots__/GTM.test.ts.snap, packages/react/src/analytics/integrations/GTM/eventsMapper.ts, packages/redux/src/analytics/middlewares/__tests__/wishlist.test.ts, packages/redux/src/analytics/middlewares/bag.ts, packages/redux/src/analytics/middlewares/wishlist.ts
- add locationId, parameter on bag and wishlist middlewares;
- add total parameter on some GTM events.
None.
=> Feat analytics improvements

packages/core/src/subscriptions/client/__mocks__/deleteSubscription.fixtures.js, packages/core/src/subscriptions/client/__tests__/deleteSubscription.test.js, packages/core/src/subscriptions/client/deleteSubscription.js, packages/core/src/subscriptions/redux/actions/__tests__/doUnsubscribeFromSubscription.test.js, packages/core/src/subscriptions/redux/actions/doUnsubscribeFromSubscription.js
- update action and client of unsubcription to allow usage of parameter `package`
- add tests
None.
=> feat: add package to unsubcribe action

packages/core/src/analytics/redux/middlewares/bag.js, packages/core/src/analytics/redux/middlewares/wishlist.js, packages/react/src/analytics/integrations/AnalyticsApi/AnalyticsApi.js, packages/react/src/analytics/integrations/GTM/eventsMapper.js, packages/react/src/analytics/integrations/__tests__/AnalyticsApi.test.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GTM.test.js.snap, packages/react/src/bags/hooks/useBagItem.js
- Analytics Package improvements requires **index** (position) parameter to pass through **deleteBagItem**. This parameter wasn't being included.
- add locationId, parameter on bag and wishlist middlewares;
- add total parameter on some GTM events;
- refactor AnalyticsApi eventList management.
None.
=> feat(core|react): analytics improvements

packages/core/src/contents/redux/__tests__/reducer.test.js, packages/core/src/contents/redux/reducer.js, packages/react/src/content/hooks/useSEO.js
Fix useSEO hook looping requests
=> fix(react|redux): useSEO hook looping requests

packages/react/src/bags/hooks/useBagItem.js
- changed position parameter into meta, allowing pass many parameters instead of current position.
None.
=> fix(react): change handle delete bag item parameters

packages/core/src/analytics/__fixtures__/trackData.fixtures.js, packages/core/src/analytics/integrations/Omnitracking/__tests__/omnitracking-helper.test.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap, packages/core/src/analytics/utils/__tests__/getters.test.js, packages/core/src/analytics/utils/getters.js, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/__fixtures__/gaData.fixtures.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
=> Release dev-v1-23-05-23

packages/client/src/users/authentication/types/postUser.types.ts, packages/client/src/users/authentication/types/putUser.types.ts, packages/client/src/users/authentication/types/user.types.ts
This adds the `metadata` field to the `User` type and on its operations put and post.
=> chore: add metadata field to user type and its operations

.github/workflows/CreateRelease.yml, .github/workflows/SendEmail.yml, packages/react/src/analytics/integrations/GA4/eventMapping.js, packages/react/src/analytics/integrations/__fixtures__/gaData.fixtures.js, packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap, packages/react/src/bags/hooks/useBagItem.js
=> Release dev-v1-30-05-23

packages/redux/MIGRATION.md
This MR updates the migration guide for Blackout Redux v1 to Main
=> chore(redux): update migraton guide

packages/react/src/__tests__/__snapshots__/index.test.ts.snap, packages/react/src/orders/hooks/__tests__/useOrder.test.ts, packages/react/src/orders/hooks/__tests__/useOrderShippingAddressChangeRequests.test.ts, packages/react/src/orders/hooks/index.ts, packages/react/src/orders/hooks/types/index.ts, packages/react/src/orders/hooks/types/useOrderShippingAddressChangeRequests.ts, packages/react/src/orders/hooks/useOrder.ts, packages/react/src/orders/hooks/useOrderShippingAddressChangeRequests.ts
This adds the useOrderShippingAddressChangeRequest hook.
None.
=> feat(react): create useOrderShippingAddressChangeRequest hook

packages/react/src/__tests__/__snapshots__/index.test.ts.snap, packages/react/src/checkout/hooks/__tests__/useCheckout.test.tsx, packages/react/src/checkout/hooks/types/useCheckout.types.ts, packages/react/src/checkout/hooks/useCheckout.ts, packages/react/src/helpers/__tests__/validateShippingAddressZipCode.test.ts, packages/react/src/helpers/index.ts, packages/react/src/helpers/validateShippingAddressZipCode.ts, packages/react/src/locale/hooks/__tests__/useCountries.test.tsx, packages/redux/src/locale/actions/__tests__/__snapshots__/fetchCountries.test.ts.snap, packages/redux/src/locale/actions/__tests__/fetchCountries.test.ts, tests/__fixtures__/checkout/checkout.fixtures.mts, tests/__fixtures__/locale/locale.fixtures.mts
Create a function and utils to validate if a zip code from a shipping address is valid.
=> feat: implement eircode validation

packages/react/src/__tests__/__snapshots__/index.test.ts.snap, packages/react/src/checkout/hooks/__tests__/useCheckout.test.tsx, packages/react/src/checkout/hooks/types/useCheckout.types.ts, packages/react/src/checkout/hooks/useCheckout.ts, packages/react/src/helpers/__tests__/validateShippingAddressZipCode.test.ts, packages/react/src/helpers/index.ts, packages/react/src/helpers/validateShippingAddressZipCode.ts, packages/react/src/locale/hooks/__tests__/useCountries.test.tsx, packages/react/src/orders/hooks/__tests__/useOrder.test.ts, packages/react/src/orders/hooks/__tests__/useOrderShippingAddressChangeRequests.test.ts, packages/react/src/orders/hooks/index.ts, packages/react/src/orders/hooks/types/index.ts, packages/react/src/orders/hooks/types/useOrderShippingAddressChangeRequests.ts, packages/react/src/orders/hooks/useOrder.ts, packages/react/src/orders/hooks/useOrderShippingAddressChangeRequests.ts, packages/redux/MIGRATION.md, packages/redux/src/locale/actions/__tests__/__snapshots__/fetchCountries.test.ts.snap, packages/redux/src/locale/actions/__tests__/fetchCountries.test.ts, tests/__fixtures__/checkout/checkout.fixtures.mts, tests/__fixtures__/locale/locale.fixtures.mts
Weekly (late) release for blackout packages.
=> Release dev-main-27-06-23

packages/core/src/sharedWishlists/redux/index.js, packages/core/src/sharedWishlists/redux/reducer.js
=> Release dev-v1-04-07-23

packages/react/src/analytics/integrations/GA4/GA4.ts, packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.ts, packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap, packages/react/src/analytics/integrations/GA4/constants.ts
- remove invalid fields (started with "_") of ga4 analytics integration.
None. 
=> feat(react): remove invalid fields on ga4 integration for `main`

packages/core/src/analytics/__fixtures__/trackData.fixtures.js, packages/core/src/analytics/integrations/Omnitracking/definitions.js, packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js, packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added new recommendations parameters to some events.
None.
=> feat: add recommendations parameters for `v1`

packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap, packages/analytics/src/integrations/Omnitracking/definitions.ts, packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts, tests/__fixtures__/analytics/page/productPageData.fixtures.mts
- Added new recommendations parameters to some events.
None.
=> feat: add recommendations parameters for `main`

packages/react/src/contents/components/base/media/__tests__/Thumbnail.test.tsx, packages/react/src/contents/components/base/media/__tests__/__snapshots__/Thumbnail.test.tsx.snap, packages/react/src/contents/components/base/media/components/audio/Audio.tsx, packages/react/src/contents/components/base/media/components/image/Image.tsx, packages/react/src/contents/components/base/media/components/image/styles.ts, packages/react/src/contents/components/base/media/components/thumbnail/Thumbnail.tsx, packages/react/src/contents/components/base/media/components/thumbnail/index.ts, packages/react/src/contents/components/base/media/components/thumbnail/styles.ts, packages/react/src/contents/components/base/media/components/utils/getFallbackSrcImage.ts, packages/react/src/contents/components/base/media/components/utils/index.ts, packages/react/src/contents/components/base/media/components/video/Video.tsx, packages/react/src/contents/types/base.types.ts
- Add thumbnail component and adapt media components to use it.
- Change return of image component in `noscript` context, returning a picture tag on it.
=> feat: improve base components

packages/client/src/__tests__/__snapshots__/index.test.ts.snap, packages/client/src/checkout/__fixtures__/patchCheckoutSession.fixtures.ts, packages/client/src/checkout/__tests__/__snapshots__/patchCheckoutSession.test.ts.snap, packages/client/src/checkout/__tests__/patchCheckoutSession.test.ts, packages/client/src/checkout/index.ts, packages/client/src/checkout/patchCheckoutSession.ts, packages/client/src/checkout/types/index.ts, packages/client/src/checkout/types/patchCheckoutSession.types.ts, packages/react/src/contents/components/base/media/__tests__/Thumbnail.test.tsx, packages/react/src/contents/components/base/media/__tests__/__snapshots__/Thumbnail.test.tsx.snap, packages/react/src/contents/components/base/media/components/audio/Audio.tsx, packages/react/src/contents/components/base/media/components/image/Image.tsx, packages/react/src/contents/components/base/media/components/image/styles.ts, packages/react/src/contents/components/base/media/components/thumbnail/Thumbnail.tsx, packages/react/src/contents/components/base/media/components/thumbnail/index.ts, packages/react/src/contents/components/base/media/components/thumbnail/styles.ts, packages/react/src/contents/components/base/media/components/utils/getFallbackSrcImage.ts, packages/react/src/contents/components/base/media/components/utils/index.ts, packages/react/src/contents/components/base/media/components/video/Video.tsx, packages/react/src/contents/types/base.types.ts
=> Release dev-main-15-08-23

packages/react/src/contents/components/base/media/components/thumbnail/index.ts
Fix the thumbnail index export, the extension of file was wrong.
=> fix: component thumbnail index export

packages/client/src/users/authentication/__fixtures__/postAccountLink.fixtures.ts, packages/client/src/users/authentication/__fixtures__/postSocialLogin.fixtures.ts, packages/client/src/users/authentication/__tests__/postAccountLink.test.ts, packages/client/src/users/authentication/__tests__/postSocialLogin.test.ts, packages/client/src/users/authentication/postAccountLink.ts, packages/client/src/users/authentication/postSocialLogin.ts
=> fix: fix social login and account link endpoint paths

packages/react/src/__tests__/__snapshots__/index.test.ts.snap, packages/react/src/users/hooks/__tests__/useUserClosetItems.test.ts, packages/react/src/users/hooks/__tests__/useUserClosets.test.ts, packages/react/src/users/hooks/index.ts, packages/react/src/users/hooks/types/index.ts, packages/react/src/users/hooks/types/useUserClosetItems.types.ts, packages/react/src/users/hooks/types/useUserClosets.types.ts, packages/react/src/users/hooks/useUserClosetItems.ts, packages/react/src/users/hooks/useUserClosets.ts, packages/redux/src/users/actionTypes.ts
This adds the new closets hooks.
None
=> Feat(react): Closet hooks

packages/react/src/analytics/integrations/Forter/loadForterScriptForSiteId.js
=> feat: update forter script for `v1`

packages/analytics/src/__tests__/__snapshots__/index.test.ts.snap, packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap, packages/analytics/src/integrations/Omnitracking/definitions.ts, packages/analytics/src/types/EventType.ts, packages/analytics/src/types/__tests__/__snapshots__/EventType.test.ts.snap, packages/react/src/__tests__/__snapshots__/index.test.ts.snap, packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap, packages/react/src/analytics/integrations/GA4/eventMapping.ts, packages/react/src/analytics/integrations/GA4/validation/eventSchemas.ts, tests/__fixtures__/analytics/track/index.mts, tests/__fixtures__/analytics/track/reviewCheckoutTrackData.fixtures.mts
- Added new analytics event - Review Checkout
- Updated unit tests for this event as well.
None.
=> feat: add review checkout analytics event to `main`

packages/client/src/checkout/types/postCheckoutOrder.types.ts
=> New impersonation flow types - customerId on Post order

packages/client/src/helpers/client/__tests__/axiosInstance.test.ts
Our concern with this test is to avoid the `baseURL` changes, for instance, when the code on the `next` branch is merged with the `main` branch.
=> chore: adding unit test to guarantee the right baseURL

packages/react/src/analytics/integrations/GA4/GA4.js, packages/react/src/analytics/integrations/GA4/constants.js, packages/react/src/analytics/integrations/GTM/GTM.js, packages/react/src/analytics/integrations/GTM/constants.js, packages/react/src/analytics/integrations/GTM/gtmTag.js, packages/react/src/analytics/integrations/index.js, packages/react/src/analytics/integrations/shared/GoogleConsentMode/GoogleConsentMode.js, packages/react/src/analytics/integrations/shared/GoogleConsentMode/__tests__/GoogleConsentMode.test.js, packages/react/src/analytics/integrations/shared/GoogleConsentMode/__tests__/__snapshots__/GoogleConsentMode.test.js.snap, packages/react/src/analytics/integrations/shared/GoogleConsentMode/index.js, packages/react/src/analytics/integrations/shared/index.js
Add support to google consent mode.
=> feat: add support to google consent mode for `v1`

packages/core/src/analytics/Analytics.js, packages/react/src/analytics/__tests__/analytics.test.js, packages/react/src/analytics/analytics.js, packages/react/src/analytics/integrations/GA4/GA4.js
- Set up analytics behavior for referrer attribution in SPA;
- Fix additional issues related to analytics context in tracking events;
- Fix inconsistencies in analytics tests.
=> feat: analytics referrer attribution spa on `v1`

packages/core/src/addresses/client/__fixtures__/deleteDefaultBillingAddress.fixtures.js, packages/core/src/addresses/client/__fixtures__/deleteDefaultShippingAddress.fixtures.js, packages/core/src/addresses/client/__tests__/__snapshots__/deleteDefaultBillingAddress.test.js.snap, packages/core/src/addresses/client/__tests__/__snapshots__/deleteDefaultShippingAddress.test.js.snap, packages/core/src/addresses/client/__tests__/deleteDefaultBillingAddress.test.js, packages/core/src/addresses/client/__tests__/deleteDefaultShippingAddress.test.js, packages/core/src/addresses/client/deleteDefaultBillingAddress.js, packages/core/src/addresses/client/deleteDefaultShippingAddress.js, packages/core/src/addresses/client/index.js, packages/core/src/addresses/redux/__tests__/reducer.test.js, packages/core/src/addresses/redux/actionTypes.js, packages/core/src/addresses/redux/actions/__tests__/__snapshots__/doDeleteDefaultBillingAddress.test.js.snap, packages/core/src/addresses/redux/actions/__tests__/__snapshots__/doDeleteDefaultShippingAddress.test.js.snap, packages/core/src/addresses/redux/actions/__tests__/doDeleteDefaultBillingAddress.test.js, packages/core/src/addresses/redux/actions/__tests__/doDeleteDefaultShippingAddress.test.js, packages/core/src/addresses/redux/actions/doDeleteDefaultBillingAddress.js, packages/core/src/addresses/redux/actions/doDeleteDefaultShippingAddress.js, packages/core/src/addresses/redux/actions/index.js, packages/core/src/addresses/redux/reducer.js, packages/core/src/analytics/Analytics.js, packages/core/src/entities/redux/__tests__/__snapshots__/reducer.test.js.snap, packages/react/src/analytics/__tests__/analytics.test.js, packages/react/src/analytics/analytics.js, packages/react/src/analytics/integrations/GA4/GA4.js
=> Weekly release `v1` 23-01-24 
