Farfetch/blackout

- packages/react/src/bags/hooks/types/useBagItem.ts
- packages/react/src/bags/hooks/useBagItem.ts
- packages/redux/src/bags/utils/__tests__/buildBagItem.test.ts
- packages/redux/src/bags/utils/__tests__/generateBagItemHash.test.ts
- packages/redux/src/bags/utils/buildBagItem.ts
- packages/redux/src/bags/utils/generateBagItemHash.ts
- tests/__fixtures__/bags/bag.fixtures.ts
- tests/__fixtures__/bags/bagItem.fixtures.ts
This adds the parameter `productAggregatorId` to add to bag requests handled by the `useBagItem` hook and to `buildBagItem` util. It also allows the possibility to receive other future parameters.
It also modifies the `generateBagItemHash` method to include `productAggregatorId` so we can differentiate between items in
different bundles.
None.
> feat(react|redux): provide product aggregator id to bag

- packages/core/src/bags/hooks/useBagItem.js
- packages/core/src/bags/redux/utils/__tests__/buildBagItem.test.js
- packages/core/src/bags/redux/utils/__tests__/createBagItemHash.test.js
- packages/core/src/bags/redux/utils/buildBagItem.js
- packages/core/src/bags/redux/utils/createBagItemHash.js
- packages/core/src/products/__tests__/withProductActions.test.js
- packages/core/src/products/withProductActions.js
- packages/react/src/bags/hooks/__tests__/useBagItem.test.js
- packages/react/src/bags/hooks/useBagItem.js
- tests/__fixtures__/bags/bag.fixtures.js
- tests/__fixtures__/bags/bagItem.fixtures.js
This adds the parameter `productAggregatorId` to add to bag requests handled by both `useBagItem` hook and `withProductActions` hoc.
It also modifies the `createBagItemHash` method to include this parameter so we can differentiate between items in different bundles.
None
> feat(core|react): add productAggregatorId to add to bag requests

- packages/core/src/products/details/redux/__tests__/__snapshots__/serverInitialState.test.js.snap
- packages/core/src/products/details/redux/serverInitialState.js
This removes the entries `attributes`, `colorGrouping`, `fittings`, `measurements`, `merchantsLocations`, `recommendedSets`, `sets`, `sizeGuides` and `sizeScale` from `serverInitialState` to avoid having false positives in the `isLoading` and `isFetched` state when using server side rendering.
> fix(core): remove entries in server initial state of product/details

- packages/redux/src/products/serverInitialState/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/products/serverInitialState/__tests__/__snapshots__/products.test.ts.snap
- packages/redux/src/products/serverInitialState/products.ts
This removes the entries `attributes`, `colorGrouping`, `fittings`, `measurements`,
`sizeguides` and `variantsByMerchantsLocations` from serverInitialState to avoid having false
positives in the `isLoading` and `isFetched` status when using server-side rendering.
> fix(redux): remove entries in server initial state of product/details

- packages/core/src/contents/__tests__/utils.test.js
- packages/core/src/contents/redux/__tests__/reducer.test.js
- packages/core/src/contents/redux/actionTypes.js
- packages/core/src/contents/redux/actions/__tests__/__snapshots__/doGetCommercePages.test.js.snap
- packages/core/src/contents/redux/actions/__tests__/doGetCommercePages.test.js
- packages/core/src/contents/redux/actions/doGetCommercePages.js
- packages/core/src/contents/redux/actions/index.js
- packages/core/src/contents/redux/reducer.js
- packages/core/src/contents/utils.js
- tests/__fixtures__/contents/commercePages.fixtures.js
- tests/__fixtures__/contents/index.js
This feature adds the commerce pages logic into contents redux, more specifically:
. Add action doGetCommercePages
. Update Content reducer
. Add ranking logic to contents utils
None.
> feat(core): add commerce pages redux

- packages/core/src/bags/redux/__tests__/selectors.test.js
- packages/core/src/bags/redux/selectors.js
The `getItemWholeQuantity` selector uses internally the `getBagItems` selector
and then iterates through the bag items to get the whole quantity. When the `getBagItems`
runs before the bag is fetched, its return value is `undefined` by default, which throws
an error when trying to `reduce`. This fix avoids that and makes this selector
return 0 if there are no bag or bag items.
> fix(core): make `getItemWholeQuantity` return 0 when there's no bag

- packages/redux/src/bags/__tests__/selectors.test.ts
- packages/redux/src/bags/selectors.ts
Our `getBagItems` selector is returning `undefined` when the bag or bag items don't exist but that
output breaks consistency and might create an error in other selectors that use `getBagItems` without
validating if it is an array or undefined. To validate if the bag is fetched or not we have other,
more specific, selectors.
> fix(redux): make `getBagItems` return empty array

- packages/core/src/helpers/client/interceptors/authentication/AuthenticationConfigOptions.js
- packages/core/src/helpers/client/interceptors/authentication/AxiosAuthenticationTokenManager.js
- packages/core/src/helpers/client/interceptors/authentication/__tests__/AxiosAuthenticationTokenManager.test.js
- packages/core/src/helpers/client/interceptors/authentication/errors.js
- packages/core/src/helpers/client/interceptors/authentication/token-providers/GuestTokenProvider.js
- packages/core/src/helpers/client/interceptors/authentication/token-providers/TokenProvider.js
- packages/core/src/helpers/client/interceptors/authentication/token-providers/UserTokenProvider.js
- packages/core/src/helpers/client/interceptors/authentication/token-providers/__tests__/GuestTokenProvider.test.js
- packages/core/src/helpers/client/interceptors/authentication/token-providers/__tests__/TokenData.test.js
- packages/core/src/helpers/client/interceptors/authentication/token-providers/__tests__/TokenProvider.test.js
- packages/react/src/authentication/contexts/UserProfileProvider.js
- packages/react/src/authentication/hooks/__tests__/useAuthentication.test.js
- packages/react/src/authentication/hooks/useUserAuthState.js
- Fixes the bug that happens when the guest user has expired
but the authentication provider continues to use the expired
guest user id when obtaining new guest tokens.
- Fixes a bug that the get access token promise was not
being set to null when the request to get access token fails
in both GuestTokenProvider and UserTokenProvider.
- Refactored the logic to change current token provider to live
inside AxiosAuthenticationTokenManager instead of being
spread out in UserProfileProvider.
- Increase test coverage.
> fix(core|react): handle guest users expired in authentication provider

- packages/client/src/helpers/client/interceptors/authentication/AuthenticationConfigOptions.js
- packages/client/src/helpers/client/interceptors/authentication/AxiosAuthenticationTokenManager.js
- packages/client/src/helpers/client/interceptors/authentication/__tests__/AxiosAuthenticationTokenManager.test.js
- packages/client/src/helpers/client/interceptors/authentication/errors.js
- packages/client/src/helpers/client/interceptors/authentication/token-providers/GuestTokenProvider.js
- packages/client/src/helpers/client/interceptors/authentication/token-providers/TokenProvider.js
- packages/client/src/helpers/client/interceptors/authentication/token-providers/UserTokenProvider.js
- packages/client/src/helpers/client/interceptors/authentication/token-providers/__tests__/GuestTokenProvider.test.js
- packages/client/src/helpers/client/interceptors/authentication/token-providers/__tests__/TokenData.test.js
- packages/client/src/helpers/client/interceptors/authentication/token-providers/__tests__/TokenProvider.test.js
- packages/react/src/authentication/contexts/UserProfileProvider.js
- packages/react/src/authentication/hooks/__tests__/useAuthentication.test.js
- packages/react/src/authentication/hooks/__tests__/useUserProfile.test.js
- packages/react/src/authentication/hooks/useUserAuthState.js
- Fixes the bug that happens when the guest user has expired
but the authentication provider continues to use the expired
guest user id when obtaining new guest tokens.
- Fixes a bug that the get access token promise was not
being set to null when the request to get access token fails
in both GuestTokenProvider and UserTokenProvider.
- Refactored the logic to change current token provider to live
inside AxiosAuthenticationTokenManager instead of being
spread out in UserProfileProvider.
- Increase test coverage.
> fix(core|react): handle guest users expired in authentication provider - next

- packages/redux/src/products/selectors/__tests__/details.test.ts
- packages/redux/src/products/selectors/details.ts
- tests/__fixtures__/products/state.fixtures.ts
This creates a selector that returns all product sizes with an updated remaining quantity,
calculated according to the items already in bag.
> feat: add selector to get all product sizes with remaining quantity

- packages/core/src/bags/hooks/useBagItem.js
- packages/core/src/bags/redux/utils/__tests__/createBagItemHash.test.js
- packages/react/src/bags/hooks/useBagItem.js
- tests/__fixtures__/bags/bagItem.fixtures.js
This fixes the incorrect access to the id property of `productAggregator`, which may be null.
> fix(core|react): allow `useBagItem`'s to work without `productAggregator`

- package.json
- scripts/yalc-publish.sh
- scripts/yalc-push.sh
Add just two scripts to publish and push, instead of having multiple scripts for each package.
Each script could receive the package folder name as an argument to publish/push only the selected package.
Bash is needed to run the script.
None.
> chore: refactor yalc scripts

- packages/client/src/promotionEvaluations/__fixtures__/getPromotionEvaluationItems.fixtures.ts
- packages/client/src/promotionEvaluations/__tests__/__snapshots__/getPromotionEvaluationItems.test.ts.snap
- packages/client/src/promotionEvaluations/__tests__/getPromotionEvaluationItems.test.ts
- packages/client/src/promotionEvaluations/getPromotionEvaluationItems.ts
- packages/client/src/promotionEvaluations/index.ts
- packages/client/src/promotionEvaluations/types/getPromotionEvaluationItems.types.ts
- packages/client/src/promotionEvaluations/types/index.ts
- packages/client/src/promotionEvaluations/types/promotionEvaluationItems.types.ts
- packages/redux/src/promotionEvaluations/__tests__/reducer.test.ts
- packages/redux/src/promotionEvaluations/__tests__/selectors.test.ts
- packages/redux/src/promotionEvaluations/actionTypes.ts
- packages/redux/src/promotionEvaluations/actions/__tests__/fetchPromotionEvaluationItems.test.ts
- packages/redux/src/promotionEvaluations/actions/factories/fetchPromotionEvaluationItemsFactory.ts
- packages/redux/src/promotionEvaluations/actions/factories/index.ts
- packages/redux/src/promotionEvaluations/actions/fetchPromotionEvaluationItems.ts
- packages/redux/src/promotionEvaluations/actions/index.ts
- packages/redux/src/promotionEvaluations/index.ts
- packages/redux/src/promotionEvaluations/reducer.ts
- packages/redux/src/promotionEvaluations/selectors.ts
- packages/redux/src/promotionEvaluations/types/action.types.ts
- packages/redux/src/promotionEvaluations/types/index.ts
- packages/redux/src/promotionEvaluations/types/state.types.ts
- packages/redux/src/types/StoreState.types.ts
- tests/__fixtures__/promotionEvaluations/index.ts
- tests/__fixtures__/promotionEvaluations/promotionEvaluations.fixtures.ts
This adds the client and redux for the `promotionEvaluations` endpoint.
None.
> feat(client|redux): add `promotionEvaluations` endpoint

- packages/react/src/analytics/integrations/GA4/validation/eventSchemas.js
- packages/react/src/analytics/integrations/shared/validation/eventSchemas.js
This PR fixes a bug on the validation of the promocode_applied for the GA4 integration.
> fix: fix ga4 promocode_applied event schema

- packages/redux/src/products/reducer/__tests__/details.test.ts
- packages/redux/src/products/reducer/details.ts
- packages/redux/src/products/serverInitialState/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/products/serverInitialState/__tests__/__snapshots__/products.test.ts.snap
- packages/redux/src/products/serverInitialState/products.ts
- packages/redux/src/products/types/state.types.ts
- tests/__fixtures__/products/state.fixtures.ts
This removes the `id` property from the `products.details` reducer since we fetch a lot of products and keeping the id of the last one fetched doesn’t look useful.
None.
> chore(redux): remove `id` property from `products.details` reducer

- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.js.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.js
This adds the missing `from` parameter to the mapping
for PRODUCT_CLICKED event in GA4.
None.
> fix(react): add from to PRODUCT_CLICKED event mapping in GA4 - next

- packages/redux/src/recentlyViewed/actions/factories/fetchRecentlyViewedProductsFactory.js
This just removes a circular dependency from `fetchRecentlyViewedProductsFactory`.
> fix(redux): remove circular dependency from recently viewed

- packages/react/src/analytics/integrations/GA4/eventMapping.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
This adds the missing `from` parameter to the mapping
for PRODUCT_CLICKED event in GA4.
> fix(react): add `from` to PRODUCT_CLICKED event mapping in GA4

- .github/semantic.yml
- .github/workflows/PullRequestLabeler.yml
- This adds another job to the PullRequestLabeler workflow that adds a type
label to the PR automatically by checking the title of the PR if it uses the conventional
commits standard.
- This also adds a semantic.yml configuration file to configure the
github app "Semantic Pull Requests" to check if all commits of a PR
contain a title that follows the conventional commits standard.
None
- [] Tests for the respective changes have been added
> chore: improvements to workflows

- packages/redux/src/loyalty/actions/__tests__/createProgramMembership.test.js
- packages/redux/src/loyalty/actions/__tests__/createProgramMembershipConvert.test.js
- packages/redux/src/loyalty/actions/__tests__/createProgramMembershipReplacement.test.js
- packages/redux/src/loyalty/actions/__tests__/fetchProgramMembershipStatements.test.js
- packages/redux/src/loyalty/actions/__tests__/fetchProgramUsersMembership.test.js
- packages/redux/src/loyalty/actions/__tests__/fetchPrograms.test.js
- packages/redux/src/loyalty/actions/createProgramMembership.js
- packages/redux/src/loyalty/actions/createProgramMembershipConvert.js
- packages/redux/src/loyalty/actions/createProgramMembershipReplacement.js
- packages/redux/src/loyalty/actions/factories/createProgramMembershipConvertFactory.js
- packages/redux/src/loyalty/actions/factories/createProgramMembershipFactory.js
- packages/redux/src/loyalty/actions/factories/createProgramMembershipReplacementFactory.js
- packages/redux/src/loyalty/actions/factories/fetchProgramMembershipStatementsFactory.js
- packages/redux/src/loyalty/actions/factories/fetchProgramUsersMembershipFactory.js
- packages/redux/src/loyalty/actions/factories/fetchProgramsFactory.js
- packages/redux/src/loyalty/actions/factories/index.js
- packages/redux/src/loyalty/actions/fetchProgramMembershipStatements.js
- packages/redux/src/loyalty/actions/fetchProgramUsersMembership.js
- packages/redux/src/loyalty/actions/fetchPrograms.js
This creates the factories for the `loyalty` actions, and provides the respective actions with the client embedded.
BREAKING CHANGE
- The action creators `createProgramMembership`, `createProgramMembershipConvert`, 
`createProgramMembershipReplacement`, `fetchProgramMembershipStatements`, `fetchPrograms`
`fetchProgramUsersMembership`,  were renamed and now come pre-configured with the 
corresponding client from @blackout-client, so you do not need to configure 
these action creators anymore if you use the default @blackout-client client provided.
```js
// Previously
import {
fetchPrograms,
createProgramMembership,
createProgramMembershipReplacement,
createProgramMembershipConvert,
fetchProgramMembershipStatements,
fetchProgramUsersMembership,
} from '@blackout-redux/loyalty';
import { …
```
> feat(redux): provide loyalty actions with a client

- packages/react/src/bags/hooks/__tests__/useBag.test.tsx
- packages/react/src/bags/hooks/types/useBag.ts
- packages/react/src/bags/hooks/useBag.ts
- packages/redux/src/bags/actions/fetchBag.ts
This fixes some types on the useBag hook. It also changes some of its returned values, such as `isEmpty` instead of `hasItems` and `id` instead of `bagId`.
None.
> fix: `useBag` hook types

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- packages/core/src/returns/client/__fixtures__/getPickupCapabilities.fixtures.js
- packages/core/src/returns/client/__fixtures__/getReferences.fixtures.js
- packages/core/src/returns/client/__fixtures__/getReturn.fixtures.js
- packages/core/src/returns/client/__fixtures__/patchReturn.fixtures.js
- packages/core/src/returns/client/__fixtures__/postReturn.fixtures.js
- packages/core/src/returns/client/__tests__/__snapshots__/getPickupCapabilities.test.js.snap
- packages/core/src/returns/client/__tests__/getPickupCapabilities.test.js
- packages/core/src/returns/client/__tests__/getReferences.test.js
- packages/core/src/returns/client/__tests__/getReturn.test.js
- packages/core/src/returns/client/__tests__/patchReturn.test.js
- packages/core/src/returns/client/__tests__/postReturn.test.js
- packages/core/src/returns/client/getPickupCapabilities.js
- packages/core/src/returns/client/getReferences.js
- packages/core/src/returns/client/getReturn.js
- packages/core/src/returns/client/patchReturn.js
- packages/core/src/returns/client/postReturn.js
- packages/core/src/returns/redux/actions/__tests__/doGetPickupCapabilities.test.js
- packages/core/src/returns/redux/actions/doGetPickupCapabilities.js
- Implement new return endpoints. Changed from /legacy/v1/returns to /account/v1/returns
- Changed pickupCapabilities endpoint. No longer needs a query, only needs the pickupDay in the format YYYY-MM-DD
> feat(core): implement new return endpoints

- packages/redux/src/entities/__tests__/__snapshots__/reducer.test.js.snap
- packages/redux/src/returns/__tests__/reducer.test.js
- packages/redux/src/returns/reducer.js
This resets the returns data (state and entities) when the user proceeds with a logout action.
> feat(redux): reset returns data on logout

- configs/typescript/tsconfig.basic.json
- configs/typescript/tsconfig.package-build.json
- jest.config.js
- package.json
- packages/analytics/tsconfig.build.json
- packages/analytics/tsconfig.json
- packages/client/tsconfig.build.json
- packages/client/tsconfig.json
- packages/react/tsconfig.build.json
- packages/react/tsconfig.json
- packages/redux/src/analytics/middlewares/__tests__/bag.test.js
- packages/redux/src/analytics/middlewares/__tests__/wishlist.test.js
- packages/redux/src/forms/actions/__tests__/fetchFormSchema.test.ts
- packages/redux/src/forms/actions/__tests__/resetFormSchema.test.ts
- packages/redux/src/forms/actions/__tests__/submitFormData.test.ts
- packages/redux/src/recentlyViewed/actions/__tests__/fetchRecentlyViewedProducts.test.js
- packages/redux/src/recentlyViewed/actions/__tests__/removeRecentlyViewedProduct.test.js
- packages/redux/src/recentlyViewed/actions/__tests__/saveRecentlyViewedProduct.test.js
- packages/redux/src/recommendations/__tests__/reducer.test.js
- packages/redux/src/recommendations/__tests__/selectors.test.js
- packages/redux/src/recommendations/actions/__tests__/fetchProductRecommendations.test.js
- packages/redux/src/subscriptions/actions/__tests__/clearAllUnsubscribeRecipientFromTopicRequests.test.js
- packages/redux/src/subscriptions/actions/__tests__/clearUnsubscribeRecipientFromTopicRequest.test.js
- packages/redux/src/subscriptions/actions/__tests__/fetchSubscriptionPackages.test.js
- packages/redux/src/subscriptions/actions/__tests__/fetchUserSubscriptions.test.js
- packages/redux/src/subscriptions/actions/__tests__/resetSubscriptions.test.js
- packages/redux/src/subscriptions/actions/__tests__/updateUserSubscriptions.test.js
- packages/redux/src/subscriptions/reducer/__tests__/index.test.js
- packages/redux/tsconfig.build.json
- packages/redux/tsconfig.json
- This adds support for using typescript in test files
while keeping the tests from transpiling when using yarn types command.
- Removed 'redux/tests' alias to be consistent with the other packages.
> chore: add support for typescript in test files

- packages/client/src/wishlists/types/wishlistSet.types.ts
- packages/react/src/wishlists/hooks/__tests__/useWishlistSets.test.tsx
- packages/react/src/wishlists/hooks/index.ts
- packages/react/src/wishlists/hooks/types/index.ts
- packages/react/src/wishlists/hooks/types/useWishlistSets.ts
- packages/react/src/wishlists/hooks/useWishlistSets.ts
- packages/redux/src/contents/actions/__tests__/fetchCommercePages.test.ts
- packages/redux/src/wishlists/selectors/types/index.ts
- packages/redux/src/wishlists/selectors/types/wishlistsSets.types.ts
- packages/redux/src/wishlists/selectors/wishlistsSets.ts
This adds a `useWishlistSets` hook that aggregates all relevant logic to use on wishlist sets.
> feat: add `useWishlistSets` hook

- packages/core/src/products/listing/redux/__tests__/__snapshots__/serverInitialState.test.js.snap
- packages/core/src/products/listing/redux/__tests__/serverInitialState.test.js
- packages/core/src/products/listing/redux/serverInitialState.js
- tests/__fixtures__/products/listing.fixtures.js
This adds the missing `id` property to the listing server initial state, letting it pass through.
> fix(core): add `id` to the listing server initial state

- packages/react/src/wishlists/hooks/__tests__/useWishlist.test.tsx
- packages/react/src/wishlists/hooks/types/useWishlist.ts
- packages/react/src/wishlists/hooks/useWishlist.ts
This adds the `addWishlistItem` method, responsible for adding an item to the wishlist, to the
`useWishlist` hook.
> feat: add `addWishlistItem` to `useWishlist` hook

- packages/client/src/products/types/set.types.ts
- packages/redux/src/products/serverInitialState/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/products/serverInitialState/__tests__/__snapshots__/lists.test.ts.snap
- packages/redux/src/products/serverInitialState/index.ts
- packages/redux/src/products/serverInitialState/lists.ts
- packages/redux/src/products/serverInitialState/products.ts
- packages/redux/src/products/serverInitialState/types/index.ts
- packages/redux/src/products/serverInitialState/types/lists.types.ts
- packages/redux/src/products/serverInitialState/types/products.types.ts
- packages/redux/src/types/Model.types.ts
- tests/__fixtures__/products/details.fixtures.ts
- tests/__fixtures__/products/productsLists.fixtures.ts
This adds the missing `id` property to the lists server initial state, letting it pass through.
This also separates the products' `serverInitialState` types for the sake of readability.
> fix(redux): add `id` to the lists server initial state

- packages/analytics/tsconfig.build.json
- packages/analytics/tsconfig.json
- packages/client/tsconfig.build.json
- packages/client/tsconfig.json
- packages/react/tsconfig.json
- packages/redux/tsconfig.json
This removes the `rootDir` property from the `tsconfig` for TS to recognize
eventual files imported from other blackout packages, thus avoiding the
`'rootDir' is expected to contain all source files` error.
This also fixes the `paths` to use the packages folders we're working on,
instead of the node_modules.
> chore: remove `rootDir` from `tsconfig` and fix the `paths`

- .github/workflows/CI.yml
This prevents the CI action to run on draft pull requests.
> chore: prevent CI action to run on draft pull requests

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/GA4/constants.js
- packages/react/src/analytics/integrations/GA4/validation/optionsValidator.js
- This adds a boolean option `setCustomUserIdProperty` to GA4 that
when set to `true`, will set a custom user property called `crm_id`
containing the same value as the `user_id` property. This is because
the `user_id` property cannot be used in reports and explorations
in GA4, so the suggested workaround is to set a new user property
containing the same value.
> feat(react): add custom user id property option

- packages/redux/src/loyalty/__tests__/reducer.test.ts
- packages/redux/src/loyalty/reducer.ts
- Implemeted action to reset loyalty data on logout
> feat(redux): reset loyalty data on logout

- packages/react/src/checkout/hooks/useCheckout.ts
- This adds a boolean param `isSameAsBilling` to the useCheckout hook function `handleSetShippingAddress` to support update the shipping and billing address in the same request (`updateCheckout`)
> feat(react): update billing support on handleSetShippingAddress

- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.js.snap
- packages/react/src/analytics/integrations/GA4/commands.js
- packages/react/src/analytics/integrations/GA4/validation/eventSchemas.js
- tests/__fixtures__/analytics/track/productUpdatedTrackData.fixtures.ts
- Allowing trigger ga4's change size event on the first selection of size.
- This permit tracking change_size event, when old selected value is undefined.
> feat(react): add ga4 change size event on first selection next

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.js.snap
- Added new parameter of path_clean in view_page payload event, with current location url, without query string.
None.
> feat(react): add parameter path_clean on GA4 view_page event for next

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
- Added new parameter of path_clean in view_page payload event, with current location url, without query string.
None.
> feat(react): add parameter path_clean on GA4 view_page event

- packages/redux/src/entities/schemas/content.ts
- tests/__fixtures__/contents/contents.ts
Fix multiple entries that have the same hash on content searchResults
- fix contentEntries schema normalizr to entries identifier be publicationId instead of hash
None.
> fix(redux): multiple entries generates same hash contents

- packages/react/src/wishlists/hooks/__tests__/useWishlistItem.test.tsx
- packages/react/src/wishlists/hooks/index.ts
- packages/react/src/wishlists/hooks/types/index.ts
- packages/react/src/wishlists/hooks/types/useWishlistItem.ts
- packages/react/src/wishlists/hooks/useWishlistItem.ts
- packages/redux/src/wishlists/selectors/wishlists.ts
This adds the hook `useWishlistItem` that manages all logic related with
a wishlist item.
> feat(react|redux): add `useWishlistItem` hook

- packages/react/src/products/hooks/__tests__/useProductsList.test.tsx
- packages/react/src/products/hooks/index.ts
- packages/react/src/products/hooks/types/index.ts
- packages/react/src/products/hooks/types/useProductsList.ts
- packages/react/src/products/hooks/useProductsList.ts
- tests/__fixtures__/products/productsLists.fixtures.ts
This adds the `useProductsList` hook, with selectors and logic useful
in products lists.
> feat(react): add `useProductsList` hook

- packages/client/src/staffMembers/__fixtures__/getStaffMember.fixtures.ts
- packages/client/src/staffMembers/__tests__/__snapshots__/getStaffMember.test.ts.snap
- packages/client/src/staffMembers/__tests__/getStaffMember.test.ts
This replaces the usage of the `moxios` library with `msw` in the unit tests of the `staffMembers`
chunk.
Refs #18 
> chore(client): replace `moxios` with `msw` in `staffMembers`

- packages/client/src/brands/__fixtures__/getBrand.fixtures.ts
- packages/client/src/brands/__fixtures__/getBrands.fixtures.ts
- packages/client/src/brands/__tests__/__snapshots__/getBrand.test.ts.snap
- packages/client/src/brands/__tests__/__snapshots__/getBrands.test.ts.snap
- packages/client/src/brands/__tests__/getBrand.test.ts
- packages/client/src/brands/__tests__/getBrands.test.ts
This replaces the usage of the `moxios` library with `msw` in the unit tests of the `brands`
chunk.
Refs #18 
> chore(client): replace moxios with msw in brands

- packages/client/src/sizeGuides/__fixtures__/getSizeGuides.fixtures.ts
- packages/client/src/sizeGuides/__tests__/__snapshots__/getSizeGuides.test.ts.snap
- packages/client/src/sizeGuides/__tests__/getSizeGuides.test.ts
- packages/client/src/sizeScales/__fixtures__/getSizeScale.fixtures.ts
- packages/client/src/sizeScales/__fixtures__/getSizeScaleMappings.fixtures.ts
- packages/client/src/sizeScales/__fixtures__/getSizeScales.fixtures.ts
- packages/client/src/sizeScales/__tests__/__snapshots__/getSizeScale.test.ts.snap
- packages/client/src/sizeScales/__tests__/__snapshots__/getSizeScaleMappings.test.ts.snap
- packages/client/src/sizeScales/__tests__/__snapshots__/getSizeScales.test.ts.snap
- packages/client/src/sizeScales/__tests__/getSizeScale.test.ts
- packages/client/src/sizeScales/__tests__/getSizeScaleMappings.test.ts
- packages/client/src/sizeScales/__tests__/getSizeScales.test.ts
This replaces the usage of the `moxios` library with `msw` in the unit tests of the `sizeScales` and `sizeGuides`
chunks.
Refs #18 
> chore(client): replace moxios with msw in size scales and size guides

- packages/client/src/categories/__fixtures__/getCategories.fixtures.ts
- packages/client/src/categories/__fixtures__/getTopCategories.fixtures.ts
- packages/client/src/categories/__tests__/__snapshots__/getCategories.test.ts.snap
- packages/client/src/categories/__tests__/__snapshots__/getTopCategories.test.ts.snap
- packages/client/src/categories/__tests__/getCategories.test.ts
- packages/client/src/categories/__tests__/getTopCategories.test.ts
- packages/client/src/designers/__fixtures__/getDesigners.fixtures.ts
- packages/client/src/designers/__tests__/__snapshots__/getDesigners.test.ts.snap
- packages/client/src/designers/__tests__/getDesigners.test.ts
This replaces the usage of the `moxios` library with `msw` in the unit tests of the `categories` and `designers`
chunks.
Refs #18 
> chore(client): replace moxios with msw in categories and designers

- packages/client/src/promotionEvaluations/__fixtures__/getPromotionEvaluationItems.fixtures.ts
- packages/client/src/promotionEvaluations/__tests__/__snapshots__/getPromotionEvaluationItems.test.ts.snap
- packages/client/src/promotionEvaluations/__tests__/getPromotionEvaluationItems.test.ts
- packages/client/src/search/__fixtures__/getSearchDidYouMean.fixtures.ts
- packages/client/src/search/__fixtures__/getSearchIntents.fixtures.ts
- packages/client/src/search/__fixtures__/getSearchSuggestions.fixtures.ts
- packages/client/src/search/__tests__/__snapshots__/getSearchDidYouMean.test.ts.snap
- packages/client/src/search/__tests__/__snapshots__/getSearchIntents.test.ts.snap
- packages/client/src/search/__tests__/__snapshots__/getSearchSuggestions.test.ts.snap
- packages/client/src/search/__tests__/getSearchDidYouMean.test.ts
- packages/client/src/search/__tests__/getSearchIntents.test.ts
- packages/client/src/search/__tests__/getSearchSuggestions.test.ts
This replaces the usage of the `moxios` library with `msw` in the unit tests of the `search` and `promotionEvaluations`
chunks.
Refs #18 
> chore(client): replace moxios with msw in search and promotion evaluations

- packages/client/src/wishlists/__fixtures__/deleteWishlistItem.fixtures.ts
- packages/client/src/wishlists/__fixtures__/deleteWishlistSet.fixtures.ts
- packages/client/src/wishlists/__fixtures__/getWishlist.fixtures.ts
- packages/client/src/wishlists/__fixtures__/getWishlistSet.fixtures.ts
- packages/client/src/wishlists/__fixtures__/getWishlistSets.fixtures.ts
- packages/client/src/wishlists/__fixtures__/patchWishlistItem.fixtures.ts
- packages/client/src/wishlists/__fixtures__/patchWishlistSet.fixtures.ts
- packages/client/src/wishlists/__fixtures__/postWishlistItem.fixtures.ts
- packages/client/src/wishlists/__fixtures__/postWishlistSet.fixtures.ts
- packages/client/src/wishlists/__tests__/__snapshots__/deleteWishlistItem.test.ts.snap
- packages/client/src/wishlists/__tests__/__snapshots__/deleteWishlistSet.test.ts.snap
- packages/client/src/wishlists/__tests__/__snapshots__/getWishlist.test.ts.snap
- packages/client/src/wishlists/__tests__/__snapshots__/getWishlistSet.test.ts.snap
- packages/client/src/wishlists/__tests__/__snapshots__/getWishlistSets.test.ts.snap
- packages/client/src/wishlists/__tests__/__snapshots__/patchWishlistItem.test.ts.snap
- packages/client/src/wishlists/__tests__/__snapshots__/patchWishlistSet.test.ts.snap
- packages/client/src/wishlists/__tests__/__snapshots__/postWishlistItem.test.ts.snap
- packages/client/src/wishlists/__tests__/__snapshots__/postWishlistSet.test.ts.snap
- packages/client/src/wishlists/__tests__/deleteWishlistItem.test.ts
- packages/client/src/wishlists/__tests__/deleteWishlistSet.test.ts
- packages/client/src/wishlists/__tests__/getWishlist.test.ts
- packages/client/src/wishlists/__tests__/getWishlistSet.test.ts
- packages/client/src/wishlists/__tests__/getWishlistSets.test.ts
- packages/client/src/wishlists/__tests__/patchWishlistItem.test.ts
- packages/client/src/wishlists/__tests__/patchWishlistSet.test.ts
- packages/client/src/wishlists/__tests__/postWishlistItem.test.ts
- packages/client/src/wishlists/__tests__/postWishlistSet.test.ts
This replaces the `moxios` package with `msw` in the fixtures and tests related with wishlists.
Refs #18 
> chore(client): replace `moxios` with `msw` in wishlists

- packages/redux/src/wishlists/actions/factories/fetchWishlistSetFactory.ts
The fetchWishlistSetFactory method was not throwing an error when
the wishlistSetId was undefined.
This PR adds a new error throwing an error when there is
no wishlistSetId
> fix(redux): fix fetchWishlistSetFactory

- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/GA4/eventMapping.js
Previously, all product categories were being sent to GA4,
even if the categories were above the limit of 5.
This changes that logic to truncate the categories, if they exceed the limit
by getting the first category and the last 4 categories that were sent as
requested by Paul.
> fix(react): truncate categories if the categories sent are greater than limit (next)

- packages/react/src/analytics/integrations/GA4/eventMapping.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
Previously, all product categories were being sent to GA4, 
even if the categories were above the limit of 5.
This changes that logic to truncate the categories if they exceed the limit
by getting the first category and the last 4 categories that were sent as
requested by Paul.
> fix(react): truncate categories if the categories sent are greater than limit

- packages/react/src/wishlists/hooks/__tests__/useWishlistSet.test.tsx
- packages/react/src/wishlists/hooks/index.ts
- packages/react/src/wishlists/hooks/types/index.ts
- packages/react/src/wishlists/hooks/types/useWishlistSet.ts
- packages/react/src/wishlists/hooks/types/useWishlistSets.ts
- packages/react/src/wishlists/hooks/useWishlistSet.ts
- packages/redux/src/entities/types/wishlistSet.types.ts
- packages/redux/src/wishlists/selectors/types/wishlistsSets.types.ts
- packages/redux/src/wishlists/selectors/wishlistsSets.ts
This adds the hook `useWishlistSet` that manages all logic related with
a wishlist set.
> feat(react): add useWishlistSet hook

- packages/client/src/helpers/adapters/types/adaptCustomAttributes.types.ts
- packages/react/src/bags/hooks/__tests__/useAddOrUpdateBagItem.test.tsx
- packages/react/src/bags/hooks/__tests__/useBagItem.test.tsx
- packages/react/src/bags/hooks/index.ts
- packages/react/src/bags/hooks/types/index.ts
- packages/react/src/bags/hooks/types/useAddOrUpdateBagItem.ts
- packages/react/src/bags/hooks/types/useBagItem.ts
- packages/react/src/bags/hooks/useAddOrUpdateBagItem.ts
- packages/react/src/bags/hooks/useBagItem.ts
- packages/redux/src/entities/types/bagItem.types.ts
- tests/__fixtures__/bags/bagItem.fixtures.ts
- tests/__fixtures__/products/products.fixtures.ts
BREAKING CHANGE: This moves the method `handleAddOrUpdateItem` to a new hook `useAddOrUpdateBagItem`. The new hook is necessary since we are using selector and actions outside a React component.
To adapt this breaking change, we need to update all instances of:
```
const { handleAddOrUpdateItem } = useBagItem();
```
to
```
const handleAddOrUpdateItem = useAddOrUpdateBagItem();
```
Closes #16
It also changes the type of `customAttributes` to `unknown` because this is in fact an unknown value that depends on the implementation of each experience.
> feat(react): move `handleAddOrUpdateItem` method to new hook

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/GA4/commands.js
- packages/react/src/analytics/integrations/GA4/eventMapping.js
- packages/react/src/analytics/integrations/GA4/validation/eventSchemas.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
- This adds mappings for the GA4 custom scroll event. It maps the
`interact_content` event with `scroll` type
and whose `target` is the document.body element.
- Fixes `PRODUCT_UPDATED` event implementation that would not let the user to
specify an override for that event.
- Simplified implementation of the `commands` module in GA4 to avoid
redundancy.
> feat(react): add GA4 custom scroll event mappings

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.js.snap
- packages/react/src/analytics/integrations/GA4/commands.js
- packages/react/src/analytics/integrations/GA4/eventMapping.js
- packages/react/src/analytics/integrations/GA4/validation/eventSchemas.js
- This adds mappings for the GA4 custom scroll event. It maps the
`interact_content` event with scroll type
and whose target is the document.body element.
- Fixes `PRODUCT_UPDATED` event implementation that would not let the user to
specify an override for that event.
- Simplified implementation of the `commands` module in GA4 to avoid
redundancy.
> feat(react): add GA4 custom scroll event mappings (next)

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/GA4/commands.js
- packages/react/src/analytics/integrations/GA4/eventMapping.js
- Fixes interact content payload to exclude properties that are objects.
- Fixes unnecessary warnings being logged to the console for events that
are not handled by the default command mapper in GA4.
> fix(react): fix interact content payload in GA4 (next)

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/GA4/commands.js
- packages/react/src/analytics/integrations/GA4/eventMapping.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- Fixes interact content payload to exclude properties that are objects.
- Fixes unnecessary warnings being logged to the console for events that
are not handled by the default command mapper in GA4.
> fix(react): fix interact content payload in GA4

- packages/core/src/analytics/integrations/Omnitracking/Omnitracking.js
- packages/core/src/analytics/integrations/Omnitracking/__tests__/omnitracking-helper.test.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
Refactored the integration and combined two different mappers into one, so we can calculate parameters based on the event data object in a single point.
> feat(core): refactored mapper on omnitracking integration to calculate parameters from data object

- packages/analytics/src/integrations/Omnitracking/Omnitracking.js
- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.js
- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.js.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/omnitracking-helper.test.js
- packages/analytics/src/integrations/Omnitracking/definitions.js
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.js
Refactored the integration and combined two different mappers into one, so we can calculate parameters based on the event data object in a single point.
> feat(core): add new mapper on omnitracking integration to calculate parameters from data object - next

- packages/react/src/bags/hooks/useAddOrUpdateBagItem.ts
The `from` parameter in useAddOrUpdateBagItem hook was being destructured
but not being used elsewhere. That prevented the `from`
value from propagating to the dispatched action, which would prevent
its tracking in the analytics bag middleware.
> fix(blackout-react): fix `from` parameter in useAddOrUpdateBagItem hook

- packages/core/src/orders/redux/__tests__/selectors.test.js
- packages/core/src/orders/redux/reducer.js
- packages/core/src/orders/redux/selectors.js
This adds missing reducers and selectors for activities endpoints
None
> fix(redux): add missing reducers and selectors for activities endpoints

- packages/redux/src/orders/__tests__/selectors.test.ts
- packages/redux/src/orders/reducer.ts
- packages/redux/src/orders/selectors.ts
- packages/redux/src/orders/types/actions.types.ts
- packages/redux/src/orders/types/state.types.ts
- tests/__fixtures__/orders/orders.fixtures.ts
This adds missing reducers and selectors for activities endpoints on next
None
> fix(redux): add missing reducers and selectors for activities endpoint on next

- packages/core/src/contents/utils.js
- tests/__fixtures__/contents/commercePages.fixtures.js
A new method to centralize ranking method that gives a list of commerce pages ordered by their rankings, the best one on first.
On default strategy returns the first result of it and on merge, it uses the order of ranked pages to list components based on it.
Mock tests changed to reflect the actual components structure and the merge strategy
> feat(core): update order of components and fix ranking on merge strategy for commerce pages

- packages/redux/src/entities/schemas/facet.ts
This adds the `groupsOn` value to the facet entity id for sizes, which fixes a bug of
having wrong descriptions of sizes. Since each size facet can have different descriptions
according to what category it belongs to (hence the `groupsOn`, which has a category id as its
value), there is the need to add the `groupsOn` to turn the entity id unique, despite of the
facet id.
For example, the the entity `sizes_17` could have both the values `36` or `XS`,
depending on the listing the user is. This would result in a bug when navigating between cached
listings, where the previous value for a given entity was kept, displaying the wrong descriptions
(like keeping `XS` for shoes). With this change, the entity id is now `sizes_17_<groupsOn>`, just
like the "sizes by category" already does.
By sending …
> fix(core): add `groupsOn` to the sizes facet's entity id

- packages/redux/src/contents/actions/__tests__/__snapshots__/fetchCommercePages.test.ts.snap
- packages/redux/src/contents/utils.ts
- tests/__fixtures__/contents/commercePages.ts
A new method to centralize ranking method that gives a list of commerce pages ordered by their rankings, the best one on first.
On default strategy returns the first result of it and on merge, it uses the order of ranked pages to list components based on it.
Mock tests changed to reflect the actual components structure and the merge strategy
> feat(core): update order of components and fix ranking on merge strategy for commerce pages next

- .github/workflows/CreateRelease.yml
- .github/workflows/SendEmail.yml
- This adds create github release and send email workflows to the
project. The create github release workflow will create a github release
whenever a tag for a non-prerelease version is pushed. The body of the
release is composed of the last entry added to the changelog of the package
indicated by the tag. The send email workflow will send an email containing
the release notes of the release to the internal distribution list whenever a
release is published. Note that as lerna might apply several tags depending
on the released packages, it will generate as many emails as packages
that were released when there is a merge to `main` branch.
Closes #20  …
> chore: add create github release and send email workflows

- .github/workflows/CreateRelease.yml
- .github/workflows/SendEmail.yml
- This adds create github release and send email workflows to the
project. The create github release workflow will create a github release
whenever a tag for a non-prerelease version is pushed. The body of the
release is composed of the last entry added to the changelog of the package
indicated by the tag. The send email workflow will send an email containing
the release notes of the release to the internal distribution list whenever a
release is published. Note that as lerna might apply several tags depending
on the released packages, it will generate as many emails as packages
that were released when there is a merge to `main` branch.
Closes #20  …
> chore: add create github release and send email workflows next

- packages/core/src/checkout/client/__fixtures__/deleteOrderItem.fixtures.js
- packages/core/src/checkout/client/__fixtures__/patchOrderItem.fixtures.js
- packages/core/src/checkout/client/__tests__/__snapshots__/deleteOrderItem.test.js.snap
- packages/core/src/checkout/client/__tests__/__snapshots__/patchOrderItem.test.js.snap
- packages/core/src/checkout/client/__tests__/deleteOrderItem.test.js
- packages/core/src/checkout/client/__tests__/patchOrderItem.test.js
- packages/core/src/checkout/client/deleteOrderItem.js
- packages/core/src/checkout/client/index.js
- packages/core/src/checkout/client/patchOrderItem.js
- packages/core/src/checkout/redux/__fixtures__/checkoutSelector.fixtures.js
- packages/core/src/checkout/redux/__tests__/reducer.test.js
- packages/core/src/checkout/redux/__tests__/selectors.test.js
- packages/core/src/checkout/redux/actionTypes.js
- packages/core/src/checkout/redux/actions/__tests__/__snapshots__/doDeleteOrderItem.test.js.snap
- packages/core/src/checkout/redux/actions/__tests__/__snapshots__/doUpdateOrderItem.test.js.snap
- packages/core/src/checkout/redux/actions/__tests__/doDeleteOrderItem.test.js
- packages/core/src/checkout/redux/actions/__tests__/doUpdateOrderItem.test.js
- packages/core/src/checkout/redux/actions/doDeleteOrderItem.js
- packages/core/src/checkout/redux/actions/doUpdateOrderItem.js
- packages/core/src/checkout/redux/actions/index.js
- packages/core/src/checkout/redux/reducer.js
- packages/core/src/checkout/redux/selectors.js
We have added 2 new endpoints for order items:
- Update order item (to update the quantity of the item in the checkout order)
- Delete order item (to delete an item from the checkout order)
None.
> feat(core): add update and delete order item endpoints

- .github/workflows/CI.yml
- This changes lerna publish message to replace [skip ci]
with [skip build] in order to allow the create github release workflow
to run. Also, a condition was added to abort any runs for commits that contain
[skip build] message.
> chore: change lerna publish message

- .github/workflows/CI.yml
- This changes lerna publish message to replace [skip ci]
with [skip build] in order to allow the create github release workflow
to run. Also, a condition was added to abort any runs for commits that contain
[skip build] message.
> chore: change lerna publish message next

- packages/redux/src/products/selectors/lists.ts
This adds an explanation for as to why the value of the discount field should be a string, instead of the suggested to-do message.
None.
> chore: add new comment for selector on products lists

- packages/react/src/content/hooks/useCommercePage.js
- created because this PR was closed https://github.com/Farfetch/blackout/pull/221
- Memoized queryCommerce and queryContent constants to improve performance.
- Improved fetchCommerce callback with queryCommerce validation.
None.
> chore(react): memoize queryCommerce and queryContent and improve fetchCommerce callback

- packages/core/src/contents/__tests__/utils.test.js
- packages/core/src/contents/utils.js
When commerce page metadata custom is a string, warn the developer to republish content.
> fix(core): implement fallback commerce page metadata string

- packages/core/src/subscriptions/client/__tests__/putSubscriptions.test.js
- packages/core/src/subscriptions/client/putSubscriptions.js
- packages/core/src/subscriptions/redux/__fixtures__/storeSubscriptionsState.fixtures.js
- packages/core/src/subscriptions/redux/__tests__/selectors.test.js
- packages/core/src/subscriptions/redux/actions/__tests__/doUpdateUserSubscriptions.test.js
- packages/core/src/subscriptions/redux/actions/doUpdateUserSubscriptions.js
- packages/core/src/subscriptions/redux/reducer/__tests__/user.test.js
- packages/core/src/subscriptions/redux/reducer/user.js
- packages/core/src/subscriptions/redux/selectors.js
This fixes the `doUpdateUserSubscriptions` action in order to reflect
the change made by the backend that changed the result of the put method
used by the action to not return the new subscriptions data and
instead requiring that a new get user subscriptions request be
performed to retrieve the updated data.
Additionally a new state for the error message of the
doGetUpdateUserSubscriptions action was added in order to allow the
consumer to differentiate the case when there was an error updating the
subscriptions and present a different error message.
To provide backwards compatibility, the previous `error` state was
maintained as well. …
> fix(blackout-core): fix doUpdateUserSubscriptions action

- packages/react/src/contents/hooks/useContentType.ts
- packages/react/src/contents/types/params.types.ts
Include new params in hook useContentType such as preview, to preview content
Include new params in hook useContentType such as preview, to be able to preview content
None
> feat(react): include new params hook useContentType next

- packages/redux/src/analytics/middlewares/wishlist.js
- This fixes the `getWishlistItemIdFromAction` from the analytics wishlist
middleware which was not considering the optional parameters when searching for
the updated wishlistItem in the action payload, which would prevent from
obtaining the correct item.
> fix(blackout-core): fix `getWishlistItemIdFromAction` function next

- packages/core/src/analytics/redux/middlewares/wishlist.js
- This fixes the `getWishlistItemIdFromAction` from the analytics wishlist
middleware which was not considering the optional parameters when searching for
the updated wishlistItem in the action payload, which would prevent from
obtaining the correct item.
> fix(blackout-core): fix `getWishlistItemIdFromAction` function

- packages/react/src/analytics/integrations/GA/GA.ts
- packages/react/src/analytics/integrations/GA/__tests__/GA.test.ts
- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.js
- This fixes a problem where tracked events that were
unhandled by GA/GA4 were still being considered for the
`onPreProcessCommand` optional function call. This presented a problem
because the generated command list was an empty array, which would break
the expectation of the consumers.
- Added corresponding tests.
> fix(blackout-react): ignore unhandled events in ga/ga4

- packages/client/src/helpers/client/interceptors/authentication/AxiosAuthenticationTokenManager.js
- packages/react/src/authentication/hooks/__tests__/useAuthentication.test.tsx
- This fixes a bug with logout interceptor where the `code` property
was being looked at the incorrect path when the logout request fails,
which prevented the logout of an user when the token does not exist.
> fix(blackout-client): fix logout in axios interceptor

- packages/client/src/subscriptions/__fixtures__/putSubscriptions.fixtures.ts
- packages/client/src/subscriptions/__tests__/putSubscriptions.test.ts
- packages/client/src/subscriptions/deleteRecipientFromTopic.ts
- packages/client/src/subscriptions/deleteSubscription.ts
- packages/client/src/subscriptions/getSubscriptionPackages.ts
- packages/client/src/subscriptions/getSubscriptions.ts
- packages/client/src/subscriptions/index.ts
- packages/client/src/subscriptions/putSubscriptions.ts
- packages/client/src/subscriptions/types/putSubscriptions.types.ts
- packages/redux/src/entities/selectors/__tests__/entity.test.ts
- packages/redux/src/entities/selectors/entity.ts
- packages/redux/src/subscriptions/__tests__/selectors.test.ts
- packages/redux/src/subscriptions/actions/__tests__/__snapshots__/updateUserSubscriptions.test.ts.snap
- packages/redux/src/subscriptions/actions/__tests__/updateUserSubscriptions.test.ts
- packages/redux/src/subscriptions/actions/factories/updateUserSubscriptionsFactory.ts
- packages/redux/src/subscriptions/reducer/__tests__/user.test.ts
- packages/redux/src/subscriptions/reducer/user.ts
- packages/redux/src/subscriptions/selectors.ts
- packages/redux/src/subscriptions/types/action.types.ts
- packages/redux/src/subscriptions/types/state.types.ts
- packages/redux/src/wishlists/selectors/wishlists.ts
- tests/__fixtures__/subscriptions/state.fixtures.ts
- tests/__fixtures__/subscriptions/subscriptions.fixtures.ts
- This fixes the `updateUserSubscriptions` action in order to reflect
the change made by the backend that changed the result of the put method
used by the action to not return the new subscriptions data and
instead requiring that a new get user subscriptions request be
performed to retrieve the updated data.
Additionally a breaking change was added with the
`getUserSubscriptionsError` selector that will not return an error when
the error was from the update subscriptions action.
To get the update error, a new selector was introduced.
This was in order to better differentiate which kind of error occurred
with the subscriptions state and enable the developer
to show alternative UIs in that case.
- Some fixes in typescript typings for `entities` and `subscriptions` slices. …
> fix(blackout-client|blackout-redux): fix updateUserSubscriptions action

- packages/core/src/helpers/client/interceptors/authentication/AxiosAuthenticationTokenManager.js
- packages/react/src/authentication/hooks/__tests__/useAuthentication.test.js
- This fixes a bug with logout interceptor where the `code` property
was being looked at the incorrect path when the logout request fails,
which prevented the logout of an user when the token does not exist.
> fix(blackout-core): fix logout in axios interceptor

- packages/react/src/analytics/integrations/Vitorino/Vitorino.js
- packages/react/src/analytics/integrations/Vitorino/__tests__/Vitorino.test.js
This PR exposes the network option of Vitorino integration, so we can use it on specific applications that need other endpoints as the marketing proxy.
> feat(react): expose Vitorino network option

- packages/react/src/analytics/integrations/GA4/validation/eventSchemas.js
- Remove wrong import and place missing schema on internal ga4 validation schemas.
None.
> fix(blackout-react): fix missing ga4 sort option schema

- packages/react/src/analytics/integrations/GA4/eventMapping.js
- packages/react/src/analytics/integrations/GA4/validation/eventSchemas.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
- adds support for multiple gender on ga4 signup newsletter track.
- change ga4 search event, to use property searchQuery instead of seachTerm.
None.
> feat(blackout-react): add support multigender ga4's signup newsletter

- packages/react/src/search/hooks/__tests__/useSearchSuggestions.test.tsx
- packages/react/src/search/hooks/types/index.ts
- packages/react/src/search/hooks/types/useSearchSuggestions.types.ts
- packages/react/src/search/hooks/useSearchSuggestions.ts
- tests/__fixtures__/search/searchSuggestions.fixtures.ts
This adds the `useSearchSuggestions` hook to the react package to facilitate
the use of selectors and actions for search suggestions.
None.
> feat: add `useSearchSuggestions` hook

- packages/react/src/analytics/integrations/Castle/CastleV2.js
- packages/react/src/analytics/integrations/__tests__/CastleV2.test.js
This PR fixes an edge case where the backend does not send a createdDate on the user info.
In this case, Castle does not accept the default date that was being calculated: `new Date(0).toISOString()`.
Now we're going to send `undefined` for these cases.
> fix(blackout-react): remove Castle's default Date when no valid 'createdDate' is passed

- packages/react/src/search/hooks/useSearchIntents.js
This fixes the problem of spreading the `searchIntents.resources` when they are `null`,
which resulted in an error. It now only spreads if there are resources, otherwise, an
empty array is used instead.
> fix: only use the `resources` to build the `searchRedirectUrl` if they exist

- packages/core/src/returns/client/__fixtures__/getPickupCapabilities.fixtures.js
- packages/core/src/returns/client/__tests__/getPickupCapabilities.test.js
- packages/core/src/returns/client/getPickupCapabilities.js
- packages/core/src/returns/redux/actions/__tests__/doGetPickupCapabilities.test.js
- packages/core/src/returns/redux/actions/doGetPickupCapabilities.js
- Fix Pickup Capabilities timestamp parsing for pickupday and query.
None.
> fix(core): fix pickup capabilities timestamp parsing

- packages/react/src/analytics/integrations/Zaraz/Zaraz.js
- packages/react/src/analytics/integrations/Zaraz/eventsMapper.js
- packages/react/src/analytics/integrations/__tests__/Zaraz.test.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/Zaraz.test.js.snap
- This adds mappings for "Product Added to Cart" and "Product Added to
Wishlist" events in Zaraz integration.
- Fixed some leaks in Zaraz testing file.
- Fixed unnecessary console.error calls when an event that does not
contain a mapper is tracked.
> feat(blackout-react): add product added to cart/wishlist mappings in Zaraz

- packages/react/src/analytics/integrations/Zaraz/Zaraz.ts
- packages/react/src/analytics/integrations/Zaraz/__tests__/Zaraz.test.ts
- packages/react/src/analytics/integrations/Zaraz/__tests__/__snapshots__/Zaraz.test.ts.snap
- packages/react/src/analytics/integrations/Zaraz/eventsMapper.ts
- This adds mappings for "Product Added to Cart" and "Product Added to
Wishlist" events in Zaraz integration.
- Fixed some leaks in Zaraz testing file.
- Fixed unnecessary console.error calls when an event that does not
contain a mapper is tracked.
> feat(blackout-react): add product added to cart/wishlist mappings in Zaraz (next)

- packages/core/src/entities/schemas/searchResult.js
This adds a new fallback when generating the "facetId" for the filter segments. It will
use `undefined` for the descriptions and the facetId.
> fix: add fallback for filter segments without facet

- packages/react/src/analytics/integrations/Zaraz/Zaraz.js
- packages/react/src/analytics/integrations/Zaraz/constants.js
- packages/react/src/analytics/integrations/Zaraz/eventsMapper.js
- packages/react/src/analytics/integrations/__fixtures__/gaData.fixtures.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/__tests__/Zaraz.test.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/Zaraz.test.js.snap
- This adds mappings for "Product Viewed" and "Search"
events in Zaraz integration.
- Force transforming product ids to a string in Zaraz events.
> feat(blackout-react): add product viewed/search mappings in Zaraz

- packages/redux/src/addresses/selectors.ts
- packages/redux/src/bags/selectors.ts
- packages/redux/src/checkout/selectors.ts
- packages/redux/src/entities/selectors/cities.ts
- packages/redux/src/entities/selectors/contents.ts
- packages/redux/src/entities/selectors/countries.ts
- packages/redux/src/entities/selectors/entity.ts
- packages/redux/src/entities/selectors/states.ts
- packages/redux/src/orders/__tests__/selectors.test.ts
- packages/redux/src/orders/selectors.ts
- packages/redux/src/payments/selectors.ts
- packages/redux/src/products/selectors/lists.ts
- packages/redux/src/returns/__tests__/selectors.test.ts
- packages/redux/src/returns/selectors.ts
- packages/redux/src/wishlists/selectors/wishlists.ts
- packages/redux/src/wishlists/selectors/wishlistsSets.ts
- Fix getEntityById selector
- Fix getEntityById implementation erros
None.
> fix(redux): get entity selectors errors

- packages/client/src/authentication/types/deleteTokens.types.ts
- packages/client/src/authentication/types/login.types.ts
- packages/client/src/authentication/types/postPasswordChange.types.ts
- packages/client/src/authentication/types/postPasswordRecover.types.ts
- packages/client/src/authentication/types/postPasswordReset.types.ts
- packages/client/src/authentication/types/postRefreshEmailToken.types.ts
- packages/client/src/authentication/types/postRegister.types.ts
- packages/client/src/authentication/types/postTokens.types.ts
- packages/client/src/authentication/types/postUserImpersonation.types.ts
- packages/client/src/authentication/types/postValidateEmail.types.ts
- packages/client/src/authentication/types/register.types.ts
- packages/redux/src/authentication/actions/factories/changePasswordFactory.ts
- packages/redux/src/authentication/actions/factories/createClientCredentialsTokenFactory.ts
- packages/redux/src/authentication/actions/factories/createUserImpersonationFactory.ts
- packages/redux/src/authentication/actions/factories/createUserTokenFactory.ts
- packages/redux/src/authentication/actions/factories/loginFactory.ts
- packages/redux/src/authentication/actions/factories/logoutFactory.ts
- packages/redux/src/authentication/actions/factories/recoverPasswordFactory.ts
- packages/redux/src/authentication/actions/factories/refreshEmailTokenFactory.ts
- packages/redux/src/authentication/actions/factories/refreshTokenFactory.ts
- packages/redux/src/authentication/actions/factories/registerFactory.ts
- packages/redux/src/authentication/actions/factories/removeUserImpersonationFactory.ts
- packages/redux/src/authentication/actions/factories/removeUserTokenFactory.ts
- packages/redux/src/authentication/actions/factories/resetPasswordFactory.ts
- packages/redux/src/authentication/actions/factories/validateEmailFactory.ts
This PR is exporting inline declared types on blackout redux. i.e. loginFactory in inline typed but the type objects are not exported.
This is useful for tenants to import them and to apply in their sides.
> chore(redux): export inline types

- packages/client/src/users/types/getUser.types.ts
- packages/redux/src/users/actions/__tests__/fetchUser.test.ts
- packages/redux/src/users/actions/factories/fetchUserFactory.ts
Currently the FetchUserFactory action receives a data that isn’t used by the client, since the client only support a config object now. According to this, I'm removing the params from the redux action.
> fix(redux): remove unsupported params from FetchUserFactory

- packages/client/package.json
- packages/client/src/forms/types/formSchema.types.ts
- packages/redux/src/forms/__tests__/reducer.test.ts
- packages/redux/src/forms/selectors.ts
- yarn.lock
- This fixes the getFormSchemaByCode selector which was adding a default
value of an array when the schema was not found which would be
incorrect as it should return undefined in that case.
- Improved typings for FormSchema to match the type for the
json-schema package. Note: @types/form-schema is defined as a dependency
because our typings depend on it and typescript requires that we add
this as a dependency so the user of this package can browse to its
definitions.
- Fixed type errors in forms reducer testing file.
> fix(blackout-client|blackout-redux): fix getFormSchemaByCode selector

- packages/redux/src/analytics/middlewares/setUser.ts
- Removed middleware mandatory parameter because middleware always
extends the tenant options, applying a default in cases of empty parameter.
None.
> fix(redux): remove setUser middleware mandatory parameter

- packages/react/src/bags/hooks/__tests__/useBag.test.tsx
- packages/react/src/bags/hooks/types/useBag.ts
- packages/react/src/bags/hooks/types/useBagItem.ts
- packages/react/src/bags/hooks/useBag.ts
- packages/redux/src/bags/selectors.ts
This adds the return values for the selectors `getBagTotalQuantity` and `getBagItemsCounter` to the hook `useBag`; the hook now receives an optional parameter `excludeProductTypes` to use on the previous selectors.
None.
> feat: add `totalQuantity` and `itemsCount` to `useBag` hook

- packages/client/src/checkout/types/getCheckoutResponse.types.ts
This PR adds support for Recovered orderStatus on the get Checkout API Response
None.
> chore(client): add recovered to orderStatusError

- packages/client/package.json
- packages/client/src/index.ts
- packages/redux/package.json
- packages/redux/src/contents/__tests__/reducer.test.ts
- packages/redux/src/contents/__tests__/serverInitialState.test.ts
- packages/redux/src/contents/actions/__tests__/fetchCommercePages.test.ts
- packages/redux/src/contents/actions/__tests__/fetchContent.test.ts
- packages/redux/src/contents/actions/__tests__/fetchContentTypes.test.ts
- packages/redux/src/contents/actions/__tests__/fetchSEO.test.ts
- packages/redux/src/contents/actions/__tests__/resetContents.test.ts
- packages/redux/src/contents/index.ts
- packages/redux/src/contents/reducer.ts
- packages/redux/src/contents/serverInitialState.ts
- packages/redux/src/index.ts
- packages/redux/src/locale/__tests__/reducer.test.ts
- packages/redux/src/locale/__tests__/serverInitialState.test.ts
- packages/redux/src/locale/actions/__tests__/fetchCountries.test.ts
- packages/redux/src/locale/actions/__tests__/fetchCountry.test.ts
- packages/redux/src/locale/actions/__tests__/fetchCountryCities.test.ts
- packages/redux/src/locale/actions/__tests__/fetchCountryCurrencies.test.ts
- packages/redux/src/locale/actions/__tests__/fetchCountryStates.test.ts
- packages/redux/src/locale/actions/__tests__/resetLocaleState.test.ts
- packages/redux/src/locale/actions/__tests__/setCountryCode.test.ts
- packages/redux/src/locale/index.ts
- packages/redux/src/locale/reducer.ts
- packages/redux/src/locale/serverInitialState.ts
Exported client and actions of contents, locale and language on root to able developers to do imports like this:
`import { getContents } from “@farfetch/blackout-client”;`
renamed exports and removed default exports on contents folder.
package/redux
- removed reducer default export
- all exports are now in the following format '*Content'.
- actionTypes to actionTypesContent
- reducer to reducerContent
- serverInitialState to serverInitialStateContent
> feat(client|redux): export clients and actions on root

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
This PR removes a validation on our custom GA script logic that was causing problems on unit tests for node^16.x.x users. This validation is not necessary for the feature, therefore it can be removed.
> fix(react): remove unnecessary custom GA script validation

- packages/redux/src/locale/middlewares/setCountryCode.ts
Set customActionTypes argument in setCountryCode as optional.
None
> fix(blackout-redux): set customActionTypes as optional

- packages/client/src/helpers/adapters/adaptProductImages.ts
- packages/client/src/helpers/adapters/types/adaptProductImages.types.ts
This adds the `Image` type to `adaptProductImages`.
> fix: fix `adaptProductImages` type

- packages/client/src/bags/__tests__/patchBagItem.test.ts
- packages/client/src/bags/__tests__/postBagItem.test.ts
- packages/react/src/bags/hooks/__tests__/useBag.test.tsx
- packages/react/src/bags/hooks/__tests__/useBagItem.test.tsx
- packages/react/src/bags/hooks/types/useBag.ts
- packages/react/src/bags/hooks/types/useBagItem.ts
- packages/react/src/bags/hooks/useBag.ts
- packages/react/src/bags/hooks/useBagItem.ts
- packages/redux/src/bags/actions/__tests__/__snapshots__/addBagItem.test.ts.snap
- packages/redux/src/bags/actions/__tests__/__snapshots__/updateBagItem.test.ts.snap
- packages/redux/src/bags/actions/__tests__/addBagItem.test.ts
- packages/redux/src/bags/actions/__tests__/updateBagItem.test.ts
- tests/__fixtures__/bags/bag.fixtures.ts
This adds the `addBagItem` action to the `useBag` hook.
> feat: add `addBagItem` to `useBag`

- packages/redux/src/entities/reducer/__tests__/entitiesMapper.test.ts
- packages/redux/src/entities/reducer/entitiesMapper.ts
- packages/redux/src/returns/__tests__/reducer.test.ts
- packages/redux/src/returns/reducer.ts
- Merge entities mappers without removing duplicated keys.
When calling LOGOUT_SUCCESS it will correctly clear all entities with that action.
- entitiesMapper signature has changed. Now it receives an array
of extraMappers instead of an object.
None.
> fix(redux): merge entities and run duplicate keys

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/analytics/integrations/Omnitracking/Omnitracking.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/react/CHANGELOG.md
- packages/react/package.json
This PR adds the `viewCurrency` omnitracking parameter, calculated from the event context.
> feat(core): add currency to omnitracking's pre-calculated parameters

- packages/core/src/analytics/__fixtures__/pageData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/Omnitracking.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
This PR adds some missing parameters necessary for the tracking of Product Listing pages on Omnitracking.
> feat(core): add omnitracking's product list page missing parameters

- packages/core/src/products/details/client/getProductGrouping.js
- packages/core/src/products/details/redux/actions/doGetProductGrouping.js
This adds the property "properties" in the jsdoc of the query params
of the getProductGrouping client and doGetProductGrouping action.
> chore: add missing query param in getProductGrouping jsdoc

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/Omnitracking.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
This PR adds a new mapping on the analytics' omnitracking integration that grabs any `products[]` and converts them into a `lineItems` JSON.
Also adds the correct TID value for the product listing event.
> feat(blackout-core): add lineItems omnitracking mapping

- packages/core/src/contents/__tests__/utils.test.js
- packages/core/src/contents/redux/actions/__tests__/__snapshots__/doGetContent.test.js.snap
- packages/core/src/contents/redux/serverInitialState.js
- packages/core/src/contents/utils.js
- packages/react/src/content/hooks/useContentPage.js
- tests/__fixtures__/contents/contents.fixtures.js
fix hash creation for pagination props and commercepages
- removed subfolder and queryString on slug for commercepages hash on serverinitialstate
- added page property with default value on hash builder
- changed hash format to '${contentType}!${codes}!${page}${pageSize}'
- pageSize property is optional and if its have value will be split by commas like:
posts!all!1,5
- function name changed from stripSlugSubfolderJsonTrue to stripSlugSubfolder
the removal of json true rule. It isn't for core packages.
> fix(core|redux): fix hash creation for pagination props and commerce pages

- jest.config.js
- packages/react/src/wishlists/hooks/__tests__/useWishlist.test.tsx
- packages/react/src/wishlists/hooks/__tests__/useWishlistItem.test.tsx
- packages/react/src/wishlists/hooks/types/useWishlist.ts
- packages/react/src/wishlists/hooks/types/useWishlistItem.ts
- packages/react/src/wishlists/hooks/useWishlist.ts
- packages/react/src/wishlists/hooks/useWishlistItem.ts
- packages/react/tests/helpers/react.tsx
- packages/redux/src/wishlists/selectors/wishlists.ts
- packages/redux/src/wishlists/types/state.types.ts
- tests/__fixtures__/wishlists/wishlists.fixtures.ts
This PR is part of the work being developed in order to achieve consistent interfaces among all the react hooks (provided in the `blackout-react` package).
The `useWishlist` hook is now exposing the following interface:
- Params
- enableAutoFetch (optional)
- Return
- isLoading
- error
- isFetched
- data
- id
- count
- items
- isEmpty
- actions
- fetch()
- reset()
- addItem(productId, {sizeId, quantity})
- updateItem(wishlistItemId, {sizeId, quantity})
- removeItem(wishlistItemId) 
The `useWishlistItem` hook is now exposing the following interface:
- Params
- enableAutoFetch (optional)
- Return
- isLoading
- error
- isFetched
- data
- id
- quantity
- size
- product
- ...
- actions
- update({sizeId, quantity})
- remove() 
Depends on #411 
By sending us your contributions, you are agreeing …
> feat(react): refactor useWishlist

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/analytics/Analytics.js
- packages/core/src/analytics/__fixtures__/pageData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/react/src/analytics/__tests__/context.test.js
- packages/react/src/analytics/analytics.js
- packages/react/src/analytics/context.js
Since document.referrer stays the same on single page applications,
this PR adds an alternative property called `pageLocationReferrer`
for page trackings that will hold the previous URL when navigating trough
pages.
This PR also adds the type of event that is being tracked to each `useContext`
function and calls the webContext directly on the analyticsWeb constructor.
Mapped the Omnitracking's `referrer` to the new `pageLocationReferrer`,
since the document.referrer was causing issues when analyzing user behavior.
> feat(core|react): add analytics SPA page referrer context 

- packages/react/src/authentication/hooks/__tests__/useAuthentication.test.js
- packages/react/src/authentication/hooks/useUserAuthState.js
Added a function to reset auth reducer to initial state.
None
> fix: added reset function to reset auth state on react-core 

- packages/redux/src/locale/serverInitialState.ts
update keys on locale serverInitialState
defaultCulture and defaultSubfolder was changed to match data from first render and client.
> fix(redux): update keys on locale serverInitialState

- packages/core/src/analytics/integrations/Omnitracking/Omnitracking.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- packages/react/src/analytics/__tests__/context.test.js
- packages/react/src/analytics/context.js
This PR introduces the omnitracking's `lineItems` mapping for the product details page track.
It also introduces some changes on the omnitracking integration itself bring the `page`, `screen` and `track` flows a bit closer in terms of code logic - in essence it was simplified to use the same functions and only leave the specific logic to each type of event, which are the newly added pageEventMapper and the final process of the event structure that must follow the omnitracking service contract.
> feat(core): add omnitracking's product detail page tracking mappings

- packages/react/src/products/hooks/__tests__/useProductDetails.test.tsx
- packages/react/src/products/hooks/types/useProductDetails.ts
- packages/react/src/products/hooks/useProductDetails.ts
- packages/react/tests/helpers/react.tsx
- packages/redux/src/products/actions/resetProductDetails.ts
- packages/redux/src/products/actions/resetProductDetailsState.ts
- packages/redux/src/products/reducer/__tests__/details.test.ts
- packages/redux/src/products/reducer/details.ts
- packages/redux/src/products/types/actions/productDetails.types.ts
- tests/__fixtures__/products/state.fixtures.ts
This PR refactors the `useProductDetails` hook to its new interface:
- Params
- productId
- enabled (optional)
- Return
- isLoading
- error
- isFetched
- data
- id
- sizes
- sizesWithRemainingQuantity
- images
- … (product entity data)
- isOutOfStock
- isOneSize
- actions
- refetch()
- reset()
None.
> feat(react): refactor useProductDetails hook

- packages/react/src/analytics/integrations/GA4/commands.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
While implementing GA4 integration we received feedback that we should fire event `change_quantity` "when a user removes the last item from a product from the cart". Meaning firing `eventTypes.PRODUCT_UPDATED` with `oldQuantity` as previous added quantity and `quantity` as 0.
Since 0 is falsy, it will never fire this event because of the verification. So instead I think using lodash's `isFinite` is a better verification than just falsy check, as this makes it possible to fire `change_quantity` with `quantity` 0.
Reference to: https://github.com/Farfetch/blackout/pull/414
@AceBunny
None
> fix(react): fix GA4 integration not firing PRODUCT_UPDATED.CHANGE_QUANTITY when quantity is 0

- packages/react/src/content/hooks/useContentPage.js
Rollback of a change that remove comment of exhaustive-deps and changes useEffect.
This change cause an infinite loop in a page.
> fix: added isLoading to content page hook to prevent infinite loops

- packages/client/src/locale/__fixtures__/getCountries.fixtures.ts
- packages/client/src/locale/__tests__/getCountries.test.ts
- packages/client/src/locale/getCountries.ts
- packages/client/src/locale/types/countries.ts
- packages/redux/src/locale/actions/__tests__/__snapshots__/fetchCountries.test.ts.snap
- packages/redux/src/locale/actions/__tests__/__snapshots__/fetchCountry.test.ts.snap
- packages/redux/src/locale/actions/__tests__/__snapshots__/fetchCountryStates.test.ts.snap
- packages/redux/src/locale/actions/__tests__/fetchCountries.test.ts
- packages/redux/src/locale/actions/factories/fetchCountriesFactory.ts
- tests/__fixtures__/locale/locale.fixtures.ts
- This changes the getCountries client to return all countries
transparently to the consumer instead of returning a paginated
response from the service. In the future, the service will change to
return all countries instead of return a paginated response as well.
BREAKING CHANGE: The getCountries client now does not return a paginated
response and does not accept any query parameters. The result is
an array of all the countries available.
> fix: change getCountries client

- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added checkout abandoned event for omnitracking.
None.
> feat(core): add omnitracking's checkout abandoned event mappings

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added checkout event to omnitracking mapppers.
https://github.com/Farfetch/blackout/pull/435
> feat(core): add omnitracking's checkout page tracking mappings

- packages/core/src/analytics/__fixtures__/pageData.fixtures.js
- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added bag event to omnitracking mapppers.
https://github.com/Farfetch/blackout/pull/440
> feat(core): add omnitracking's bag page tracking mappings

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added edit checkout step event to omnitracking mapppers.
https://github.com/Farfetch/blackout/pull/444
> Feat add omnitracking edit checkout step track

- packages/core/src/analytics/integrations/Omnitracking/Omnitracking.js
This PR fixes a problem with the `navigatedFrom` parameter that was being calculated only on page views and it shouldn't, because pageviews don't bring a `from` parameter associated with it.
> fix(core): fix omnitrackings's 'navigatedFrom' parameter logic

- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/products/hooks/__tests__/useProductSizeGuides.test.tsx
- packages/react/src/products/hooks/index.ts
- packages/react/src/products/hooks/types/index.ts
- packages/react/src/products/hooks/types/useProductSizeGuides.ts
- packages/react/src/products/hooks/useProductSizeGuides.ts
- packages/redux/src/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/products/selectors/__tests__/sizeGuides.test.ts
- packages/redux/src/products/selectors/sizeGuides.ts
- tests/__fixtures__/products/state.fixtures.ts
This PR adds the `useProductSizeGuides` react hook :
- Params
- productId
- enableAutoFetch (optional)
- Return
- isLoading
- error
- isFetched
- data
- brand
- id
- name
- maps
- …
- actions
- refetch()
None.
> feat(react): add useProductSizeGuides hook

- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/products/hooks/__tests__/useProductAttributes.test.tsx
- packages/react/src/products/hooks/index.ts
- packages/react/src/products/hooks/types/index.ts
- packages/react/src/products/hooks/types/useProductAttributes.ts
- packages/react/src/products/hooks/useProductAttributes.ts
- tests/__fixtures__/products/state.fixtures.ts
This PR adds the `useProductAttributes` react hook :
- Params
- productId
- enableAutoFetch (optional)
- Return
- isLoading
- error
- isFetched
- data
- Array of
- id
- name
- values (Array)
- id
- value
- actions
- refetch()
None.
> feat(react): add useProductAttributes hook

- packages/client/src/bags/types/postBagItem.types.ts
- packages/redux/src/bags/utils/buildBagItem.ts
Fixed `buildBagItem` util that was returning an object with `customAttributes: "null"` (null as string) if the util function parameter `customAttributes` is `null`
none
> fix(redux): fix buildBagItem

- packages/redux/src/checkout/actions/factories/fetchCheckoutFactory.ts
- packages/redux/src/entities/schemas/checkoutOrderItem.ts
- packages/redux/src/entities/schemas/checkoutOrderItemProduct.ts
- This adds support to pass a `productImgQueryParam` to checkout order
items to add to their images' url, as it is being
done in other areas like bag, wishlist, orders and listing.
> fix(redux): add productImgQueryParam to checkout order items

- packages/client/src/helpers/client/__fixtures__/errors.fixtures.ts
- packages/client/src/helpers/client/__tests__/__snapshots__/formatError.test.ts.snap
- packages/client/src/helpers/client/__tests__/formatError.test.ts
- packages/client/src/helpers/client/formatError.ts
- packages/client/src/helpers/client/types/formatError.types.ts
- Add optional chaining on the adaptError function to work on the scenario when the error request doesn't have a valid description and the error message should be thrown (e.g. 404 Request Not Found)
None.
By sending us your contributions, you agree that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)
> fix(client): fix adaptError for errors with no response description

- packages/core/src/profile/client/getProfile.js
- packages/core/src/profile/redux/actions/doGetProfile.js
This pr adds the return of the client method response on doGetProfile action. It also adds a string literal validation on getProfile.
> feat(redux): add result return on doGetProfile

- packages/core/src/orders/redux/__fixtures__/orders.fixtures.js
- packages/core/src/orders/redux/__tests__/selectors.test.js
- packages/core/src/orders/redux/selectors.js
This adds a new selector for order splitting in the stable edition. This will provide a more optimised organization of the data in the store to be rendered in the tenant.
> feat(core): add new selector for order splitting

- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/index.ts
- packages/react/src/payments/hooks/__tests__/usePaymentTokens.test.tsx
- packages/react/src/payments/hooks/index.ts
- packages/react/src/payments/hooks/types/index.ts
- packages/react/src/payments/hooks/types/usePaymentTokens.types.ts
- packages/react/src/payments/hooks/usePaymentTokens.ts
- packages/react/src/payments/index.ts
- packages/redux/src/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/payments/__tests__/reducer.test.ts
- packages/redux/src/payments/__tests__/selectors.test.ts
- packages/redux/src/payments/reducer.ts
- packages/redux/src/payments/selectors.ts
This PR adds the `usePaymentTokens` react hook :
- Params
- enableAutoFetch (optional)
- Return
- isLoading
- error
- isFetched
- data
- items (Array of tokens)
- actions
- fetch
- remove
Also, a redux selector `arePaymentTokensFetched` was added to `blackout-redux`
None.
> feat(react): add usePaymentTokens hook

- packages/core/src/analytics/__fixtures__/pageData.fixtures.js
- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Fixed some missing mappings in checkout and bag events;
- Added share event to omnitracking;
- Adjust tests to cover this changes.
None.
> feat(core): add omnitracking's share event mappings

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added checkout started omnitracking event mapping.
https://github.com/Farfetch/blackout/pull/458
> Feat add omnitracking checkout started event

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added promocode applied event mapping.
None.
> feat(core): add omnitracking's promocode mappings

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/__tests__/omnitracking-helper.test.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added place order started event mapping;
- Fix omnitracking checkout event mapper helper to remove unwanted orderId;
- Fix tests;
None.
> feat(core): add omnitracking's place order started event mappings

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added order completed event mapping.
#476 
> Feat add omnitracking order completed event

- packages/core/src/orders/client/__tests__/postOrderShippingAddressChangeRequests.test.js
- packages/core/src/orders/client/postOrderShippingAddressChangeRequests.js
- Fixes the post change address request response from an object to status.
None.
> fix(client): change post address request response

- packages/client/src/checkout/types/checkoutOrder.types.ts
- packages/client/src/checkout/types/postCheckoutOrderCharge.types.ts
- packages/client/src/payments/types/payer.types.ts
- packages/client/src/payments/types/paymentIntentCharge.types.ts
- packages/client/src/payments/types/postPaymentIntentInstrument.types.ts
- packages/redux/src/checkout/actions/factories/fetchCheckoutOrderChargeFactory.ts
- packages/redux/src/entities/types/checkoutOrderItem.types.ts
Fixed `checkout` and `payments` types both on `blackout-redux` and `blackout-client`
None.
> fix(redux|client): fix checkout and payments types

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/__tests__/omnitracking-helper.test.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added address_info_added event mapping.
None.
> feat(core): add omnitracking's address info mappings

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added payment_info_added event mapping.
#486 
> Feat add omnitracking payment info event

- packages/analytics/src/integrations/Omnitracking/Omnitracking.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/constants.ts
- packages/analytics/src/integrations/Omnitracking/types/Omnitracking.types.ts
This PR adds a new option to the omnitracking integration so we can pass a custom http client to handle the requests, allowing to override the default behaviour of calling the internal postTrackings core client.
> feat(analytics): add new option to pass an http client to omnitracking integration - next

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/__tests__/omnitracking-helper.test.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added shipping method event mapping.
- Added shipping info event mapping.
#487 
> Feat add omnitracking shipping event

- packages/core/src/analytics/integrations/Omnitracking/Omnitracking.js
- packages/core/src/analytics/integrations/Omnitracking/constants.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
This PR adds a new option to the omnitracking integration so we can pass a custom http client to handle the requests, allowing to override the default behaviour of calling the internal `postTrackings` core client.
> feat(core): add new option to pass an http client to omnitracking integration

- packages/react/src/products/hooks/__tests__/useProductListing.test.tsx
- packages/react/src/products/hooks/useProductListing.ts
- packages/redux/src/brands/selectors.ts
- packages/redux/src/entities/types/product.types.ts
- packages/redux/src/products/selectors/__tests__/lists.test.ts
- packages/redux/src/products/selectors/lists.ts
- packages/redux/src/products/serverInitialState/__tests__/lists.test.ts
- packages/redux/src/products/serverInitialState/lists.ts
- tests/__fixtures__/products/productsLists.fixtures.ts
- tests/__fixtures__/products/state.fixtures.ts
This PR:
- adds brand data to each product returned by the `useProductListing` hook;
- fixes listing `serverInitialState` to infer whether the page is of type `set` or not. This change fixes the fact that the listing hash was being miscalculated (it was always calculated as `listing/<something>` instead of `sets/<something>` when it was a set page).
None.
> fix(react): add products brand data to useProductListing hook

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
Added product clicked event mapping to omnitracking;
#497.
> Feat add omnitracking product clicked event

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added filters cleared and filters applied event mapping to omnitracking;
#498.
> Feat add omnitracking filters events

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added login event mapping to omnitracking;
- Added signup event mapping to omnitracking;
#499.
> Feat add omnitracking login signup events

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added interact content event mapping to omnitracking;
#501.
> Feat add omnitracking interact content event

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Added select content event mapping to omnitracking;
- Reafactoring of interact content tests.
#503
> Feat add omnitracking select content event

- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- Added interact content's scroll track support on omnitracking;
- Tests improvement of omnitracking interact content;
#504
> Feat add omnitracking scroll track event

- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/bags/hooks/useBag.ts
- packages/react/src/categories/hooks/useCategories.ts
- packages/react/src/checkout/hooks/useCheckout.ts
- packages/react/src/contents/hooks/useCommercePages.ts
- packages/react/src/contents/hooks/useContentType.ts
- packages/react/src/contents/hooks/useMetaTags.ts
- packages/react/src/contents/hooks/useNavbars.ts
- packages/react/src/contents/hooks/usePage.ts
- packages/react/src/contents/hooks/useWidget.ts
- packages/react/src/helpers/index.ts
- packages/react/src/locale/hooks/useCountries.ts
- packages/react/src/locale/hooks/useCountryAddressSchemas.ts
- packages/react/src/locale/hooks/useCountryStateCities.ts
- packages/react/src/locale/hooks/useCountryStates.ts
- packages/react/src/orders/hooks/useOrders.ts
- packages/react/src/payments/hooks/usePaymentTokens.ts
- packages/react/src/products/hooks/useProductAttributes.ts
- packages/react/src/products/hooks/useProductDetails.ts
- packages/react/src/products/hooks/useProductListing.ts
- packages/react/src/products/hooks/useProductSizeGuides.ts
- packages/react/src/search/hooks/useSearchDidYouMean.ts
- packages/react/src/search/hooks/useSearchIntents.ts
- packages/react/src/search/hooks/useSearchSuggestions.ts
- packages/react/src/users/hooks/useUser.ts
- packages/react/src/users/hooks/useUserAddress.ts
- packages/react/src/users/hooks/useUserAddresses.ts
- packages/react/src/wishlists/hooks/useWishlist.ts
- packages/react/src/wishlists/hooks/useWishlistSet.ts
- packages/react/src/wishlists/hooks/useWishlistSets.ts
- This removes the `useAction` module from the public exports
of the react package as it is an internal helper module and
was requiring the installation of the redux package even when
not importing this module specifically (ex: importing another
module from the package root).
BREAKING CHANGE: `useAction` hook is not available from
react package. Use `useDispatch` hook from `react-redux` directly instead.
Closes #401 
> fix(react): remove `useAction` from public exports

- packages/react/src/products/hooks/__tests__/useProductListing.test.tsx
- packages/react/src/products/hooks/useProductListing.ts
- packages/redux/src/entities/types/productsList.types.ts
- packages/redux/src/products/actions/resetProductDetails.ts
- packages/redux/src/products/actions/resetProductDetailsState.ts
- packages/redux/src/products/actions/resetProductsLists.ts
- packages/redux/src/products/actions/resetProductsListsState.ts
- packages/redux/src/products/reducer/__tests__/details.test.ts
- packages/redux/src/products/reducer/__tests__/lists.test.ts
- packages/redux/src/products/reducer/details.ts
- packages/redux/src/products/reducer/lists.ts
- packages/redux/src/products/types/actions/productDetails.types.ts
- packages/redux/src/products/types/actions/productsLists.types.ts
- tests/__fixtures__/products/productsLists.fixtures.ts
- This fixes the resetProductsLists action to include support for resetting only specific products lists instead of resetting all list states. This will fix the `useProductListing` hook reset action which will now only reset the state of the listing passed as its parameter.
- Small refactoring of the `details` reducer to reuse reset code between slices.
> fix(redux): fix resetProductsLists action

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
This PR fixes a bug where a GA4 event was being triggered before a page view, which was causing an issue where the event was not being sent to GA with the correct page path. For this to happen, a page view must be registered on the dataLayer first, so the event being triggered after can be associated with the correct page_path.
> fix(react): fix GA4 page and event tracking

- packages/analytics/src/integrations/Omnitracking/Omnitracking.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/types/Omnitracking.types.ts
- Added pre-calculated viewCurrency parameter to omnitracking.
None.
> feat(analytics): add omnitracking pre-calculated parameters

- packages/client/src/settings/__tests__/getConfiguration.test.ts
- packages/client/src/settings/types/getConfiguration.ts
- packages/client/src/settings/types/getConfigurations.ts
- Add a default parameter and make the query parameter on `getConfiguration` and `getConfigurations` clients
None.
> chore(client): make query param optional on configuration clients

- packages/analytics/src/Analytics.ts
- packages/analytics/src/integrations/Omnitracking/Omnitracking.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/analytics/src/types/analytics.types.ts
- packages/react/src/analytics/__tests__/context.test.ts
- packages/react/src/analytics/context.ts
- tests/__fixtures__/analytics/baseAnalyticsEventData.fixtures.ts
- tests/__fixtures__/analytics/page/index.ts
- tests/__fixtures__/analytics/page/listingPageData.fixtures.ts
- tests/__fixtures__/analytics/page/productPageData.fixtures.ts
- Add persist of navigation from parameter, by using from parameter on page events;
- Add Product Listing Page Event to omnitracking;
- Add Product Page Event to omnitracking;
- Since document.referrer stays the same on single page applications,
this PR adds an alternative property called `pageLocationReferrer`
for page trackings that will hold the previous URL when navigating trough
pages.
- This PR also adds the type of event that is being tracked to each `useContext`
function and calls the webContext directly on the analyticsWeb constructor.
Mapped the Omnitracking's `referrer` to the new `pageLocationReferrer`,
since the document.referrer was causing issues when analyzing user behavior.
- Adjust test to cover the above points.
By sending us your contributions, you are agreeing that …
> feat(analytics|react): add product details and listing pages to omnitracking

- packages/analytics/src/integrations/Omnitracking/Omnitracking.ts
- packages/analytics/src/integrations/Omnitracking/__fixtures__/expectedPagePayloadMobile.fixtures.ts
- packages/analytics/src/integrations/Omnitracking/__fixtures__/expectedPagePayloadUnknown.fixtures.ts
- packages/analytics/src/integrations/Omnitracking/__fixtures__/expectedPagePayloadWeb.fixtures.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/Omnitracking/Omnitracking.ts
- packages/react/src/analytics/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/react/src/analytics/integrations/Omnitracking/omnitracking-web-helper.ts
- tests/__fixtures__/analytics/baseAnalyticsEventData.fixtures.ts
- Moved the two parameters logic to the react facade as it should only be applied on the web.
- Also fixed the calculation itself. Instead of looking at the culture passed via analytics.useContext(), it will now look at the subfolder.
None.
> fix(analytics|react): fix omnitracking's clientLanguage and clientCountry parameters

- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- Added omnitracking checkout abandoned event.
None.
> feat(analytics): add omnitracking's checkout abandoned event mappings

- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/omnitracking-helper.test.ts
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- Added place order started event mapping;
- Add mapper helper to deal with checkout orderId and orderCode;
- Fix tests;
#528 
> Feat add checkout order placed omnitracking next

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- tests/__fixtures__/analytics/page/checkoutPageData.fixtures.ts
- tests/__fixtures__/analytics/page/index.ts
This PR adds mappings for the checkout started event and the checkout page view event.
None.
> feat(analytics): add omnitracking's checkout started and checkout page view event mappings

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
Added edit checkout step event to omnitracking mapppers.
None.
> feat(analytics): add omnitracking's edit checkout step tracking mappings

- packages/react/src/analytics/integrations/GA4/eventMapping.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
This PR remove percentage string in scroll event, sending only the numeric value of percentageScrolled.
None.
> feat(analytics): remove percentage in scroll event

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- tests/__fixtures__/analytics/track/shareTrackData.fixtures.ts
- Added share event to omnitracking;
None.
> feat(analytics): add omnitracking's share event mappings

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/omnitracking-helper.test.ts
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- tests/__fixtures__/analytics/track/addressInfoAddedTrackData.fixtures.ts
Added address_info_added event mapping on omnitracking integration.
None.
> feat(analytics): add omnitracking's address info mappings

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/omnitracking-helper.test.ts
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- tests/__fixtures__/analytics/track/shippingInfoAddedTrackData.fixtures.ts
- tests/__fixtures__/analytics/track/shippingMethodAddedTrackData.fixtures.ts
This PR adds mappings for the following events:
- `Payment Info Added`
- `Shipping Info Added`
- `Shipping Method Added`
None.
> feat(analytics): add omnitracking's shipping and payment mappings

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/react/src/analytics/integrations/GA/__tests__/__snapshots__/GA.test.ts.snap
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/Zaraz/__tests__/__snapshots__/Zaraz.test.ts.snap
- tests/__fixtures__/analytics/track/orderCompletedTrackData.fixtures.ts
- Added order completed event mapping to the omnitracking integration.
None.
> feat(analytics|react): add omnitracking's order completed mappings

- packages/core/src/orders/client/helpers/adaptOrderDetails.js
- packages/core/src/orders/client/postOrderItemActivities.js
- packages/core/src/orders/redux/actions/__tests__/__snapshots__/doGetOrderDetails.test.js.snap
- packages/core/src/orders/redux/actions/doGetOrderDetails.js
- packages/core/src/orders/redux/actions/doPostOrderItemActivities.js
- Fixed split by merchant validation in getOrderDetails
- Added missing order status to adaptOrderStatus
- Fixed postOrderItemActivities action and client
None.
> fix(core): split by merchant validation

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- Added add product clicked event mapping to omnitracking;
None.
> feat(analytics): add omnitracking's product clicked event mappings

- packages/analytics/src/integrations/Omnitracking/Omnitracking.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/types/Omnitracking.types.ts
This PR fixes an issue where the page events mapper were just being called in unit tests and wasn't being used on the code itself. This brings a refactor that was done previously on the main branch.
None.
> fix(analytics): make use of omnitracking's page events mapper

- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/omnitracking-helper.test.ts
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/analytics/src/integrations/Omnitracking/types/Omnitracking.types.ts
- tests/__fixtures__/analytics/track/selectContentTrackData.fixtures.ts
- Added select content event mapping to omnitracking;
None.
> feat(analytics): add omnitracking's select content events mappings

- packages/analytics/src/__tests__/__snapshots__/index.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/omnitracking-helper.test.ts
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/analytics/src/types/index.ts
- packages/analytics/src/types/signupNewsletterGenderTypes.ts
- packages/react/src/analytics/integrations/GA4/eventMapping.ts
- packages/react/src/analytics/integrations/shared/dataMappings/index.ts
- Added signup newsletter event mapping to omnitracking;
- Fix problem related with gender on ga4 integration;
None.
> feat(analytics|react): add omnitracking's signup newsletter events mappings

- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
Removed events that are now properly handled by the Vitorino script to avoid having them duplicated.
None.
> fix(analytics): remove omnitracking's duplicated events

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/omnitracking-helper.test.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
This PR fixes a bug in the omnitracking and GA4 parity for the checkout steps events.
None.
> fix(analytics|react): fix checkout steps mapping for GA4 and omnitracking parity

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/analytics/integrations/Omnitracking/__tests__/omnitracking-helper.test.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.js
This PR fixes a bug in the omnitracking and GA4 parity for the checkout steps events.
None.
> fix(core|react): fix checkout steps mapping for GA4 and omnitracking parity

- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/index.ts
- packages/react/src/settings/hooks/__tests__/useConfiguration.test.tsx
- packages/react/src/settings/hooks/__tests__/useConfigurations.test.tsx
- packages/react/src/settings/hooks/index.ts
- packages/react/src/settings/hooks/types/index.ts
- packages/react/src/settings/hooks/types/useConfiguration.ts
- packages/react/src/settings/hooks/types/useConfigurations.ts
- packages/react/src/settings/hooks/useConfiguration.ts
- packages/react/src/settings/hooks/useConfigurations.ts
- packages/react/src/settings/index.ts
- tests/__fixtures__/settings/configurations.fixtures.ts
This PR adds the following hooks to the settings folder: `useConfiguration` and `useConfigurations`
> feat(react): settings hooks

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- tests/__fixtures__/analytics/track/interactContentTrackData.fixtures.ts
- Added interact content event mapping to omnitracking next;
None.
> feat(analytics|react): add omnitracking's interact content events mappings next

- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/definitions.ts
Added interact content's scroll track support on omnitracking;
[561](https://github.com/Farfetch/blackout/pull/561)
> feat(analytics|react): add omnitracking's scroll track on interact content event mappings next

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
This PR changes the way we send page view events to GA4 enabling compatibility with recently created properties.
None.
> feat(react): update GA4 page view command

- packages/react/src/analytics/integrations/GA4/GA4.ts
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
This PR changes the way we send page view events to GA4 enabling compatibility with recently created properties.
None.
> feat(react): update GA4 page view command - next

- packages/react/src/analytics/integrations/Castle/Castle.ts
- packages/react/src/analytics/integrations/Castle/__tests__/Castle.test.ts
- tests/__fixtures__/analytics/baseAnalyticsEventData.fixtures.ts
This PR includes the removal of the unnecessary tracking requests being sent to castle.io, along with a fix on the `registered_at` property to comply with the castle's date format.
> fix(react): remove unnecessary castle.io tracking requests

- packages/core/src/analytics/redux/middlewares/__tests__/setUser.test.js
- packages/core/src/analytics/redux/middlewares/setUser.js
This PR fixes a bug when the user manually logs out.
The `LOGOUT` event was only being triggered when the user session expired. 
Now it will be correctly triggered in that case and when the user manually logs out, or when the GET_PROFILE action fails.
> fix(core): fix analytics' setUser middleware on logout action

- packages/redux/src/bags/__tests__/reducer.test.ts
- packages/redux/src/bags/reducer.ts
- This adds missing actions to some slices of the bag reducer in order to correctly update its state. For example, when using the `useBag` hook, if the product is already on the bag, an update will be performed to that bag item which would not update the `isLoading` slice of the bag reducer to `true`.
> fix(redux): fix bag reducer

- packages/react/src/bags/hooks/__tests__/useBag.test.tsx
- packages/react/src/bags/hooks/errors/index.ts
- packages/react/src/bags/hooks/useBag.ts
- tests/__fixtures__/bags/bag.fixtures.ts
- This adds throw statements to `handleAddUpdateBagItem` and `handleFullUpdate` functions used by the actions in `useBag` hook in order to communicate to the consumer that it was unable to perform the action. This replaces the early return strategy which would not communicate to the user that the actions were unable to perform an add/update of a bag item because there was either missing information or no stock available.
> fix(react): fix add/update bag item errors in useBag hook

- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/redux/src/analytics/middlewares/__tests__/setUser.test.ts
- packages/redux/src/analytics/middlewares/setUser.ts
This PR fixes a bug when the user manually logs out.
The LOGOUT event was only being triggered when the user session expired.
Now it will be correctly triggered in that case and when the user manually logs out, or when the GET_PROFILE action fails.
None.
> fix(redux): fix analytics' setUser middleware on logout action - Next

- packages/redux/src/locale/serverInitialState.ts
- packages/redux/src/types/model.types.ts
- tests/__fixtures__/locale/locale.fixtures.ts
- Fix the model property being used to set the sourceCountryCode in the locale initial state
> fix(redux): fix countrySourceCode in locale initial state

- scripts/release.sh
- This fixes a bug with the release script that was not sending the --yes flag to the lerna version command which prevented the correct release of new versions and
also activated verbose logs for lerna calls.
> chore: fix missing yes flag in lerna version

- scripts/release.sh
- This fixes an error with the positioning of the --yes flag that was by mistake added to between the --message flag which confused lerna version command.
> chore: fix --yes flag position in lerna version

- packages/client/src/__tests__/__snapshots__/index.test.ts.snap
- packages/client/src/helpers/client/index.ts
- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/bags/hooks/index.ts
- packages/react/src/brands/hooks/index.ts
- packages/react/src/categories/hooks/index.ts
- packages/react/src/contents/index.ts
- packages/react/src/locale/index.ts
- packages/react/src/orders/hooks/index.ts
- packages/react/src/payments/hooks/index.ts
- packages/react/src/products/hooks/index.ts
- packages/react/src/search/hooks/index.ts
- packages/react/src/settings/hooks/index.ts
- packages/react/src/subscriptions/hooks/index.ts
- packages/react/src/users/hooks/index.ts
- packages/redux/src/addresses/index.ts
- This adds missing type exports from react and redux packages.
> chore(react|redux): add missing type exports

- packages/client/src/returns/types/getReturn.types.ts
- packages/client/src/returns/types/getReturnPickupCapability.types.ts
- packages/client/src/returns/types/getReturnPickupRescheduleRequests.types.ts
- packages/client/src/returns/types/patchReturn.types.ts
- packages/client/src/returns/types/postReturnPickupRescheduleRequests.types.ts
- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/returns/hooks/__tests__/useReturn.test.tsx
- packages/react/src/returns/hooks/__tests__/useReturnPickupRescheduleRequest.test.ts
- packages/react/src/returns/hooks/__tests__/useReturnPickupRescheduleRequests.test.ts
- packages/react/src/returns/hooks/index.ts
- packages/react/src/returns/hooks/types/index.ts
- packages/react/src/returns/hooks/types/useReturnPickupRescheduleRequest.ts
- packages/react/src/returns/hooks/types/useReturnPickupRescheduleRequests.ts
- packages/react/src/returns/hooks/useReturn.ts
- packages/react/src/returns/hooks/useReturnPickupRescheduleRequest.ts
- packages/react/src/returns/hooks/useReturnPickupRescheduleRequests.ts
- packages/react/tests/helpers/flushPromises.ts
- packages/redux/src/returns/actions/factories/createReturnPickupRescheduleRequestFactory.ts
- tests/__fixtures__/returns/returns.fixtures.ts
- This add the hooks useReturnPickupRescheduleRequests and useReturnPickupRescheduleRequest to
manage return pickup reschedule requests.
- Adds some types fixing as well.
> feat(redux|react): add pickup reschedule hooks

- packages/react/src/content/hooks/useContentType.js
Fix the environmentCode: avoiding sending request with the environmentCode empty when there is no value either on props or `WEB_APP_CONTENT_ENV`. Change to default: "live"
None
> fix: remove environmentCode query

- packages/react/src/bags/hooks/__tests__/useBag.test.tsx
- packages/react/src/bags/hooks/useBag.ts
- packages/react/src/contents/components/base/contentList/ContentList.tsx
- packages/react/src/contents/helpers/__tests__/renderContent.test.tsx
- packages/react/src/contents/helpers/renderContent.tsx
- packages/react/src/contents/types/component.types.ts
- packages/react/src/contents/types/metatags.types.ts
- packages/react/src/wishlists/hooks/__tests__/useWishlist.test.tsx
- packages/react/src/wishlists/hooks/useWishlist.ts
- packages/redux/src/analytics/middlewares/__tests__/bag.test.ts
- packages/redux/src/analytics/middlewares/bag.ts
- packages/redux/src/bags/__tests__/selectors.test.ts
- packages/redux/src/bags/selectors.ts
- packages/redux/src/entities/types/wishlistItem.types.ts
- packages/redux/src/products/selectors/product.ts
- packages/redux/src/wishlists/selectors/__tests__/wishlists.test.ts
- packages/redux/src/wishlists/selectors/wishlists.ts
- This fixes `getWishlistItems` selector that was recalculating its value unnecessarily every time the state changed even though it was using `createSelector` because of an incorrect function input to createSelector that was selecting the whole state.
- Changed `getBagItemAvailableSizes` selector to not use `getBagItem` in its implementation as it would invalidate the cached result created by createSelector as it would change the bag item id parameter.
- Refactored `getBagItems`, `getBagItem`, `getWishlistItems` and `getWishlistItem` selectors to use a common denormalize function.
- Changed `useWishlist` and `useBag` hooks to returned undefined when the wishlist and bag are undefined respectively. This is to avoid generating a new object reference when the data has not changed.
- Changed …
> fix(react|redux): fix wishlist and bag selectors

- packages/client/src/wishlists/types/patchWishlistSet.types.ts
- packages/react/src/bags/hooks/__tests__/useBagItem.test.tsx
- packages/react/src/bags/hooks/useBagItem.ts
- packages/react/src/wishlists/hooks/__tests__/useWishlistItem.test.tsx
- packages/react/src/wishlists/hooks/useWishlistItem.ts
- packages/react/src/wishlists/hooks/useWishlistSets.ts
- packages/redux/src/analytics/middlewares/__tests__/wishlist.test.ts
- packages/redux/src/analytics/middlewares/wishlist.ts
- packages/redux/src/wishlists/actions/factories/updateWishlistSetFactory.ts
- packages/redux/src/wishlists/types/actions.types.ts
- added support for metadata on bag and wishlist action's.
- Moved `from` property from `PatchWishlistSetData` to new created type `WishlistSetActionMetadata`.
- Added new parameter to `updateWishlistSetFactory` for metadata.
```js
// Previously
const setId= 'setId';
const data: PatchWishlistSetData = [
{
from: 'BAG',
.... // another values
}
];
updateWishlistSetFactory(...)(setId, data);
// Now
const setId= 'setId';
const data: PatchWishlistSetData = [
{
.... // other values
}
];
const metadata: WishlistSetActionMetadata = {
from: 'BAG'
}
updateWishlistSetFactory(...)(setId, data, metadata);
```
None. …
> feat(client|redux|react) add support to metadata on bag and wishlist actions for NEXT

- packages/react/src/contents/types/metatags.types.ts
- packages/react/src/contents/utils/getListingSeoMetadataParams.ts
- This fixes getListingSeoMetadataParams implementation to make it take into account that the listing name might be null as well.
> fix(react): fix getListingSeoMetadataParams

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/omnitracking-helper.test.ts
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/analytics/src/utils/getters.ts
- packages/react/src/analytics/integrations/GA/commands.ts
- packages/react/src/analytics/integrations/GA4/GA4.ts
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.ts
- packages/react/src/analytics/integrations/GA4/types/index.ts
- Normalize mapping of property productId on Omnitracking and GA4 integrations.
None.
> feat(analytics|react): normalize property of productId on Analytics for next

- packages/analytics/src/integrations/Omnitracking/Omnitracking.ts
- applied same logic as main logic releated with navigated from parameter
of omnitracking.
None. 
> Fix omnitracking navigatedfrom parameter logic

- packages/core/src/profile/client/__fixtures__/getUserReturns.fixtures.js
- packages/core/src/profile/client/__tests__/__snapshots__/getUserReturns.test.js.snap
- packages/core/src/profile/client/__tests__/getUserReturns.test.js
- packages/core/src/profile/client/getUserReturns.js
- packages/core/src/profile/client/index.js
- packages/core/src/profile/redux/__fixtures__/userReturns.fixtures.js
- packages/core/src/profile/redux/actionTypes.js
- packages/core/src/profile/redux/actions/__tests__/__snapshots__/doGetUserReturns.test.js.snap
- packages/core/src/profile/redux/actions/__tests__/doGetUserReturns.test.js
- packages/core/src/profile/redux/actions/doGetUserReturns.js
- packages/core/src/profile/redux/actions/index.js
This adds the new get user returns endpoint that is used to fetch all of an authenticated user returns with pagination.
None
> feat(core): add new get user returns endpoints

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
This PR updates a tracker ID on the omnitracking integration for the signup newsletter event.
None.
> fix(analytics): fix omnitracking TID value for signup newsletter event - NEXT

- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
This PR updates a tracker ID on the omnitracking integration for the signup newsletter event.
None.
> fix(core): fix omnitracking TID value for signup newsletter event

- packages/core/src/checkout/redux/__tests__/reducer.test.js
- packages/core/src/checkout/redux/actionTypes.js
- packages/core/src/checkout/redux/actions/__tests__/resetPromocode.test.js
- packages/core/src/checkout/redux/actions/index.js
- packages/core/src/checkout/redux/actions/resetPromocode.js
- This PR makes possible to reset the promo code in the blackout core;
- In blackout, there is no action responsible for changing properties to the inital state of the promocode, and with this PR, it becomes quite simplified, because in some situation at checkout it may be necessary to reset these values to the initial ones;
- A new action was then added with the name SET_PROMOCODE_RESET able to respond to what was intended;
- Finally, all the logic responsible for processing this action is already developed in the checkout reducer;
> fix(redux): Fix action promocode reset in checkout

- packages/core/src/returns/client/__fixtures__/getUserReturns.fixtures.js
- packages/core/src/returns/client/__tests__/getUserReturns.test.js
- packages/core/src/returns/client/getUserReturns.js
- packages/core/src/returns/redux/actions/__tests__/doGetUserReturns.test.js
- packages/core/src/returns/redux/actions/doGetUserReturns.js
- Added missing query parameter to getUserReturns endpoint.
None.
> fix(core): add query to get user returns

- packages/analytics/src/integrations/Omnitracking/definitions.ts
This change fixes the validation of select content event parameters in case the id is equal to 0.
None
> fix: select content analytics event

- packages/client/src/contents/__tests__/getSearchContents.test.ts
- packages/client/src/contents/getSearchContents.ts
- packages/client/src/contents/types/contents.types.ts
Add `target.segment ` on searchContents function
> feat(client): add segment at target on searchContents

- packages/client/src/checkout/__tests__/getCheckoutOrderDetails.test.ts
- packages/client/src/checkout/types/deliveryBundle.types.ts
- packages/redux/src/checkout/actions/__tests__/__snapshots__/createCheckoutOrder.test.ts.snap
- packages/redux/src/checkout/actions/__tests__/__snapshots__/fetchCheckoutOrder.test.ts.snap
- packages/redux/src/checkout/actions/__tests__/__snapshots__/setCheckoutOrderItemTags.test.ts.snap
- packages/redux/src/checkout/actions/__tests__/__snapshots__/setCheckoutOrderPromocode.test.ts.snap
- packages/redux/src/checkout/actions/__tests__/__snapshots__/setCheckoutOrderTags.test.ts.snap
- packages/redux/src/checkout/actions/__tests__/__snapshots__/updateCheckoutOrder.test.ts.snap
- packages/redux/src/products/serverInitialState/products.ts
- tests/__fixtures__/checkout/checkout.fixtures.ts
This changes the serverInitialState handling of the
`productAttributes` property from page model to discard it if the value
is an empty array since the server will return an empty array by default
even when no request to fetch the product attributes was made.
Without this change, it was impossible to distinguish if the product
has no attributes or if the attributes were not fetched and the client
should then fetch them.
Also, added a fix for the DeliveryBundle type in checkout which
was missing some properties.
> fix(redux): fix product attributes server render

- packages/analytics/src/Analytics.ts
- packages/analytics/src/Consent.ts
- packages/analytics/src/__tests__/__snapshots__/index.test.ts.snap
- packages/analytics/src/__tests__/consent.test.ts
- packages/analytics/src/integrations/Integration.ts
- packages/analytics/src/integrations/__tests__/Integration.test.ts
- packages/analytics/src/types/analytics.types.ts
- packages/analytics/src/utils/__tests__/__snapshots__/contants.test.ts.snap
- packages/analytics/src/utils/__tests__/contants.test.ts
- packages/analytics/src/utils/constants.ts
- packages/analytics/src/utils/index.ts
- packages/react/src/analytics/integrations/GA/GA.ts
- packages/react/src/analytics/integrations/GA/__tests__/GA.test.ts
- packages/react/src/analytics/integrations/GA4/GA4.ts
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.ts
This PR introduces a new feature on the analytics package that allows the projects to define custom consent categories to integrations. The built-in ones will still use its default consent categories.
- Added custom consent feature;
- Adapted the .shouldLoad() method on the Integration class to contain all logic regarding the consent and removed this method from the integrations that no longer need it (as all the work will now be done on the static method of the Integration class;
- From now on, built-in integrations that need consent can just define a static property on the class called consentCategories - this will be used on the .shouldLoad() method of the Integration class if no custom consent categories are defined via the integration's options.
None.
By sending us your …
> feat(analytics|react): allow analytics to work with any consent categories - NEXT

- packages/core/src/analytics/Analytics.js
- packages/core/src/analytics/Consent.js
- packages/core/src/analytics/__tests__/analytics.test.js
- packages/core/src/analytics/__tests__/consent.test.js
- packages/core/src/analytics/integrations/Integration.js
- packages/core/src/analytics/integrations/__tests__/Integration.test.js
- packages/core/src/analytics/utils/__tests__/__snapshots__/contants.test.js.snap
- packages/core/src/analytics/utils/constants.js
- packages/react/src/analytics/integrations/Castle/CastleV1.js
- packages/react/src/analytics/integrations/Castle/CastleV2.js
- packages/react/src/analytics/integrations/Forter/Forter.js
- packages/react/src/analytics/integrations/GA/GA.js
- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/GTM/GTM.js
- packages/react/src/analytics/integrations/Riskified.js
- packages/react/src/analytics/integrations/Vitorino/Vitorino.js
This PR introduces a new feature on the analytics package that allows the projects to define custom consent categories to integrations. The built-in ones will still use its default consent categories.
- Added custom consent feature;
- Adapted the `.shouldLoad()` method on the `Integration` class  to contain all logic regarding the consent and removed this method from the integrations that no longer need it (as all the work will now be done on the static method of the `Integration` class;
- From now on, built-in integrations that need consent can just define a static property on the class called `consentCategories` - this will be used on the `.shouldLoad()` method of the `Integration` class if no custom consent categories are defined via the integration's options.
- Removed some …
> feat(core|react): allow analytics to work with any consent categories

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- Add a method to stringify the filters object (this was already being done to GA4 but not for omni).
None
> Feat(analytics): add filters validation analytics

- packages/react/src/analytics/integrations/Vitorino/index.js
- Add missing export of VITORINO_PROVIDERS.
None.
> fix(react): add missing export on vitorino

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- Fixed filters validation method. It was returning an object when it should be returning directly the string.
None
> fix: filters validation analytics

- packages/client/package.json
This fixes the previous commit that reintroduced the authentication interceptor but missed the crypto-js dependency.
- [] The code is commented, particularly in hard-to-understand areas
> fix(client): add crypto-js to client's dependencies

- packages/client/src/language/types/translations.type.ts
Removal of deprecated parameters 'client_id' and 'tenant_id'
from 'Translation' type as they are now inferred from the token.
'client_id' and 'tenant_id' parameters were removed from 'Translation' type.
They are now inferred from the token.
> fix: remove deprecated params from translations

- packages/core/src/contents/client/__fixtures__/contents.fixtures.js
- packages/core/src/contents/client/__tests__/getSearchContents.test.js
- packages/core/src/contents/client/getSearchContents.js
Add `target.segment` on searchContents function
> feat(core|client): add segment at targets on searchContent

- packages/core/src/bags/client/__fixtures__/putBagPromocodes.fixtures.js
- packages/core/src/bags/client/__tests__/__snapshots__/putBagPromocodes.test.js.snap
- packages/core/src/bags/client/__tests__/putBagPromocodes.test.js
- packages/core/src/bags/client/index.js
- packages/core/src/bags/client/putBagPromocodes.js
- packages/core/src/bags/redux/__tests__/reducer.test.js
- packages/core/src/bags/redux/__tests__/selectors.test.js
- packages/core/src/bags/redux/actionTypes.js
- packages/core/src/bags/redux/actions/__tests__/__snapshots__/doSetBagPromocodes.test.js.snap
- packages/core/src/bags/redux/actions/__tests__/doSetBagPromocodes.test.js
- packages/core/src/bags/redux/actions/doSetBagPromocodes.js
- packages/core/src/bags/redux/actions/index.js
- packages/core/src/bags/redux/middlewares/__tests__/getBagOnSetPromocodesRequestSuccess.test.js
- packages/core/src/bags/redux/middlewares/getBagOnSetPromocodesRequestSuccess.js
- packages/core/src/bags/redux/middlewares/index.js
- packages/core/src/bags/redux/reducer.js
- packages/core/src/bags/redux/selectors.js
- tests/__fixtures__/bags/bag.fixtures.js
This PR adds the ability to set promo code in bag (in this moment only **one** promo code can be applied)
> Feat(core): add put bags promo codes endopint

- packages/analytics/package.json
- packages/client/package.json
- packages/react/package.json
- packages/redux/package.json
This adds "type": "module" to all package.json files of all packages that was missing. This will broad the compatibility of the packages with other frameworks like fastify.
> fix: add "type": "module" to all packages

- packages/core/src/checkout/redux/__tests__/reducer.test.js
- packages/core/src/checkout/redux/reducer.js
This fixes an issue where the properties `state.code` and `state.name`  in the shipping/billing address of a checkout order would not be cleared in the store if their value was `undefined`.
No.
> fix(core): checkout reducer not overwriting address state

- packages/redux/src/checkout/__tests__/reducer.test.ts
- packages/redux/src/checkout/reducer.ts
This fixes an issue where the properties `state.code` and `state.name` in the shipping/billing address of a checkout order would not be cleared in the store if their value was `undefined`.
None.
> fix(redux): checkout reducer not overwriting address state

- package.json
- packages/react/src/authentication/hooks/__tests__/useAuthentication.test.tsx
- packages/redux/package.json
- packages/redux/src/contents/__tests__/reducer.test.ts
- packages/redux/src/entities/schemas/order.ts
- yarn.lock
This updates typescript to version 4.9. To do so, it was required to
bump `msw`, `reselect` and `@types/node` packages to versions that
supported TS 4.9. Also, a few new issues were found by the new TS
version which were changed.
> chore: update typescript to 4.9

- packages/react/src/bags/hooks/useBag.ts
- packages/redux/src/bags/actions/factories/addBagItemFactory.ts
- packages/redux/src/bags/actions/factories/fetchBagFactory.ts
- packages/redux/src/bags/actions/factories/fetchBagOperationFactory.ts
- packages/redux/src/bags/actions/factories/removeBagItemFactory.ts
- packages/redux/src/bags/actions/factories/setBagPromocodesFactory.ts
- packages/redux/src/bags/actions/factories/updateBagItemFactory.ts
- packages/redux/src/users/authentication/actions/factories/fetchGuestUserFactory.ts
- packages/redux/src/users/authentication/actions/factories/fetchUserFactory.ts
- packages/redux/src/users/authentication/actions/factories/loginFactory.ts
- packages/redux/src/users/authentication/actions/factories/logoutFactory.ts
- packages/redux/src/users/authentication/actions/factories/registerFactory.ts
- packages/redux/src/wishlists/actions/factories/addWishlistItemFactory.ts
- packages/redux/src/wishlists/actions/factories/addWishlistSetFactory.ts
- packages/redux/src/wishlists/actions/factories/fetchWishlistFactory.ts
- packages/redux/src/wishlists/actions/factories/fetchWishlistSetFactory.ts
- packages/redux/src/wishlists/actions/factories/fetchWishlistSetsFactory.ts
- packages/redux/src/wishlists/actions/factories/removeWishlistItemFactory.ts
- packages/redux/src/wishlists/actions/factories/removeWishlistSetFactory.ts
- packages/redux/src/wishlists/actions/factories/updateWishlistItemFactory.ts
This fixes the `useBag` hook actions which were using stale `items` data when the actions were invoked in succession (like a call to removeItem is awaited and then a call to addItem is made). The fix is to remove the `items` from the callbacks and use `getState` to get the most updated state from the store.
Also, it was needed to await the `dispatch` calls to the bag success actions to make sure that when the `.then` callback is invoked all the middlewares have run first and the state in the store was updated. We will need to change all factory actions to await the dispatch of the success action (at least) eventually but on this PR I only included wishlist, bag and user authentication actions as they are the most problematic.
By sending us your contributions, you are agreeing that your …
> fix(redux): fix useBag hook actions

- packages/core/src/returns/client/__fixtures__/getReturnWorkflow.fixtures.js
- packages/core/src/returns/client/__tests__/__snapshots__/getReturnWorkflow.test.js.snap
- packages/core/src/returns/client/__tests__/getReturnWorkflow.test.js
- packages/core/src/returns/client/getReturnWorkflow.js
- packages/core/src/returns/client/index.js
This adds client and redux action for new getReturnWorkflow endpoint.
> feat(core|redux): add get return workflow endpoint

- packages/redux/package.json
- packages/redux/src/checkout/reducer.ts
- packages/redux/src/locale/reducer.ts
- packages/redux/src/orders/reducer.ts
- packages/redux/src/returns/reducer.ts
- packages/redux/src/users/addresses/reducer.ts
- yarn.lock
This updates immer requirements to version 9.0.19 and changes the imports to use named exports instead of default due to an issue with webpack importing.
- [] The code is commented, particularly in hard-to-understand areas
> fix(redux): fix immer imports to work with nodenext

- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
This PR solves a minor problem about three specific events (search, view_wishlist, view_cart) which weren't being sent with page_path and path_clean, this was because the type was being sent as page, to correct this we need to specify that trackEvent is being triggered with `type: TrackTypes.TRACK`.
None
> fix(react): fix ga4 events

- packages/core/src/analytics/Analytics.js
- packages/core/src/analytics/__fixtures__/commonData.fixtures.js
- packages/core/src/analytics/__fixtures__/pageData.fixtures.js
- packages/core/src/analytics/__tests__/analytics.test.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/utils/constants.js
- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/GTM/GTM.js
- packages/react/src/analytics/integrations/__fixtures__/analyticsPageData.fixtures.json
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/__tests__/GTM.test.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GTM.test.js.snap
- Added new property on track events, to set __blackoutAnalyticsEventId on GTM. This property is already used on other integrations to relation events on different integrations.
- Code refactor: created new constant on analytics package to define default property name for __blackoutAnalyticsEventId, avoiding possible inconsistencies.
None.
> feat(core|react): add unique id to GTM integration

- packages/analytics/src/__tests__/__snapshots__/index.test.ts.snap
- packages/analytics/src/__tests__/analytics.test.ts
- packages/analytics/src/utils/constants.ts
- packages/react/src/analytics/integrations/GA4/GA4.ts
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.ts
- packages/react/src/analytics/integrations/GA4/constants.ts
- packages/react/src/analytics/integrations/GTM/GTM.ts
- packages/react/src/analytics/integrations/GTM/__tests__/GTM.test.ts
- packages/react/src/analytics/integrations/GTM/__tests__/__snapshots__/GTM.test.ts.snap
- tests/__fixtures__/analytics/baseAnalyticsEventData.fixtures.ts
- Added new property on track events, to set __blackoutAnalyticsEventId
on GTM. This property is already used on other integrations to relation
events on different integrations.
- Code refactor: created new contant on analytics package to define
default property name for __blackoutAnalyticsEventId, avoiding possible inconsistencies.
None.
> feat(analytics|react): add unique id to GTM integration for next

- packages/react/src/contents/hooks/__tests__/__fixtures__/useSeoMetadata.fixtures.ts
- packages/react/src/locale/hooks/__tests__/useLocale.test.tsx
- packages/react/src/locale/hooks/useLocale.ts
- packages/redux/src/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/locale/__tests__/selectors.test.ts
- packages/redux/src/locale/__tests__/serverInitialState.test.ts
- packages/redux/src/locale/actionTypes.ts
- packages/redux/src/locale/reducer.ts
- packages/redux/src/locale/selectors.ts
- packages/redux/src/locale/serverInitialState.ts
- packages/redux/src/locale/types/actions.types.ts
- packages/redux/src/locale/types/reducer.types.ts
- tests/__fixtures__/locale/locale.fixtures.ts
- Change useLocale hook to use subfolder from locale state. 
> fix(redux): subfolder on useLocale & serverInitialState

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/analytics/integrations/Castle/index.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.ts
- packages/react/src/analytics/integrations/index.ts
- tests/__fixtures__/analytics/track/checkoutAbandonedTrackData.fixtures.mts
- Added parameters to checkout_abandoned event, regarding the analytics package improvements.
- On checkout_started switched two parameters for a method (`getDeliveryInformationDetails`) that returns those same parameters.
None
> feat(analytics|react): add parameters checkout abandoned event next

- packages/core/src/contents/redux/actions/__tests__/__snapshots__/doGetContent.test.js.snap
- packages/core/src/contents/redux/serverInitialState.js
- packages/react/src/content/hooks/__tests__/__fixtures__/Page.fixtures.js
- packages/react/src/content/hooks/__tests__/__snapshots__/useContentType.test.js.snap
- packages/react/src/content/hooks/__tests__/useContentType.test.js
- tests/__fixtures__/contents/contents.fixtures.js
- Changing serverInitialState `contentTypeCode` and `codes` params to depend on `seachResponse` entries. 
Note:
- Also, in discussing with the BE, it was found that the codes in the initial state only come with only one code. That why the changes in the `contents.fixtures`.
None
> fix(core): refactor server initial state to search content type code

- packages/react/src/bags/hooks/__tests__/useBag.test.tsx
- packages/react/src/bags/hooks/__tests__/useBagItem.test.tsx
- packages/react/src/bags/hooks/types/useBag.ts
- packages/react/src/bags/hooks/useBag.ts
- packages/react/src/bags/hooks/useBagItem.ts
This adds a config parameter to all actions that were missing it from `useBag` and `useBagItem` actions. Also, removed the `HandleAddOrUpdateItem` from the exported types as it is an internal type.
> feat: add config parameter to `useBag` and `useBagItem` actions

- packages/client/src/users/returns/__fixtures__/getUserReturnsLegacy.fixtures.ts
- packages/client/src/users/returns/__tests__/__snapshots__/getUserReturnsLegacy.test.ts.snap
- packages/client/src/users/returns/__tests__/getUserReturnsLegacy.test.ts
- packages/client/src/users/returns/getUserReturnsLegacy.ts
- packages/client/src/users/returns/index.ts
Add legacy fetch user returns endpoint
> feat(client): add legacy fetch user returns endpoint

- packages/client/src/checkout/types/patchCheckoutOrderItems.types.ts
- packages/redux/src/checkout/actions/__tests__/updateCheckoutOrderItems.test.ts
- tests/__fixtures__/checkout/checkout.fixtures.mts
This fixes the type `PatchCheckoutOrderItemsData` which should not require an object with an `operations` property inside the `checkoutItemPatchDocument` property but instead receive the array of operations directly.
> fix: fix `patchCheckoutOrderItems` types

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.ts
- tests/__fixtures__/analytics/track/shippingInfoAddedTrackData.fixtures.mts
Changes made on add_shipping_info regarding analytics package improvements.
- Removed address_finder parameter
- Added checkout_step and checkoutOrderId. 
None.
> feat: add parameters add shipping info event next

- packages/react/src/analytics/integrations/GTM/eventsMapper.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GTM.test.js.snap
This PR fixes a bug with the analytics GTM integration which was not passing the `orderId` parameter on the `order_completed` event.
> fix(react): add missing orderId parameter on order_completed event

- .eslintrc.js
This adds a pattern to `@typescript-eslint/no-restricted-imports` rule to prevent imports to `lodash` package as `lodash-es` should be used instead because of our packages being ESM-only.
> chore: prevent lodash imports in source

- packages/react/src/checkout/hooks/__tests__/useCheckoutOrderDetails.test.tsx
- packages/react/src/checkout/hooks/useCheckoutOrderDetails.ts
This fixes a possible infinite loop in `useCheckoutOrderDetails` when the redux store contains the details of another checkout order than the one the hook is requested to fetch, it will try infinitely to reset the details state because the reset action that is being used does not clear that particular state. To fix this, we use the `resetCheckout` to clear all checkout data instead.
> fix: fix possible infinite loop in `useCheckoutOrderDetails`

- .github/workflows/CI.yml
- patches/@lerna+conventional-commits+5.6.2.patch
- patches/@lerna+version+5.6.2.patch
- scripts/release.sh
This changes the pipeline to prevent commits that contain breaking changes from updating the major version of the packages as those are only supposed to be created when next is merged into main.
Unfortunately, the only was to make this work with lerna is to apply a patch to the version command to look for a specific flag parameter that was added for it.
This also applies some best practices to load github context variables into run scripts in CI workflow.
> chore: prevent automatic major version bumps to `main`

- packages/redux/src/contents/serverInitialState.ts
- tests/__fixtures__/contents/contents.fixtures.mts
- Changing serverInitialState `contentTypeCode` and `codes` params to depend on `seachResponse` entries. 
Note:
- Also, in discussing with the BE, it was found that the codes in the initial state only come with only one code. That why the changes in the `contents.fixtures`.
None
> fix(redux): refactor server initial state to search content type code

- packages/react/src/analytics/integrations/Castle/Castle.ts
- packages/react/src/analytics/integrations/Castle/__tests__/Castle.test.ts
- removed castle pageview event.
None.
> feat(react): remove castle pageview event tracking for `next`

- packages/client/src/__tests__/__snapshots__/index.test.ts.snap
- packages/client/src/orders/types/orderItem.types.ts
- packages/client/src/types/common/saleIntent.types.ts
- tests/__fixtures__/orders/orders.fixtures.mts
- tests/__fixtures__/products/productVariantsMerchantsLocations.fixtures.mts
- yarn.lock
- This adds `expectedFulfillmentDate` and `saleIntent` types to order item.
None.
> feat(client): add backorder types to order item

- packages/analytics/src/__tests__/__snapshots__/index.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/analytics/src/types/analytics.types.ts
- packages/analytics/src/utils/__tests__/getters.test.ts
- packages/analytics/src/utils/getters.ts
- packages/analytics/src/utils/hashUserData.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.ts
- tests/__fixtures__/analytics/track/orderCompletedTrackData.fixtures.mts
- yarn.lock
- update fields on `order_completed` event contract of GA4 and Omnitracking integration to add new fields.
None.
> feat(analytics|react): update order completed analytics event

- scripts/release.sh
This re-adds the setting of the origin url to include the `GITHUB_TOKEN` so that lerna can push as the `GH_TOKEN` variable is not enough as it will only be used for creating github releases.
> chore: fix release script

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.ts
- tests/__fixtures__/analytics/track/addressInfoAddedTrackData.fixtures.mts
- Added checkout step parameter to add_address_info event.
None.
> feat: add checkout step to analytics event

- packages/react/src/returns/hooks/__tests__/useUserReturns.test.ts
- packages/react/src/returns/hooks/types/useUserReturns.ts
- packages/react/src/returns/hooks/useUserReturns.ts
This adds the legacy flow to useUserReturns hook
None.
> feat(react): add legacy guest flow to useUserReturns hook

- .github/workflows/CreateRelease.yml
- .github/workflows/SendEmail.yml
This updates the github release title format to remove the `Release` string from it and use only the tag name as it will be the new default for the `main` releases.
> chore: update github release title format

- packages/redux/src/exchanges/__tests__/reducer.test.ts
- packages/redux/src/exchanges/reducer.ts
This fixes the exchanges result reducer by changing the return from action.payload.result to action.payload.
None.
> fix(redux): exchanges result reducer

- packages/client/src/bags/types/bag.types.ts
- packages/react/src/bags/hooks/__tests__/useBag.test.tsx
- packages/redux/src/bags/actions/__tests__/__snapshots__/addBagItem.test.ts.snap
- packages/redux/src/bags/actions/__tests__/__snapshots__/fetchBag.test.ts.snap
- packages/redux/src/bags/actions/__tests__/__snapshots__/removeBagItem.test.ts.snap
- packages/redux/src/bags/actions/__tests__/__snapshots__/updateBagItem.test.ts.snap
- tests/__fixtures__/bags/bag.fixtures.mts
- Added `promocodes` prop in bag client types.
> fix(redux|client): add promocodes prop in bag types

- packages/core/src/exchanges/redux/__tests__/reducer.test.js
- packages/core/src/exchanges/redux/reducer.js
This fixes the exchanges result reducer by changing the return from action.payload.result to action.payload.
None.
> fix(core): exchanges result reducer

- packages/client/src/orders/types/orderItem.types.ts
- tests/__fixtures__/orders/orders.fixtures.mts
This adds the missing isExchangeAvailable to the orderItem property
None.
> fix(client): add isExchangeAvailable to orderItem property

- packages/core/src/sharedWishlists/redux/index.js
- packages/core/src/sharedWishlists/redux/reducer.js
- Add an index missing file in shared wishlists redux.
- It also adjusts the initial state property from `id` to `isLoading`.
> fix(core): add missing index file in shared wishlists redux

- packages/react/src/bags/hooks/__tests__/useBag.test.tsx
- packages/react/src/bags/hooks/useBag.ts
- packages/react/src/returns/hooks/__tests__/useUserReturns.test.ts
- tests/__fixtures__/products/ids.fixtures.mts
- tests/__fixtures__/products/productSizes.fixtures.mts
This fixes the call to `handleFullUpdate` method in `useBag` to use the
correct parameters and changed the unit test to make sure this bug gets
caught.
Also, changed `enableAutoFetch` value to false in some tests from
`useUserReturns` tests to remove a warning of PromiseUnhandledException.
> fix: fix `useBag` wrong call to `handleFullUpdate`

- packages/client/src/__tests__/__snapshots__/index.test.ts.snap
- packages/client/src/payments/__fixtures__/postPaymentSession.fixtures.ts
- packages/client/src/payments/__tests__/__snapshots__/postPaymentSession.test.ts.snap
- packages/client/src/payments/__tests__/postPaymentSession.test.ts
- packages/client/src/payments/index.ts
- packages/client/src/payments/postPaymentSession.ts
- packages/client/src/payments/types/index.ts
- packages/client/src/payments/types/paymentInstrument.types.ts
- packages/client/src/payments/types/postPaymentIntentInstrument.types.ts
- packages/client/src/payments/types/postPaymentSession.types.ts
- tests/__fixtures__/payments/payments.fixtures.mts
This adds the `postPaymentSession` client and changes the types of the `method` property of both `PaymentInstrument` and
`PostPaymentIntentInstrumentData` types to `string` to give more flexibility.
> feat: add postPaymentSession client

- packages/analytics/src/integrations/Omnitracking/Omnitracking.ts
- packages/analytics/src/integrations/Omnitracking/__fixtures__/expectedTrackPayload.fixtures.ts
- packages/analytics/src/integrations/Omnitracking/types/Omnitracking.types.ts
- Add analytics versions field to omnitracking output payload.
None.
> feat(analytics): add analytics versions to omnitracking for `main`

- packages/redux/src/sharedWishlists/index.ts
- packages/redux/src/sharedWishlists/middlewares/__tests__/updateSharedWishlistUponItemsChanges.test.ts
- packages/redux/src/sharedWishlists/middlewares/index.ts
- packages/redux/src/sharedWishlists/middlewares/updateSharedWishlistUponItemsChanges.ts
- This adds the shared wishlist middleware that handles the update of the snapshot when a wishlist item is updated, added or deleted.
None
> feat(redux): add shared wishlist middleware for updating snapshop

- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/users/hooks/__tests__/useUserContact.test.ts
- packages/react/src/users/hooks/__tests__/useUserContacts.test.ts
- packages/react/src/users/hooks/index.ts
- packages/react/src/users/hooks/types/index.ts
- packages/react/src/users/hooks/types/useUserContact.types.ts
- packages/react/src/users/hooks/types/useUserContacts.types.ts
- packages/react/src/users/hooks/useUserContact.ts
- packages/react/src/users/hooks/useUserContacts.ts
- packages/redux/src/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/users/contacts/selectors.ts
This adds both new hooks for user contacts management, one for using with a single address and the other with the user contacts list.
None
> feat(react) useUserContact and useUserContacts hooks

- packages/client/src/__tests__/__snapshots__/index.test.ts.snap
- packages/client/src/checkout/types/checkoutSession.types.ts
- tests/__fixtures__/checkout/checkoutSessions.fixtures.mts
This adds the types for `checkoutOrderId`, `orderStatus`, `shippingAddress`, `billingAddress` and `clickAndCollect` to the `checkoutSession` type. It also changes the type for `orderId`.
> fix(client): checkout session types

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/client/src/__tests__/__snapshots__/index.test.ts.snap
- packages/client/src/checkout/types/checkoutSession.types.ts
- packages/client/src/checkout/types/postCheckoutSession.types.ts
- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/users/hooks/__tests__/useUserContact.test.ts
- packages/react/src/users/hooks/__tests__/useUserContacts.test.ts
- packages/react/src/users/hooks/index.ts
- packages/react/src/users/hooks/types/index.ts
- packages/react/src/users/hooks/types/useUserContact.types.ts
- packages/react/src/users/hooks/types/useUserContacts.types.ts
- packages/react/src/users/hooks/useUserContact.ts
- packages/react/src/users/hooks/useUserContacts.ts
- packages/redux/src/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/sharedWishlists/index.ts
- packages/redux/src/sharedWishlists/middlewares/__tests__/updateSharedWishlistUponItemsChanges.test.ts
- packages/redux/src/sharedWishlists/middlewares/index.ts
- packages/redux/src/sharedWishlists/middlewares/updateSharedWishlistUponItemsChanges.ts
- packages/redux/src/users/contacts/selectors.ts
- tests/__fixtures__/analytics/page/productPageData.fixtures.mts
- tests/__fixtures__/checkout/checkoutSessions.fixtures.mts
> Weekly release - dev-main-08-08-23

- packages/core/src/sharedWishlists/redux/__tests__/reducer.test.js
- packages/core/src/sharedWishlists/redux/middlewares/__tests__/getWishlistSetsUponSharedWishlistIdChanges.test.js
- packages/core/src/sharedWishlists/redux/middlewares/__tests__/updateSharedWishlistUponItemsChanges.test.js
- packages/core/src/sharedWishlists/redux/middlewares/getWishlistSetsUponSharedWishlistIdChanges.js
- packages/core/src/sharedWishlists/redux/middlewares/index.js
- packages/core/src/sharedWishlists/redux/middlewares/updateSharedWishlistUponItemsChanges.js
- packages/core/src/sharedWishlists/redux/reducer.js
This adds a middleware for getting the wishlist sets when the `sharedWishlistId` has changed. It ensures we are always accessing the updated data from the wishlist sets after creating or deleting a shared wishlist.
Also, the action `UPDATE_WISHLIST_SET_SUCCESS` was added to the `updateSharedWishlistUponItemsChanges` middleware and the shared wishlist reducer (result) was adjusted.
None
> feat(core): add middleware for getting the wishlist sets upon shared wishlist id changes

- packages/redux/src/sharedWishlists/middlewares/__tests__/getWishlistSetsUponSharedWishlistIdChanges.test.ts
- packages/redux/src/sharedWishlists/middlewares/__tests__/updateSharedWishlistUponItemsChanges.test.ts
- packages/redux/src/sharedWishlists/middlewares/getWishlistSetsUponSharedWishlistIdChanges.ts
- packages/redux/src/sharedWishlists/middlewares/index.ts
- packages/redux/src/sharedWishlists/middlewares/updateSharedWishlistUponItemsChanges.ts
This adds a middleware for getting the wishlist sets when the `sharedWishlistId` has changed. It ensures we are always accessing the updated data from the wishlist sets after creating or deleting a shared wishlist.
Also, the action `UPDATE_WISHLIST_SET_SUCCESS` was added to the `updateSharedWishlistUponItemsChanges` middleware.
None
> feat(redux): add share wishlist middleware for refetching wishlist sets

- packages/redux/src/sharedWishlists/__tests__/reducer.test.ts
- packages/redux/src/sharedWishlists/reducer.ts
- This adjusts the result slice in the shared wishlist reducer for handling the `REMOVE_SHARED_WISHLIST_SUCCESS` action.
None.
> fix(redux): adjust shared wishlists reducer

- packages/redux/src/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/checkout/actions/index.ts
Added the export for `fetchCheckoutOrderOperation` action as it was not being exported and causes the applications that use it to fail.
> fix: fix fetchCheckoutOrderOperation action not being exported

- packages/client/src/users/addresses/__tests__/putUserDefaultBillingAddress.test.ts
- packages/client/src/users/addresses/__tests__/putUserDefaultContactAddress.test.ts
- packages/client/src/users/addresses/__tests__/putUserDefaultShippingAddress.test.ts
- packages/client/src/users/addresses/putUserDefaultBillingAddress.ts
- packages/client/src/users/addresses/putUserDefaultContactAddress.ts
- packages/client/src/users/addresses/putUserDefaultShippingAddress.ts
This fixes the user addresses put requests that were specifying the incorrect arguments to the `axios.put` call.
Closes #846 
> fix: fix user addresses put requests

- packages/client/src/contents/types/contents.types.ts
- packages/redux/src/entities/types/contents.types.ts
This fixes `ContentMetadata` type to be more flexible.
- [] Tests for the respective changes have been added
> fix: content metadata type

- packages/react/src/analytics/integrations/AnalyticsApi/AnalyticsApi.ts
- packages/react/src/analytics/integrations/AnalyticsApi/__tests__/AnalyticsApi.test.ts
This PR removes the dependency of a marketing consent on the client-side Analytics API integration. 
The consent must be managed on the server side, as it is already passed to its endpoint along with all event data. We must only control the consent there and load the server-side integrations accordingly. 
> fix(analytics): remove analytics API consent dependency

- packages/react/src/authentication/hooks/__tests__/useSocialLogin.test.tsx
- packages/react/src/authentication/hooks/useSocialLogin.ts
- packages/redux/src/users/authentication/actions/__tests__/__snapshots__/createAccountLink.test.ts.snap
- packages/redux/src/users/authentication/actions/__tests__/__snapshots__/socialLogin.test.ts.snap
- packages/redux/src/users/authentication/actions/__tests__/socialLogin.test.ts
- packages/redux/src/users/authentication/actions/factories/createAccountLinkFactory.ts
- packages/redux/src/users/authentication/actions/factories/socialLoginFactory.ts
This fixes socialLogin and createAccountLink actions that were missing user id. Also, it renames useSocialLogin action from login to socialLogin, in order to prevent issues with the usual login action.
> fix: fix social login actions

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.ts
- tests/__fixtures__/analytics/track/paymentInfoAddedTrackData.fixtures.mts
- Add checkout_order_id (omni) and transaction_id (ga4) to payment_info_added event
- Updated unit tests as well.
None.
> feat: add parameters to payment info added event

- packages/analytics/src/__tests__/__snapshots__/index.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/types/EventType.ts
- packages/analytics/src/types/__tests__/__snapshots__/EventType.test.ts.snap
- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- tests/__fixtures__/analytics/track/index.mts
- tests/__fixtures__/analytics/track/sitePerformanceTrackData.fixtures.mts
Add new event to analytics: Site Performance.
- Add compatibility to omnitracking;
None.
> feat: add site performance measuring event to analytics for `main`

- packages/analytics/src/integrations/Omnitracking/__tests__/Omnitracking.test.ts
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.ts
- add new parameter `page number` for cases of endlessScrolling in interact content events (scrolling)
None. 
> feat: add parameters to interact content event for `main`

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- packages/core/src/analytics/types/__tests__/__snapshots__/eventTypes.test.js.snap
- packages/core/src/analytics/types/eventTypes.js
Add new event to analytics: Site Performance.
- Add compatibility to omnitracking;
None.
> feat: add site performance measuring event to analytics to `v1`

- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/react/src/analytics/integrations/GA4/eventMapping.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
- add new parameter `page number` for cases of endlessScrolling in interact content events (scrolling)
None.
> feat: add parameters to interact content event for `v1`

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.ts
- packages/react/src/analytics/integrations/GA4/validation/eventSchemas.ts
- packages/redux/src/analytics/middlewares/__tests__/wishlist.test.ts
- packages/redux/src/analytics/middlewares/wishlist.ts
- packages/redux/src/wishlists/types/actions.types.ts
- tests/__fixtures__/analytics/track/productAddedToWishlistTrackData.fixtures.mts
- tests/__fixtures__/analytics/track/productRemovedFromWishlistTrackData.fixtures.mts
- tests/__fixtures__/analytics/track/productUpdatedWishlistTrackData.fixtures.mts
- Add isMainWishlist parameter to wishlist related events
- Updated unit tests as well
None.
> feat: add isMainWishlist parameter to `main`

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.ts
- tests/__fixtures__/analytics/track/paymentInfoAddedTrackData.fixtures.mts
- tests/__fixtures__/analytics/track/placeOrderStartedTrackData.fixtures.mts
- Added checkout step parameter to two analytics events (place_order_started and payment_info_added).
- Updated unit tests for both events.
None.
> feat: add checkout step to analytics events `main`

- packages/core/src/analytics/__fixtures__/trackData.fixtures.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- packages/react/src/analytics/integrations/GA4/eventMapping.js
- packages/react/src/analytics/integrations/__fixtures__/gaData.fixtures.js
- packages/react/src/analytics/integrations/__tests__/__snapshots__/GA4.test.js.snap
- Added checkout step parameter to two analytics events (place_order_started and payment_info_added).
- Updated unit tests for both events.
None.
> feat: add checkout step to analytics events `v1`

- packages/core/src/orders/redux/selectors.js
This fixes guest orders not returning items by merchant
> fix(core): fix guest orders not returning items by merchant

- packages/client/src/users/authentication/getUserExternalLogins.ts
- packages/redux/src/entities/schemas/productsList.ts
- packages/redux/src/products/actions/__tests__/fetchProductListing.test.ts
- tests/__fixtures__/products/productsLists.fixtures.mts
This fixes `productsList` schema handling of the `filterSegments` property which was not finding the correct facet when the filter segment was not pointing to the first facet of the first facet group.
Closes #906 
> fix: fix `productsList` schema handling of `filterSegments`

- packages/client/src/contents/__tests__/getCommercePages.test.ts
- packages/client/src/contents/__tests__/getContentPage.test.ts
- packages/client/src/contents/types/commercePages.types.ts
- packages/client/src/contents/types/contentPage.types.ts
Include target **benefits** and target **segments** to Clients commerce pages and serverless API
None
> fix: add segments and benefits targets to commerce pages fetch

- packages/core/src/analytics/integrations/Omnitracking/__tests__/omnitracking-helper.test.js
- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/Omnitracking.test.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Add sizeItem to product_updated (size) event;
- Fix camelCase fields on omnitracking whitelisted parameters;
- Add warn when login or signup have method property missing;
- Add and fix omnitracking tests and snapshots.
None.
> feat: omnitracking minor changes for `v1`

- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Add productId parameter (that maps the first productId of lineItems parameter) to product_added_to_wishlist event.
- Add a helper to support this logic of mapping the first productId of lineItems.
- Updated snapshots
None.
> feat: add productId to analytics events `v1`

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/analytics/src/types/analytics.types.ts
- Add unitSalePrice to lineItems and product_details event.
- Add a helper to calculate unitSalePrice (price - discount).
- Updated snapshots
None.
> feat: add unitSalePrice to analytics events `main`

- packages/core/src/analytics/integrations/Omnitracking/definitions.js
- packages/core/src/analytics/integrations/Omnitracking/omnitracking-helper.js
- packages/core/src/analytics/integrations/__tests__/__snapshots__/Omnitracking.test.js.snap
- Add unitSalePrice to lineItems and product_details event.
- Add a helper to calculate unitSalePrice (price - discount).
- Updated snapshots
None.
> feat: add unitSalePrice to analytics events `v1`

- packages/core/src/entities/redux/__tests__/__snapshots__/reducer.test.js.snap
- packages/core/src/entities/redux/reducer/entitiesMapper.js
- packages/core/src/entities/schemas/exchangeFilter.js
- packages/core/src/exchanges/redux/__fixtures__/exchanges.fixtures.js
- packages/core/src/exchanges/redux/__tests__/reducer.test.js
- packages/core/src/exchanges/redux/__tests__/selectors.test.js
- packages/core/src/exchanges/redux/actionTypes.js
- packages/core/src/exchanges/redux/actions/__tests__/__snapshots__/doCreateExchangeFilter.test.js.snap
- packages/core/src/exchanges/redux/actions/__tests__/doCreateExchangeFilter.test.js
- packages/core/src/exchanges/redux/actions/__tests__/doResetExchangeFilters.test.js
- packages/core/src/exchanges/redux/actions/doCreateExchangeFilter.js
- packages/core/src/exchanges/redux/actions/doResetExchangeFilters.js
- packages/core/src/exchanges/redux/actions/index.js
- packages/core/src/exchanges/redux/index.js
- packages/core/src/exchanges/redux/reducer.js
- packages/core/src/exchanges/redux/selectors.js
BREAKING CHANGE: Exchange filters are now stored under entities by orderItemUuid (shippingOrderLineId). Previously the user wasn't able to fetch multiple filters because each request cleared the previous data, which this PR aims to fix.
> fix: save exchange filters by id

- packages/client/src/wishlists/types/wishlistSet.types.ts
This adds the sharedWishlistId property to the `WishtlistSet` type which was missing.
> chore: update wishlistset type to include sharedWishlistId

- packages/redux/src/brands/__tests__/utils.test.ts
- packages/redux/src/helpers/__tests__/buildQueryStringFromObject.test.ts
- packages/redux/src/helpers/buildQueryStringFromObject.ts
- packages/redux/src/products/serverInitialState/__tests__/lists.test.ts
- tests/__fixtures__/brands/brands.fixtures.mts
- tests/__fixtures__/products/productsLists.fixtures.mts
This reverts commit 871a98db22326e88566f98ce23d235695b39776a.
The change to buildQueryStringFromObject function broke range filters (like price). The original problem that caused this commit in the first place will be addressed in another PR as it will affect getSearchRedirectUrl util function in @farfetch/blackout-react.
> Revert "fix: buildQueryStringFromObject query construction"

- packages/client/src/products/types/facetValue.types.ts
- packages/redux/src/products/actions/__tests__/fetchProductListing.test.ts
- packages/redux/src/products/selectors/__tests__/listings.test.ts
- packages/redux/src/products/selectors/listings.ts
- tests/__fixtures__/products/productsLists.fixtures.mts
- tests/__fixtures__/products/state.fixtures.mts
This fixes the `getProductListingFacetGroups` selector as it was only
returning the `values` property containing only the facets for the
first value in the array.
Also, a fix for the type `FacetValue`'s slug property was added.
> fix: fix `getProductListingFacetGroups` selector

- packages/react/src/checkout/hooks/__tests__/useCheckout.test.tsx
- packages/react/src/checkout/hooks/useCheckout.ts
- packages/redux/src/checkout/__tests__/selectors.test.ts
- tests/__fixtures__/checkout/checkout.fixtures.mts
We understand that the responsibility for exposing delivery bundles data lies with `useCheckout`. So I opened this PR in which I get the delivery bundles in the context of redux and expose it in the `useCheckout` hook. I also take the opportunity to add a key to the `useCheckout` that represents which delivery bundle has been selected.
> feat: add delivery bundles usecheckout

- packages/analytics/src/integrations/Omnitracking/__tests__/__snapshots__/Omnitracking.test.ts.snap
- packages/analytics/src/integrations/Omnitracking/__tests__/omnitracking-helper.test.ts
- packages/analytics/src/integrations/Omnitracking/definitions.ts
- packages/analytics/src/integrations/Omnitracking/omnitracking-helper.ts
- packages/react/src/analytics/integrations/GA4/__tests__/__snapshots__/GA4.test.ts.snap
- tests/__fixtures__/analytics/track/productClickedTrackData.fixtures.mts
- Added itemListName parameter to some analytics events on omnitracking side.
- Updated `getRecommendationsTrackingData` function regarding a specific case: send moduleTitle and moduleId only when it's a recommendations related event. This meets the changes requested by the data team, which asks for moduleTitle and itemListName on events that are related to recommendations, otherwise, only itemListName.
- Updated unit tests as well.
None.
> feat: add itemListName parameter to analytics events `main`

- packages/client/src/settings/types/getAccountSetting.ts
- packages/redux/src/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/settings/reducer/index.ts
This fixes an issue with settings reducer export, it was missing the export needed for imports using object destructuring and fixed the type of the property details in the AccountSetting type. We need it to be dynamic since backend is always pushing for new settings configurations. 
None
> fix(client|redux): account settings type and reducer export

- packages/redux/src/products/reducer/__tests__/recentlyViewed.test.ts
- packages/redux/src/products/reducer/recentlyViewedProducts.ts
- tests/__fixtures__/products/recentlyViewed.fixtures.mts
- Fixed the order of the data presented on recently viewed, I've added a sort by date.
- Adjusted some unit tests and added another to check specifically this logic of sorting.
None.
> fix(redux): add sort by date on recently viewed `main`

- packages/core/src/recentlyViewed/redux/__mocks__/getRecentlyViewed.js
- packages/core/src/recentlyViewed/redux/__tests__/reducer.test.js
- packages/core/src/recentlyViewed/redux/reducer.js
- Fixed the order of the data presented on recently viewed, I've added a sort by date.
- Adjusted some unit tests and added another to check specifically this logic of sorting.
None.
> fix(core): add sort by date on recently viewed `v1`

- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/analytics/integrations/GA4/GA4.ts
- packages/react/src/analytics/integrations/GA4/constants.ts
- packages/react/src/analytics/integrations/GA4/types/index.ts
- packages/react/src/analytics/integrations/GTM/GTM.ts
- packages/react/src/analytics/integrations/GTM/constants.ts
- packages/react/src/analytics/integrations/GTM/gtmTag.ts
- packages/react/src/analytics/integrations/GTM/types/index.ts
- packages/react/src/analytics/integrations/index.ts
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/GoogleConsentMode.ts
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/__tests__/GoogleConsentMode.test.ts
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/__tests__/__snapshots__/GoogleConsentMode.test.ts.snap
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/index.ts
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/types.ts
- packages/react/src/analytics/integrations/shared/index.ts
- add support to consent management protocol v2 (analytics)
None.
> feat: add support to consent management protocol v2 to `main`

- packages/react/src/__tests__/__snapshots__/index.test.ts.snap
- packages/react/src/checkout/draftOrders/__tests__/useDraftOrder.test.tsx
- packages/react/src/checkout/draftOrders/__tests__/useDraftOrders.test.tsx
- packages/react/src/checkout/draftOrders/hooks/index.ts
- packages/react/src/checkout/draftOrders/hooks/types/index.ts
- packages/react/src/checkout/draftOrders/hooks/types/useDraftOrder.ts
- packages/react/src/checkout/draftOrders/hooks/types/useDraftOrders.ts
- packages/react/src/checkout/draftOrders/hooks/useDraftOrder.ts
- packages/react/src/checkout/draftOrders/hooks/useDraftOrders.ts
- packages/react/src/checkout/draftOrders/index.ts
- packages/react/src/checkout/index.ts
- packages/redux/src/__tests__/__snapshots__/index.test.ts.snap
- packages/redux/src/checkout/draftOrders/actions/__tests__/resetDraftOrders.test.ts
- packages/redux/src/checkout/draftOrders/actions/index.ts
- packages/redux/src/checkout/draftOrders/actions/resetDraftOrders.ts
- tests/__fixtures__/checkout/draftOrders.fixtures.mts
This PR is about creating Draft Orders React.
Basically, two React hooks are created for the Draft Orders Redux logic. The first custom hook `useDraftOrders` is responsible for returning the states of the `get`, `update`, `update item`, `remove` and `remove item` actions of a draft order. It also stores the draft order in a state.
The second custom hook `useDraftOrders` is responsible for returning the states of the `create` and `get all` draft orders actions. Just like the first one, it stores the draft orders in a state.
For the sake of responsibility we assign draft order creation to the custom hook `useDraftOrders` …
> feat(react): create package draft orders react 

- packages/react/src/users/hooks/__tests__/useUser.test.ts
- packages/react/src/users/hooks/useUser.ts
This fixes the bug with the `useUser` hook which could enter an infinite loop when enableAutoFetch is set to true.
> fix: fix useUser hook infinite loading

- packages/redux/src/checkout/actions/__tests__/__snapshots__/updateCheckoutOrder.test.ts.snap
- packages/redux/src/checkout/actions/__tests__/updateCheckoutOrder.test.ts
- packages/redux/src/checkout/actions/factories/updateCheckoutOrderFactory.ts
This fixes the updateCheckoutOrderFactory that was throwing an error when the update trigger the recovery of the
order which will return a different
orderId than the one that was passed to the call.
> fix: fix updateCheckoutOrder factory recovery case

- packages/redux/src/products/actions/__tests__/__snapshots__/fetchRecentlyViewedProducts.test.ts.snap
- packages/redux/src/products/reducer/__tests__/recentlyViewed.test.ts
- packages/redux/src/products/reducer/recentlyViewedProducts.ts
- packages/redux/src/products/selectors/__tests__/recentlyViewed.test.ts
- tests/__fixtures__/products/recentlyViewed.fixtures.mts
This fixes recentlyViewedProducts reducer to sort the products by descending order instead of ascending.
> fix: fix recentlyViewedProducts reducer to sort descending

- packages/core/src/addresses/client/__fixtures__/deleteDefaultBillingAddress.fixtures.js
- packages/core/src/addresses/client/__fixtures__/deleteDefaultShippingAddress.fixtures.js
- packages/core/src/addresses/client/__tests__/__snapshots__/deleteDefaultBillingAddress.test.js.snap
- packages/core/src/addresses/client/__tests__/__snapshots__/deleteDefaultShippingAddress.test.js.snap
- packages/core/src/addresses/client/__tests__/deleteDefaultBillingAddress.test.js
- packages/core/src/addresses/client/__tests__/deleteDefaultShippingAddress.test.js
- packages/core/src/addresses/client/deleteDefaultBillingAddress.js
- packages/core/src/addresses/client/deleteDefaultShippingAddress.js
- packages/core/src/addresses/client/index.js
- packages/core/src/addresses/redux/__tests__/reducer.test.js
- packages/core/src/addresses/redux/actionTypes.js
- packages/core/src/addresses/redux/actions/__tests__/__snapshots__/doDeleteDefaultBillingAddress.test.js.snap
- packages/core/src/addresses/redux/actions/__tests__/__snapshots__/doDeleteDefaultShippingAddress.test.js.snap
- packages/core/src/addresses/redux/actions/__tests__/doDeleteDefaultBillingAddress.test.js
- packages/core/src/addresses/redux/actions/__tests__/doDeleteDefaultShippingAddress.test.js
- packages/core/src/addresses/redux/actions/doDeleteDefaultBillingAddress.js
- packages/core/src/addresses/redux/actions/doDeleteDefaultShippingAddress.js
- packages/core/src/addresses/redux/actions/index.js
- packages/core/src/addresses/redux/reducer.js
- packages/core/src/entities/redux/__tests__/__snapshots__/reducer.test.js.snap
This adds the following endpoints to the v1 version:
DELETE /users​/{id}​/addresses​/shipping​/current > Unsets the default shipping address of the user.
DELETE /users​/{id}​/addresses​/billing​/current > Unsets the default billing address of the user.
> feat: expose missing address endpoints on v1

- packages/react/src/analytics/integrations/GA4/GA4.ts
- packages/react/src/analytics/integrations/GA4/__tests__/GA4.test.ts
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/GoogleConsentMode.ts
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/types.ts
-  add advanced mode gcm for `main`
> feat: add advanced mode gcm for `main`

- packages/react/src/analytics/integrations/AnalyticsApi/AnalyticsApi.js
- packages/react/src/analytics/integrations/GA4/GA4.js
- packages/react/src/analytics/integrations/__tests__/AnalyticsApi.test.js
- packages/react/src/analytics/integrations/__tests__/GA4.test.js
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/GoogleConsentMode.js
- add advanced mode to gcm
- remove category requirement on Analytics API integration. 
> Feat add advanced mode gcm on `v1`

- packages/core/src/analytics/utils/getters.js
- packages/react/src/analytics/analytics.js
- packages/react/src/analytics/constants.js
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/GoogleConsentMode.js
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/__tests__/GoogleConsentMode.test.js
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/__tests__/__snapshots__/GoogleConsentMode.test.js.snap
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/cookieUtils.js
This adds support for sharing google consent
mode with other apps such as Luxury Checkout
through a cookie set for the same domain.
> feat: add support for sharing gcm v1

- packages/analytics/src/utils/getters.ts
- packages/react/src/analytics/analytics.ts
- packages/react/src/analytics/constants.ts
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/GoogleConsentMode.ts
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/__tests__/GoogleConsentMode.test.ts
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/__tests__/__snapshots__/GoogleConsentMode.test.ts.snap
- packages/react/src/analytics/integrations/shared/GoogleConsentMode/cookieUtils.ts
This adds support for sharing google consent
mode with other apps such as Luxury Checkout
through a cookie set for the same domain.
> feat: add support for sharing gcm

- packages/redux/src/products/serverInitialState/listings.ts
This fixes a validation of the products serverInitialState where we validate if the referencedListing has a value, both null and empty arrays are possible outputs so we need to include the empty array validation by length to avoid the error by spreading the first of the referencedListings.
This has been tested in Whitelabel.
No.
> fix: referencedListing serverInitialState Validation
